// Generated by tools/voice.py from group.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("group", {
 "lines": {
  "hook.1": "So far, every query returned rows. Now the bakery wants numbers.",
  "hook.2": "How many orders came in? What sells best? Who are the regulars?",
  "hook.3": "Each answer squeezes many rows into a few. That's what this lesson is about.",
  "agg.1": "Here are all sixteen orders.",
  "agg.2": "COUNT star turns them into one row, with one number: sixteen.",
  "agg.3": "COUNT, SUM, AVG, MIN and MAX each turn many rows into one value. They're called <k id=\"aggregate\">aggregate functions</k>.",
  "agg.4": {
   "caption": "On the eight products: the prices add up to <b>36.10</b>, and average <b>4.51</b>. Cheapest <b>2.80</b>, dearest <b>6.50</b>.",
   "voice": "On the eight products: the prices add up to thirty-six ten, and average four fifty-one. The cheapest is two eighty, the dearest six fifty."
  },
  "count.ask": "Ten customers. How many does COUNT of phone return?",
  "count.ten": "It's seven. Three customers have no phone.",
  "count.seven": "Seven. You remembered the missing phones.",
  "count.three": "Three is how many are missing. COUNT of phone returns seven.",
  "count.1": "<k id=\"count-column\">COUNT of a column</k> skips NULLs. COUNT star counts every row. Interviewers love that difference.",
  "group.1": "Next question: how many orders are paid, pending, or refunded?",
  "group.2": "<b>GROUP BY status</b> sorts the rows into one pile per status.",
  "group.3": "Then each pile collapses into a single row, and COUNT runs once per pile.",
  "group.4": "Three statuses, three rows. That's <k id=\"group-by\">GROUP BY</k>.",
  "group.5": "The result has a new <k>grain</k>: one row per status, not one per order. Always know the grain of your result.",
  "city.1": "Your turn. How many customers live in each city?",
  "city.ask": "Write the query: the city, and a count.",
  "city.hint": {
   "caption": "<b>SELECT city, COUNT(*)</b> from customers, then <b>GROUP BY city</b>.",
   "voice": "Select the city and count star from customers, then group by city."
  },
  "city.error": "The database couldn't run that. The message under the editor says why.",
  "city.extra": "Too many rows. Is there a GROUP BY?",
  "city.missing": "Some cities are missing, or the counts are off. Group by city and count every row.",
  "city.columns": "Just two columns: the city, and the count.",
  "city.done": "Seven rows. Notice NULL: Raj has no city, and missing values form a group of their own.",
  "bare.1": {
   "caption": "Here's a mistake that's easy to make. Group orders by customer, but also select <b>ordered_at</b>.",
   "voice": "Here's a mistake that's easy to make. Group orders by customer, but also select the order date."
  },
  "bare.2": "Maya has four orders, with four dates. Her group gets one row. Which date goes in it?",
  "bare.3": "PostgreSQL refuses to guess, and rejects the query. SQLite quietly picks one. That's a <k id=\"bare-column\">bare column</k>.",
  "bare.4": "The rule: every selected column is either grouped, or wrapped in an aggregate. MAX of ordered at gives Maya's latest order.",
  "having.1": "The bakery wants its regulars: customers with at least two orders.",
  "having.2": "WHERE can't do it. It runs before grouping, and there's no count yet.",
  "having.3": "<k id=\"having\">HAVING</k> filters groups, after they're counted. Maya, Omar, Ana and Yuki make the cut.",
  "having.4": "Now count only paid orders. WHERE drops the unpaid rows first, then the groups are counted.",
  "having.ask": "Is Omar still a regular?",
  "having.yes": "Look again. Omar's second order is still pending.",
  "having.no": "Right. One of Omar's two orders is pending.",
  "having.5": "WHERE filters rows before grouping. HAVING filters groups after. The full order is FROM, WHERE, GROUP BY, HAVING, SELECT.",
  "best.1": "Your turn. The bakery wants its best sellers: products that sold at least five units in total.",
  "best.ask": "Group by product name, and keep the big groups.",
  "best.hint": {
   "caption": "Sum the <b>quantity</b> per product, then <b>HAVING SUM(i.quantity) &gt;= 5</b>.",
   "voice": "Sum the quantity per product, then keep the groups having a sum of at least five."
  },
  "best.error": "The database couldn't run that. Read the message, then try again.",
  "best.extra": "Too many products. Filter the groups with HAVING.",
  "best.missing": "Some best sellers are missing. Are you summing the quantity, not counting rows?",
  "best.columns": "Two columns: the product's name, and its total.",
  "best.done": "Four products. Croissants lead with ten.",
  "fanout.1": "Last trap, and it's one you've seen before. Count each customer's orders, but also join their items.",
  "fanout.2": "Maya shows seven orders. She has four. The join repeated each order once per item.",
  "fanout.3": "COUNT star counts rows, and fan-out made extra rows.",
  "fanout.4": "<k id=\"count-distinct\">COUNT DISTINCT</k> on the order ID counts each order once. Maya's back to four.",
  "fanout.5": "When a joined total looks too big, check the grain before you trust it.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "A table has 10 rows, and 3 of them have a NULL phone. What do <code>COUNT(*)</code> and <code>COUNT(phone)</code> return?",
   "voice": "A table has ten rows, and three have a null phone. What do count star and count of phone return?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "COUNT star counts rows. COUNT of a column skips NULLs.",
  "quiz.q2": {
   "caption": "You need customers with more than 5 orders. Where does the condition go?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "The count only exists after grouping, so it's a HAVING condition. WHERE runs before any group exists.",
  "quiz.q3": {
   "caption": "<code>SELECT customer_id, ordered_at, COUNT(*) FROM orders GROUP BY customer_id</code>. What does PostgreSQL do?",
   "voice": "Select customer ID, the order date, and count star, from orders, grouped by customer ID. What does Postgres do?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "ordered_at is a bare column: neither grouped nor aggregated. Postgres rejects it. Wrap it, like MAX of ordered at.",
  "quiz.q4": {
   "caption": "Orders per customer looks too high after joining order_items. The fix?",
   "voice": "Orders per customer looks too high after joining order items. What's the fix?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "The join repeats each order per item. Count distinct order IDs, or count before joining.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. Aggregates squeeze rows into numbers. GROUP BY sets the grain. And HAVING filters the groups.",
  "finish.2": "Next up: questions inside questions, with subqueries and CTEs."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "aggregate": {
   "term": "Aggregate function",
   "def": "A function that turns many rows into one value: COUNT, SUM, AVG, MIN or MAX."
  },
  "count-column": {
   "term": "COUNT(column)",
   "def": "Counts the rows where that column isn't NULL. COUNT(*) counts every row."
  },
  "group-by": {
   "term": "GROUP BY",
   "def": "Sorts rows into groups that share a value, then returns one row per group. Aggregates are computed per group."
  },
  "grain": {
   "term": "Grain",
   "def": "What one row of a result stands for: one order, one customer, one day. GROUP BY sets it."
  },
  "bare-column": {
   "term": "Bare column",
   "def": "A selected column that's neither grouped nor aggregated. PostgreSQL rejects it; SQLite quietly picks a value from some row."
  },
  "having": {
   "term": "HAVING",
   "def": "Filters groups after GROUP BY, using aggregates. WHERE filters rows before grouping."
  },
  "count-distinct": {
   "term": "COUNT(DISTINCT \u2026)",
   "def": "Counts different values once each. The usual fix when a join has repeated rows."
  }
 },
 "audio": {
  "agg.1": {
   "hash": "de12ea245103",
   "ms": 1980
  },
  "agg.2": {
   "hash": "c7f2b6434afb",
   "ms": 5040
  },
  "agg.3": {
   "hash": "18026e089fe4",
   "ms": 9108
  },
  "agg.4": {
   "hash": "4566a32cc474",
   "ms": 9396
  },
  "bare.1": {
   "hash": "2ed4a465adcc",
   "ms": 6120
  },
  "bare.2": {
   "hash": "013b1a381d5e",
   "ms": 5796
  },
  "bare.3": {
   "hash": "37d2f952f13c",
   "ms": 7272
  },
  "bare.4": {
   "hash": "96557b308532",
   "ms": 7164
  },
  "best.1": {
   "hash": "fa5e84a1a1eb",
   "ms": 6696
  },
  "best.ask": {
   "hash": "8825dca5dd74",
   "ms": 3312
  },
  "best.columns": {
   "hash": "baa83f2e2404",
   "ms": 3420
  },
  "best.done": {
   "hash": "287f33d760b2",
   "ms": 2988
  },
  "best.error": {
   "hash": "81c2cc0a2d89",
   "ms": 4176
  },
  "best.extra": {
   "hash": "7d2fde9db183",
   "ms": 2988
  },
  "best.hint": {
   "hash": "414df3223a6d",
   "ms": 4572
  },
  "best.missing": {
   "hash": "b6207e054955",
   "ms": 4752
  },
  "city.1": {
   "hash": "a20a0717c20a",
   "ms": 3564
  },
  "city.ask": {
   "hash": "5811e8c837d4",
   "ms": 3672
  },
  "city.columns": {
   "hash": "f0fa48a9eea6",
   "ms": 3024
  },
  "city.done": {
   "hash": "f8d4e0d45adb",
   "ms": 6804
  },
  "city.error": {
   "hash": "ab049c0f6f83",
   "ms": 4392
  },
  "city.extra": {
   "hash": "e5b04675d787",
   "ms": 2988
  },
  "city.hint": {
   "hash": "c4f69f7dc3ea",
   "ms": 3996
  },
  "city.missing": {
   "hash": "693932923b2b",
   "ms": 5472
  },
  "count.1": {
   "hash": "a9085c5b07a4",
   "ms": 7596
  },
  "count.ask": {
   "hash": "ffe31abebeb2",
   "ms": 3420
  },
  "count.seven": {
   "hash": "2302de6b1967",
   "ms": 3024
  },
  "count.ten": {
   "hash": "a265abfd2ac4",
   "ms": 3708
  },
  "count.three": {
   "hash": "dc3ba870bd77",
   "ms": 5112
  },
  "fanout.1": {
   "hash": "40eee9769e33",
   "ms": 6264
  },
  "fanout.2": {
   "hash": "cd71cc1dcf03",
   "ms": 6624
  },
  "fanout.3": {
   "hash": "e39e4eb367ec",
   "ms": 3816
  },
  "fanout.4": {
   "hash": "cb57414f21d9",
   "ms": 5472
  },
  "fanout.5": {
   "hash": "8ab6a22d1fcf",
   "ms": 4320
  },
  "finish.1": {
   "hash": "ccfea034d877",
   "ms": 8208
  },
  "finish.2": {
   "hash": "f30faff2d67c",
   "ms": 5760
  },
  "group.1": {
   "hash": "dea412bd7406",
   "ms": 4320
  },
  "group.2": {
   "hash": "d72ebbfcf4c2",
   "ms": 3996
  },
  "group.3": {
   "hash": "9ebea8a60a43",
   "ms": 5220
  },
  "group.4": {
   "hash": "0cede18d138d",
   "ms": 4067
  },
  "group.5": {
   "hash": "ecf3167fd4fb",
   "ms": 8064
  },
  "having.1": {
   "hash": "57741be5ca99",
   "ms": 4392
  },
  "having.2": {
   "hash": "cfe744452778",
   "ms": 3996
  },
  "having.3": {
   "hash": "b47b15ee8f1d",
   "ms": 6660
  },
  "having.4": {
   "hash": "07d117313418",
   "ms": 5724
  },
  "having.5": {
   "hash": "10b65eec46ab",
   "ms": 9396
  },
  "having.ask": {
   "hash": "71d5bc8ebcca",
   "ms": 1656
  },
  "having.no": {
   "hash": "05e2e76ef06d",
   "ms": 3492
  },
  "having.yes": {
   "hash": "b233000137ed",
   "ms": 3600
  },
  "hook.1": {
   "hash": "f499ef6ffb7f",
   "ms": 5400
  },
  "hook.2": {
   "hash": "49467dedf345",
   "ms": 4284
  },
  "hook.3": {
   "hash": "b7229b9938df",
   "ms": 5796
  },
  "keywords.1": {
   "hash": "52c9899fd888",
   "ms": 2916
  },
  "keywords.ask": {
   "hash": "9e5d200f6173",
   "ms": 4140
  },
  "keywords.done": {
   "hash": "b410b19a541a",
   "ms": 4536
  },
  "keywords.hint": {
   "hash": "520960a4916d",
   "ms": 3060
  },
  "quiz.intro": {
   "hash": "08fdf9d19fee",
   "ms": 1476
  },
  "quiz.pass": {
   "hash": "1e2c41acf108",
   "ms": 2016
  },
  "quiz.q1": {
   "hash": "c2be34ee961e",
   "ms": 6840
  },
  "quiz.q1-why": {
   "hash": "c74a99505946",
   "ms": 3924
  },
  "quiz.q2": {
   "hash": "fb11d818fd37",
   "ms": 4356
  },
  "quiz.q2-why": {
   "hash": "47bbf9422a66",
   "ms": 6084
  },
  "quiz.q3": {
   "hash": "6adfb66a7d69",
   "ms": 8928
  },
  "quiz.q3-why": {
   "hash": "4b2132ca8ca4",
   "ms": 9324
  },
  "quiz.q4": {
   "hash": "9ef119a6b0d8",
   "ms": 5004
  },
  "quiz.q4-why": {
   "hash": "4a416714ba92",
   "ms": 6624
  },
  "quiz.retry": {
   "hash": "674b74cededc",
   "ms": 4067
  },
  "quiz.right1": {
   "hash": "5df4176b3959",
   "ms": 864
  },
  "quiz.right2": {
   "hash": "e99e52b00ddc",
   "ms": 1116
  },
  "quiz.right3": {
   "hash": "bbb1d6dfd81d",
   "ms": 864
  }
 }
});
