// Generated by tools/voice.py from group.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("group", {
 "lines": {
  "hook.1": "So far, every query returned rows. Now the bakery wants numbers.",
  "hook.2": "How many orders came in? What sells best? Who are the regulars?",
  "hook.3": "Each answer squeezes many rows into a few. That's what this lesson is about.",
  "goals.intro": "Here's what you'll be able to do by the end of this lesson.",
  "goals.1": "One. Turn many rows into one value with COUNT, SUM, AVG, MIN and MAX, and know which NULLs they skip.",
  "goals.2": "Two. Group rows with GROUP BY, say what one result row stands for, and keep every column grouped or aggregated.",
  "goals.3": "Three. Filter rows with WHERE and groups with HAVING, and count correctly after a join.",
  "agg.1": "Here are all sixteen orders.",
  "agg.2": "COUNT star turns them into one row, with one number: sixteen.",
  "agg.3": "COUNT, SUM, AVG, MIN and MAX each turn many rows into one value. They're called <k id=\"aggregate\">aggregate functions</k>.",
  "agg.4": {
   "caption": "On the eight products: the prices add up to <b>36.10</b>, and average <b>4.51</b>. Cheapest <b>2.80</b>, dearest <b>6.50</b>.",
   "voice": "On the eight products: the prices add up to thirty-six ten, and average four fifty-one. The cheapest is two eighty, the dearest six fifty."
  },
  "count.ask": "Ten customers. How many does COUNT of phone return?",
  "count.ten": "It's seven. Three customers have no phone.",
  "count.seven": "Seven. You remembered the missing phones.",
  "count.three": "Three is how many are missing. COUNT of phone returns seven.",
  "count.1": "<k id=\"count-column\">COUNT of a column</k> skips NULLs. COUNT star counts every row. Interviewers love that difference.",
  "group.1": "Next question: how many orders are paid, pending, or refunded?",
  "group.2": "<b>GROUP BY status</b> sorts the rows into one pile per status.",
  "group.3": "Then each pile collapses into a single row, and COUNT runs once per pile.",
  "group.4": "Three statuses, three rows. That's <k id=\"group-by\">GROUP BY</k>.",
  "group.5": "The result has a new <k>grain</k>: one row per status, not one per order. Always know the grain of your result.",
  "city.1": "Your turn. How many customers live in each city?",
  "city.ask": "Write the query: the city, and a count.",
  "city.hint": {
   "caption": "<b>SELECT city, COUNT(*)</b> from customers, then <b>GROUP BY city</b>.",
   "voice": "Select the city and count star from customers, then group by city."
  },
  "city.error": "The database couldn't run that. The message under the editor says why.",
  "city.extra": "Too many rows. Is there a GROUP BY?",
  "city.missing": "Some cities are missing, or the counts are off. Group by city and count every row.",
  "city.columns": "Just two columns: the city, and the count.",
  "city.done": "Seven rows. Notice NULL: Raj has no city, and missing values form a group of their own.",
  "bare.1": {
   "caption": "Here's a mistake that's easy to make. Group orders by customer, but also select <b>ordered_at</b>.",
   "voice": "Here's a mistake that's easy to make. Group orders by customer, but also select the order date."
  },
  "bare.2": "Maya has four orders, with four dates. Her group gets one row. Which date goes in it?",
  "bare.3": "PostgreSQL refuses to guess, and rejects the query. SQLite quietly picks one. That's a <k id=\"bare-column\">bare column</k>.",
  "bare.4": "The rule: every selected column is either grouped, or wrapped in an aggregate. MAX of ordered at gives Maya's latest order.",
  "having.1": "The bakery wants its regulars: customers with at least two orders.",
  "having.2": "WHERE can't do it. It runs before grouping, and there's no count yet.",
  "having.3": "<k id=\"having\">HAVING</k> filters groups, after they're counted. Maya, Omar, Ana and Yuki make the cut.",
  "having.4": "Now count only paid orders. WHERE drops the unpaid rows first, then the groups are counted.",
  "having.ask": "Is Omar still a regular?",
  "having.yes": "Look again. Omar's second order is still pending.",
  "having.no": "Right. One of Omar's two orders is pending.",
  "having.5": "WHERE filters rows before grouping. HAVING filters groups after. The full order is FROM, WHERE, GROUP BY, HAVING, SELECT.",
  "best.1": "Your turn. The bakery wants its best sellers: products that sold at least five units in total.",
  "best.ask": "Group by product name, and keep the big groups.",
  "best.hint": {
   "caption": "Sum the <b>quantity</b> per product, then <b>HAVING SUM(i.quantity) &gt;= 5</b>.",
   "voice": "Sum the quantity per product, then keep the groups having a sum of at least five."
  },
  "best.error": "The database couldn't run that. Read the message, then try again.",
  "best.extra": "Too many products. Filter the groups with HAVING.",
  "best.missing": "Some best sellers are missing. Are you summing the quantity, not counting rows?",
  "best.columns": "Two columns: the product's name, and its total.",
  "best.done": "Four products. Croissants lead with ten.",
  "fanout.1": "Last trap, and it's one you've seen before. Count each customer's orders, but also join their items.",
  "fanout.2": "Maya shows seven orders. She has four. The join repeated each order once per item.",
  "fanout.3": "COUNT star counts rows, and fan-out made extra rows.",
  "fanout.4": "<k id=\"count-distinct\">COUNT DISTINCT</k> on the order ID counts each order once. Maya's back to four.",
  "fanout.5": "When a joined total looks too big, check the grain before you trust it.",
  "recap.intro": "Let's look back at what you can do now.",
  "recap.1": "An aggregate squeezes many rows into one value. COUNT star counts rows. COUNT of phone skips the three missing phones: ten versus seven.",
  "recap.2": "GROUP BY turns each pile of rows into one row. That's the grain. Every other column needs an aggregate, never a bare column.",
  "recap.3": "WHERE drops rows before grouping. HAVING drops groups after they're counted. Count only paid orders, and Omar is no longer a regular.",
  "check.intro": "Now three quick checks. Each asks you to use an idea, not just name it.",
  "check.q1": {
   "caption": "<code>COUNT(city)</code> and <code>COUNT(DISTINCT city)</code> on the customers. Raj has no city; the rest live in six different cities. What comes back?",
   "voice": "Count of city, and count distinct city, on the customers. Raj has no city, and the rest live in six different cities. What comes back?"
  },
  "check.q1-why": "Nine and six. COUNT of city skips Raj's NULL. DISTINCT counts each city once, and NULL is never counted.",
  "check.q2": {
   "caption": "<code>SELECT category, name, SUM(price) FROM products GROUP BY category</code>. What's wrong?",
   "voice": "Select the category, the name, and the sum of the prices from products, grouped by category. What's wrong?"
  },
  "check.q2-why": "Name is a bare column. Each category has several products, so there's no single name. Postgres rejects it; SQLite quietly picks one.",
  "check.q3": "Products with at least five units sold, counting only paid orders. Where does each condition go?",
  "check.q3-why": "The status is a fact about one row, so it goes in WHERE, before grouping. The sum only exists per group, so it goes in HAVING.",
  "check.right1": "Right.",
  "check.right2": "Exactly.",
  "check.right3": "Correct.",
  "check.pass": {
   "caption": "<b>{right} / 3</b>. The ideas are sticking.",
   "voice": "Nicely done. The ideas are sticking."
  },
  "check.retry": {
   "caption": "<b>{right} / 3</b>. The goals marked revisit are the ones to replay.",
   "voice": "A few to revisit. The goals marked revisit at the end are the ones to replay."
  },
  "interview.intro": "Now an interview round. Two quick questions, then one you answer in your own words.",
  "interview.w1": {
   "caption": "What's the difference between WHERE and HAVING?",
   "speaker": "interviewer"
  },
  "interview.w1-why": "WHERE runs before grouping, on single rows, so it can't see a count. HAVING runs after, on whole groups.",
  "interview.w2": {
   "caption": "When do <code>COUNT(*)</code> and <code>COUNT(column)</code> give different answers?",
   "voice": "When do count star and count of a column give different answers?",
   "speaker": "interviewer"
  },
  "interview.w2-why": "When the column has NULLs. COUNT star counts rows; COUNT of a column counts the values that aren't NULL.",
  "interview.right1": "Good answer.",
  "interview.right2": "That's the one they want.",
  "interview.open": {
   "caption": "Write a query for each customer's number of orders and total spend. Then tell me what could make those numbers wrong.",
   "speaker": "interviewer"
  },
  "interview.think": "Take a minute. Say your answer out loud, as if you were in the room, or jot some notes. Then reveal the model answer.",
  "interview.hint": "Press Reveal when you're ready.",
  "interview.reveal": "Here's what an interviewer listens for. Tick the points you covered.",
  "interview.rate": "Be honest. How did you do?",
  "interview.got": "Nice. That's an answer that lands.",
  "interview.partly": "Good start. It's in your flashcards now, so it'll come back.",
  "interview.missed": "That's what practice is for. It's in your flashcards, and it'll come back.",
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. Aggregates squeeze rows into numbers. GROUP BY sets the grain. And HAVING filters the groups.",
  "finish.2": "Next up: questions inside questions, with subqueries and CTEs."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "aggregate": {
   "term": "Aggregate function",
   "def": "A function that turns many rows into one value: COUNT, SUM, AVG, MIN or MAX."
  },
  "count-column": {
   "term": "COUNT(column)",
   "def": "Counts the rows where that column isn't NULL. COUNT(*) counts every row."
  },
  "group-by": {
   "term": "GROUP BY",
   "def": "Sorts rows into groups that share a value, then returns one row per group. Aggregates are computed per group."
  },
  "grain": {
   "term": "Grain",
   "def": "What one row of a result stands for: one order, one customer, one day. GROUP BY sets it."
  },
  "bare-column": {
   "term": "Bare column",
   "def": "A selected column that's neither grouped nor aggregated. PostgreSQL rejects it; SQLite quietly picks a value from some row."
  },
  "having": {
   "term": "HAVING",
   "def": "Filters groups after GROUP BY, using aggregates. WHERE filters rows before grouping."
  },
  "count-distinct": {
   "term": "COUNT(DISTINCT \u2026)",
   "def": "Counts different values once each. The usual fix when a join has repeated rows."
  }
 },
 "audio": {
  "agg.1": {
   "hash": "de12ea245103",
   "ms": 1980
  },
  "agg.2": {
   "hash": "c7f2b6434afb",
   "ms": 5040
  },
  "agg.3": {
   "hash": "18026e089fe4",
   "ms": 9108
  },
  "agg.4": {
   "hash": "4566a32cc474",
   "ms": 9396
  },
  "bare.1": {
   "hash": "2ed4a465adcc",
   "ms": 6120
  },
  "bare.2": {
   "hash": "013b1a381d5e",
   "ms": 5796
  },
  "bare.3": {
   "hash": "37d2f952f13c",
   "ms": 7272
  },
  "bare.4": {
   "hash": "96557b308532",
   "ms": 7164
  },
  "best.1": {
   "hash": "fa5e84a1a1eb",
   "ms": 6696
  },
  "best.ask": {
   "hash": "8825dca5dd74",
   "ms": 3312
  },
  "best.columns": {
   "hash": "baa83f2e2404",
   "ms": 3420
  },
  "best.done": {
   "hash": "287f33d760b2",
   "ms": 2988
  },
  "best.error": {
   "hash": "81c2cc0a2d89",
   "ms": 4176
  },
  "best.extra": {
   "hash": "7d2fde9db183",
   "ms": 2988
  },
  "best.hint": {
   "hash": "414df3223a6d",
   "ms": 4572
  },
  "best.missing": {
   "hash": "b6207e054955",
   "ms": 4752
  },
  "check.intro": {
   "hash": "e2ce00ee353d",
   "ms": 5796
  },
  "check.pass": {
   "hash": "c8130accb1a3",
   "ms": 2412
  },
  "check.q1": {
   "hash": "0e68712d2a6e",
   "ms": 9036
  },
  "check.q1-why": {
   "hash": "0055bbf804a8",
   "ms": 10044
  },
  "check.q2": {
   "hash": "1b409cfa1a98",
   "ms": 6948
  },
  "check.q2-why": {
   "hash": "63123a72f248",
   "ms": 9936
  },
  "check.q3": {
   "hash": "c7cfde87746e",
   "ms": 5796
  },
  "check.q3-why": {
   "hash": "cfc229bb2c56",
   "ms": 9216
  },
  "check.retry": {
   "hash": "17e6ed537d47",
   "ms": 5220
  },
  "check.right1": {
   "hash": "5df4176b3959",
   "ms": 864
  },
  "check.right2": {
   "hash": "e99e52b00ddc",
   "ms": 972
  },
  "check.right3": {
   "hash": "bbb1d6dfd81d",
   "ms": 864
  },
  "city.1": {
   "hash": "a20a0717c20a",
   "ms": 3564
  },
  "city.ask": {
   "hash": "5811e8c837d4",
   "ms": 3672
  },
  "city.columns": {
   "hash": "f0fa48a9eea6",
   "ms": 3024
  },
  "city.done": {
   "hash": "f8d4e0d45adb",
   "ms": 6804
  },
  "city.error": {
   "hash": "ab049c0f6f83",
   "ms": 4392
  },
  "city.extra": {
   "hash": "e5b04675d787",
   "ms": 2988
  },
  "city.hint": {
   "hash": "c4f69f7dc3ea",
   "ms": 3996
  },
  "city.missing": {
   "hash": "693932923b2b",
   "ms": 5472
  },
  "count.1": {
   "hash": "a9085c5b07a4",
   "ms": 7596
  },
  "count.ask": {
   "hash": "ffe31abebeb2",
   "ms": 3420
  },
  "count.seven": {
   "hash": "2302de6b1967",
   "ms": 3024
  },
  "count.ten": {
   "hash": "a265abfd2ac4",
   "ms": 3708
  },
  "count.three": {
   "hash": "dc3ba870bd77",
   "ms": 5112
  },
  "fanout.1": {
   "hash": "40eee9769e33",
   "ms": 6264
  },
  "fanout.2": {
   "hash": "cd71cc1dcf03",
   "ms": 6624
  },
  "fanout.3": {
   "hash": "e39e4eb367ec",
   "ms": 3816
  },
  "fanout.4": {
   "hash": "cb57414f21d9",
   "ms": 5472
  },
  "fanout.5": {
   "hash": "8ab6a22d1fcf",
   "ms": 4320
  },
  "finish.1": {
   "hash": "ccfea034d877",
   "ms": 8208
  },
  "finish.2": {
   "hash": "f30faff2d67c",
   "ms": 5760
  },
  "goals.1": {
   "hash": "c13cb91cc4da",
   "ms": 8748
  },
  "goals.2": {
   "hash": "8e77a4291ec4",
   "ms": 7920
  },
  "goals.3": {
   "hash": "00df4f82cb47",
   "ms": 5796
  },
  "goals.intro": {
   "hash": "7105eda85e67",
   "ms": 2700
  },
  "group.1": {
   "hash": "dea412bd7406",
   "ms": 4320
  },
  "group.2": {
   "hash": "d72ebbfcf4c2",
   "ms": 3996
  },
  "group.3": {
   "hash": "9ebea8a60a43",
   "ms": 5220
  },
  "group.4": {
   "hash": "0cede18d138d",
   "ms": 4067
  },
  "group.5": {
   "hash": "ecf3167fd4fb",
   "ms": 8064
  },
  "having.1": {
   "hash": "57741be5ca99",
   "ms": 4392
  },
  "having.2": {
   "hash": "cfe744452778",
   "ms": 3996
  },
  "having.3": {
   "hash": "b47b15ee8f1d",
   "ms": 6660
  },
  "having.4": {
   "hash": "07d117313418",
   "ms": 5724
  },
  "having.5": {
   "hash": "10b65eec46ab",
   "ms": 9396
  },
  "having.ask": {
   "hash": "71d5bc8ebcca",
   "ms": 1656
  },
  "having.no": {
   "hash": "05e2e76ef06d",
   "ms": 3492
  },
  "having.yes": {
   "hash": "b233000137ed",
   "ms": 3600
  },
  "hook.1": {
   "hash": "f499ef6ffb7f",
   "ms": 5400
  },
  "hook.2": {
   "hash": "49467dedf345",
   "ms": 4284
  },
  "hook.3": {
   "hash": "b7229b9938df",
   "ms": 5796
  },
  "interview.got": {
   "hash": "aabb8fade94b",
   "ms": 2916
  },
  "interview.hint": {
   "hash": "ec946fd698df",
   "ms": 1476
  },
  "interview.intro": {
   "hash": "a64cb106fc49",
   "ms": 5580
  },
  "interview.missed": {
   "hash": "cf7b5457ae7f",
   "ms": 4824
  },
  "interview.open": {
   "hash": "9ecd6208ea31",
   "ms": 7092
  },
  "interview.partly": {
   "hash": "4cd133f7622f",
   "ms": 3816
  },
  "interview.rate": {
   "hash": "33112c8f4502",
   "ms": 2304
  },
  "interview.reveal": {
   "hash": "2ab0cad8958c",
   "ms": 3600
  },
  "interview.right1": {
   "hash": "4defc0b4ea6a",
   "ms": 1044
  },
  "interview.right2": {
   "hash": "15b09ac0e501",
   "ms": 1656
  },
  "interview.think": {
   "hash": "04527f670030",
   "ms": 7092
  },
  "interview.w1": {
   "hash": "b3919685bfed",
   "ms": 3564
  },
  "interview.w1-why": {
   "hash": "cd2060400b9f",
   "ms": 7776
  },
  "interview.w2": {
   "hash": "8e242a0149c6",
   "ms": 4392
  },
  "interview.w2-why": {
   "hash": "433abe96da91",
   "ms": 7164
  },
  "keywords.1": {
   "hash": "52c9899fd888",
   "ms": 2916
  },
  "keywords.ask": {
   "hash": "9e5d200f6173",
   "ms": 4140
  },
  "keywords.done": {
   "hash": "b410b19a541a",
   "ms": 4536
  },
  "keywords.hint": {
   "hash": "520960a4916d",
   "ms": 3060
  },
  "recap.1": {
   "hash": "7c686b6254fe",
   "ms": 9432
  },
  "recap.2": {
   "hash": "a8116fb36f2a",
   "ms": 8280
  },
  "recap.3": {
   "hash": "e5951b47c51d",
   "ms": 8784
  },
  "recap.intro": {
   "hash": "f29481f34c13",
   "ms": 2340
  }
 }
});
