// Generated by tools/voice.py from group.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("group", {
 "lines": {
  "hook.1": "So far, every query returned rows. Now the bakery wants numbers.",
  "hook.2": "How many orders came in? What sells best? Who are the regulars?",
  "hook.3": "Each answer squeezes many rows into a few. That's what this lesson is about.",
  "agg.1": "Here are all sixteen orders.",
  "agg.2": "COUNT star turns them into one row, with one number: sixteen.",
  "agg.3": "COUNT, SUM, AVG, MIN and MAX each turn many rows into one value. They're called <k id=\"aggregate\">aggregate functions</k>.",
  "agg.4": {
   "caption": "On the eight products: the prices add up to <b>36.10</b>, and average <b>4.51</b>. Cheapest <b>2.80</b>, dearest <b>6.50</b>.",
   "voice": "On the eight products: the prices add up to thirty-six ten, and average four fifty-one. The cheapest is two eighty, the dearest six fifty."
  },
  "count.ask": "Ten customers. How many does COUNT of phone return?",
  "count.ten": "It's seven. Three customers have no phone.",
  "count.seven": "Seven. You remembered the missing phones.",
  "count.three": "Three is how many are missing. COUNT of phone returns seven.",
  "count.1": "<k id=\"count-column\">COUNT of a column</k> skips NULLs. COUNT star counts every row. Interviewers love that difference.",
  "group.1": "Next question: how many orders are paid, pending, or refunded?",
  "group.2": "<b>GROUP BY status</b> sorts the rows into one pile per status.",
  "group.3": "Then each pile collapses into a single row, and COUNT runs once per pile.",
  "group.4": "Three statuses, three rows. That's <k id=\"group-by\">GROUP BY</k>.",
  "group.5": "The result has a new <k>grain</k>: one row per status, not one per order. Always know the grain of your result.",
  "city.1": "Your turn. How many customers live in each city?",
  "city.ask": "Write the query: the city, and a count.",
  "city.hint": {
   "caption": "<b>SELECT city, COUNT(*)</b> from customers, then <b>GROUP BY city</b>.",
   "voice": "Select the city and count star from customers, then group by city."
  },
  "city.error": "The database couldn't run that. The message under the editor says why.",
  "city.extra": "Too many rows. Is there a GROUP BY?",
  "city.missing": "Some cities are missing, or the counts are off. Group by city and count every row.",
  "city.columns": "Just two columns: the city, and the count.",
  "city.done": "Seven rows. Notice NULL: Raj has no city, and missing values form a group of their own.",
  "bare.1": {
   "caption": "Here's a mistake that's easy to make. Group orders by customer, but also select <b>ordered_at</b>.",
   "voice": "Here's a mistake that's easy to make. Group orders by customer, but also select the order date."
  },
  "bare.2": "Maya has four orders, with four dates. Her group gets one row. Which date goes in it?",
  "bare.3": "PostgreSQL refuses to guess, and rejects the query. SQLite quietly picks one. That's a <k id=\"bare-column\">bare column</k>.",
  "bare.4": "The rule: every selected column is either grouped, or wrapped in an aggregate. MAX of ordered at gives Maya's latest order.",
  "having.1": "The bakery wants its regulars: customers with at least two orders.",
  "having.2": "WHERE can't do it. It runs before grouping, and there's no count yet.",
  "having.3": "<k id=\"having\">HAVING</k> filters groups, after they're counted. Maya, Omar, Ana and Yuki make the cut.",
  "having.4": "Now count only paid orders. WHERE drops the unpaid rows first, then the groups are counted.",
  "having.ask": "Is Omar still a regular?",
  "having.yes": "Look again. Omar's second order is still pending.",
  "having.no": "Right. One of Omar's two orders is pending.",
  "having.5": "WHERE filters rows before grouping. HAVING filters groups after. The full order is FROM, WHERE, GROUP BY, HAVING, SELECT.",
  "best.1": "Your turn. The bakery wants its best sellers: products that sold at least five units in total.",
  "best.ask": "Group by product name, and keep the big groups.",
  "best.hint": {
   "caption": "Sum the <b>quantity</b> per product, then <b>HAVING SUM(i.quantity) &gt;= 5</b>.",
   "voice": "Sum the quantity per product, then keep the groups having a sum of at least five."
  },
  "best.error": "The database couldn't run that. Read the message, then try again.",
  "best.extra": "Too many products. Filter the groups with HAVING.",
  "best.missing": "Some best sellers are missing. Are you summing the quantity, not counting rows?",
  "best.columns": "Two columns: the product's name, and its total.",
  "best.done": "Four products. Croissants lead with ten.",
  "fanout.1": "Last trap, and it's one you've seen before. Count each customer's orders, but also join their items.",
  "fanout.2": "Maya shows seven orders. She has four. The join repeated each order once per item.",
  "fanout.3": "COUNT star counts rows, and fan-out made extra rows.",
  "fanout.4": "<k id=\"count-distinct\">COUNT DISTINCT</k> on the order ID counts each order once. Maya's back to four.",
  "fanout.5": "When a joined total looks too big, check the grain before you trust it.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "A table has 10 rows, and 3 of them have a NULL phone. What do <code>COUNT(*)</code> and <code>COUNT(phone)</code> return?",
   "voice": "A table has ten rows, and three have a null phone. What do count star and count of phone return?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "COUNT star counts rows. COUNT of a column skips NULLs.",
  "quiz.q2": {
   "caption": "You need customers with more than 5 orders. Where does the condition go?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "The count only exists after grouping, so it's a HAVING condition. WHERE runs before any group exists.",
  "quiz.q3": {
   "caption": "<code>SELECT customer_id, ordered_at, COUNT(*) FROM orders GROUP BY customer_id</code>. What does PostgreSQL do?",
   "voice": "Select customer ID, the order date, and count star, from orders, grouped by customer ID. What does Postgres do?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "ordered_at is a bare column: neither grouped nor aggregated. Postgres rejects it. Wrap it, like MAX of ordered at.",
  "quiz.q4": {
   "caption": "Orders per customer looks too high after joining order_items. The fix?",
   "voice": "Orders per customer looks too high after joining order items. What's the fix?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "The join repeats each order per item. Count distinct order IDs, or count before joining.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. Aggregates squeeze rows into numbers. GROUP BY sets the grain. And HAVING filters the groups.",
  "finish.2": "Next up: how a database actually reads those rows from disk."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "aggregate": {
   "term": "Aggregate function",
   "def": "A function that turns many rows into one value: COUNT, SUM, AVG, MIN or MAX."
  },
  "count-column": {
   "term": "COUNT(column)",
   "def": "Counts the rows where that column isn't NULL. COUNT(*) counts every row."
  },
  "group-by": {
   "term": "GROUP BY",
   "def": "Sorts rows into groups that share a value, then returns one row per group. Aggregates are computed per group."
  },
  "grain": {
   "term": "Grain",
   "def": "What one row of a result stands for: one order, one customer, one day. GROUP BY sets it."
  },
  "bare-column": {
   "term": "Bare column",
   "def": "A selected column that's neither grouped nor aggregated. PostgreSQL rejects it; SQLite quietly picks a value from some row."
  },
  "having": {
   "term": "HAVING",
   "def": "Filters groups after GROUP BY, using aggregates. WHERE filters rows before grouping."
  },
  "count-distinct": {
   "term": "COUNT(DISTINCT \u2026)",
   "def": "Counts different values once each. The usual fix when a join has repeated rows."
  }
 },
 "audio": {
  "agg.1": {
   "hash": "8908dcf74dad",
   "ms": 1621
  },
  "agg.2": {
   "hash": "ad4c2cc7fb7c",
   "ms": 3733
  },
  "agg.3": {
   "hash": "0d89d3512b46",
   "ms": 7573
  },
  "agg.4": {
   "hash": "3dc6f3f38591",
   "ms": 8661
  },
  "bare.1": {
   "hash": "4efc409f77d7",
   "ms": 5803
  },
  "bare.2": {
   "hash": "cda7d1a3cff1",
   "ms": 5056
  },
  "bare.3": {
   "hash": "81ef26637877",
   "ms": 6613
  },
  "bare.4": {
   "hash": "e330f28df391",
   "ms": 8064
  },
  "best.1": {
   "hash": "9b876d9a12bf",
   "ms": 5525
  },
  "best.ask": {
   "hash": "1d9b68881e8c",
   "ms": 2581
  },
  "best.columns": {
   "hash": "d7a9b0bc54fa",
   "ms": 2688
  },
  "best.done": {
   "hash": "1ca6f60868eb",
   "ms": 2389
  },
  "best.error": {
   "hash": "321aab9fd8e5",
   "ms": 3520
  },
  "best.extra": {
   "hash": "03ce7b49a08b",
   "ms": 2560
  },
  "best.hint": {
   "hash": "34250d21ee7e",
   "ms": 4245
  },
  "best.missing": {
   "hash": "6e4e6d2625a1",
   "ms": 4459
  },
  "city.1": {
   "hash": "2d08a1bbd953",
   "ms": 2603
  },
  "city.ask": {
   "hash": "a8a6e8d45d72",
   "ms": 2176
  },
  "city.columns": {
   "hash": "f9403911e4d0",
   "ms": 2389
  },
  "city.done": {
   "hash": "9f727eb4bee9",
   "ms": 5739
  },
  "city.error": {
   "hash": "6a6131c294e4",
   "ms": 3840
  },
  "city.extra": {
   "hash": "2fd798e750c4",
   "ms": 2005
  },
  "city.hint": {
   "hash": "f8d7d2de8479",
   "ms": 3925
  },
  "city.missing": {
   "hash": "851f64712347",
   "ms": 4843
  },
  "count.1": {
   "hash": "f44e1efd099d",
   "ms": 5504
  },
  "count.ask": {
   "hash": "bf2535db61b7",
   "ms": 2944
  },
  "count.seven": {
   "hash": "45e71dbfff8f",
   "ms": 2133
  },
  "count.ten": {
   "hash": "f70fad571172",
   "ms": 2496
  },
  "count.three": {
   "hash": "c0c409a3004f",
   "ms": 3307
  },
  "fanout.1": {
   "hash": "1264fb32fe38",
   "ms": 6016
  },
  "fanout.2": {
   "hash": "8cf290cb815a",
   "ms": 5312
  },
  "fanout.3": {
   "hash": "7082f86eb32e",
   "ms": 3413
  },
  "fanout.4": {
   "hash": "c13afc0b02a3",
   "ms": 4736
  },
  "fanout.5": {
   "hash": "06eb01b918a7",
   "ms": 3904
  },
  "finish.1": {
   "hash": "7a423b9407d8",
   "ms": 6848
  },
  "finish.2": {
   "hash": "555b915c7e66",
   "ms": 3712
  },
  "group.1": {
   "hash": "31eff017045b",
   "ms": 3883
  },
  "group.2": {
   "hash": "f9f84f2cec9a",
   "ms": 3541
  },
  "group.3": {
   "hash": "1f06d88bb4be",
   "ms": 4373
  },
  "group.4": {
   "hash": "cd0ae403c98c",
   "ms": 2667
  },
  "group.5": {
   "hash": "eace98fdfce4",
   "ms": 6443
  },
  "having.1": {
   "hash": "c9d37b39dc6e",
   "ms": 3733
  },
  "having.2": {
   "hash": "25515561141d",
   "ms": 3669
  },
  "having.3": {
   "hash": "e3c337bee389",
   "ms": 5312
  },
  "having.4": {
   "hash": "78661a9a4fa5",
   "ms": 5419
  },
  "having.5": {
   "hash": "2ee0a67a20ef",
   "ms": 7275
  },
  "having.ask": {
   "hash": "e07e05483ff6",
   "ms": 1536
  },
  "having.no": {
   "hash": "748ff0429160",
   "ms": 2432
  },
  "having.yes": {
   "hash": "715f0d1ad236",
   "ms": 2795
  },
  "hook.1": {
   "hash": "6a8ae3e50686",
   "ms": 4309
  },
  "hook.2": {
   "hash": "ae3f625ffa38",
   "ms": 3499
  },
  "hook.3": {
   "hash": "e495f8b7b294",
   "ms": 4416
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "quiz.intro": {
   "hash": "f0a37944ed86",
   "ms": 1365
  },
  "quiz.pass": {
   "hash": "fd15ec4d6ef7",
   "ms": 1579
  },
  "quiz.q1": {
   "hash": "8ecf7bb0345a",
   "ms": 6336
  },
  "quiz.q1-why": {
   "hash": "6410455e39af",
   "ms": 3179
  },
  "quiz.q2": {
   "hash": "b3391c400feb",
   "ms": 4971
  },
  "quiz.q2-why": {
   "hash": "b07411412ac3",
   "ms": 6187
  },
  "quiz.q3": {
   "hash": "7f74656f3965",
   "ms": 8021
  },
  "quiz.q3-why": {
   "hash": "5ba4c057e7ef",
   "ms": 7616
  },
  "quiz.q4": {
   "hash": "d98f2da9d72f",
   "ms": 5248
  },
  "quiz.q4-why": {
   "hash": "deaf41ca0bde",
   "ms": 5867
  },
  "quiz.retry": {
   "hash": "bae6100ef83b",
   "ms": 3349
  },
  "quiz.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "quiz.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "quiz.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  }
 }
});
