// Generated by tools/voice.py from joins.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("joins", {
 "lines": {
  "hook.1": "Maya's orders don't store her name. They store her customer ID, a key that points into the customers table.",
  "hook.2": "Remember following those pointers by hand? In SQL, that's one clause: JOIN.",
  "hook.3": "But every kind of join quietly drops some rows, or repeats them. Knowing which is what interviewers check.",
  "inner.1": "Customers on the left, orders on the right. Each order carries a customer ID.",
  "inner.2": {
   "caption": "<code>JOIN customers c ON c.id = o.customer_id</code> matches each order to the customer it points at.",
   "voice": "Join customers, on the customer's ID equals the order's customer ID. That matches each order to the customer it points at."
  },
  "inner.3": "The part after ON is the <k id=\"join-condition\">join condition</k>. It says which rows belong together.",
  "inner.4": "Some rows have no partner. Lena and Theo never ordered, and two walk-in orders have no customer at all.",
  "inner.ask": "Sixteen orders go in. How many rows come out?",
  "inner.sixteen": "Close, but the two walk-ins have nobody to match. Fourteen.",
  "inner.fourteen": "Fourteen. You were watching the walk-ins.",
  "inner.ten": "More than that. Fourteen orders have a customer, so fourteen rows come back.",
  "inner.5": "An <k id=\"inner-join\">inner join</k> keeps only matched pairs. Anything without a partner, on either side, is dropped.",
  "inner.6": "Plain JOIN means inner join. It's the default.",
  "left.1": "Now the bakery wants every customer, with their orders if they have any.",
  "left.2": "Swap JOIN for <b>LEFT JOIN</b>. Every row from the left table stays.",
  "left.3": "Lena and Theo stay too. Where an order should be, the columns are filled with NULL.",
  "left.4": "That's a <k id=\"left-join\">left join</k>: all of the left table, plus its matches from the right, or NULLs.",
  "never.1": "The bakery wants to send a welcome offer to customers who've never ordered.",
  "never.2": "Here's the trick. After a left join, those customers are the rows where the order side is NULL.",
  "never.ask": "Finish the WHERE clause, then run it.",
  "never.hint": {
   "caption": "Keep the rows where <b>o.id IS NULL</b>.",
   "voice": "Keep the rows where the order's ID is null."
  },
  "never.error": "The database couldn't run that. The message under the editor says why.",
  "never.extra": "Too many rows. Keep only the customers whose order side is NULL.",
  "never.missing": "Someone's missing. Test the order's ID with IS NULL, not with equals.",
  "never.columns": "Just the customer's name, please.",
  "never.done": "Lena and Theo. Finding rows with no match is called an <k id=\"anti-join\">anti-join</k>.",
  "trap.1": "Next request: every customer, with their paid orders. Customers with none should still show up.",
  "trap.2": "A first try: a left join, then keep the paid orders in WHERE.",
  "trap.ask": "Will Lena still be in the result?",
  "trap.yes": "That's the intent. Let's see.",
  "trap.no": "Good instinct. Let's see why.",
  "trap.3": {
   "caption": "Lena, Theo and Raj are gone. WHERE runs after the join, and a NULL status isn't <b>'paid'</b>.",
   "voice": "Lena, Theo and Raj are gone. WHERE runs after the join, and a null status isn't paid, so their rows fail."
  },
  "trap.4": "A filter on the right-hand table in WHERE quietly turns a left join back into an inner join.",
  "trap.5": "Move the test into ON. Now it only decides which orders match, and every customer stays.",
  "trap.6": "Rule of thumb: in a left join, filters on the right-hand table belong in ON.",
  "full.1": "A <k id=\"right-join\">right join</k> is the mirror image: it keeps every row of the right table. Most teams swap the tables and write LEFT.",
  "full.2": "A <k id=\"full-outer-join\">full outer join</k> keeps both sides whole: customers with no orders, and orders with no customer.",
  "full.3": "Eighteen rows. It's handy for reconciling two lists, to see what's missing on each side.",
  "fanout.1": "Joins can also add rows. Each order has one or more items.",
  "fanout.2": "Join orders to their items, and sixteen orders become twenty-two rows. Order one appears twice, once per item.",
  "fanout.3": "That's <k id=\"fan-out\">fan-out</k>. Add up anything from the orders side now, and some orders count twice.",
  "fanout.4": "Forget the join condition entirely, and every customer pairs with every order. Ten times sixteen: a hundred and sixty rows.",
  "fanout.5": "That's a <k id=\"cross-join\">cross join</k>. Occasionally useful, usually a bug.",
  "fanout.6": "Before trusting a joined total, ask: how many rows per order does this join make?",
  "walk.1": "Last one. List every order's ID with the customer's name, and keep the walk-in orders.",
  "walk.ask": "Write the join. Start from the orders.",
  "walk.hint": {
   "caption": "Start <b>FROM orders</b>, then <b>LEFT JOIN customers</b>.",
   "voice": "Start from orders, then left join customers."
  },
  "walk.error": "The database couldn't run that. Read the message, then try again.",
  "walk.extra": "Too many rows. Check the ON condition.",
  "walk.missing": "Some orders are missing. The walk-ins need a left join that starts from orders.",
  "walk.columns": "Just the order's ID and the customer's name.",
  "walk.done": "Sixteen orders, two with no name. Which table comes first decides what a left join keeps.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "customers has 10 rows, orders has 16, and 2 orders have no customer. How many rows does an inner join on the customer ID return?",
   "voice": "Customers has ten rows. Orders has sixteen, and two have no customer. How many rows does an inner join on the customer ID return?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "Each order with a customer matches exactly one row, so fourteen. The walk-ins, and customers who never ordered, are dropped.",
  "quiz.q2": {
   "caption": "Which query finds customers who have never ordered?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "A left join keeps every customer. Those with no order have NULL on the order side, so test for that.",
  "quiz.q3": {
   "caption": "<code>LEFT JOIN orders o ON \u2026 WHERE o.status = 'paid'</code>. What happens to customers with no paid orders?",
   "voice": "A left join to orders, then where the status is paid. What happens to customers with no paid orders?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "WHERE runs after the join, and NULL isn't paid, so those rows fail. Put the condition in ON.",
  "quiz.q4": {
   "caption": "A report's revenue doubled right after someone added a join. What's the likely cause?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "The new join matches several rows per order, so each order is repeated, and added up, more than once.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. Inner joins keep only matches. Outer joins keep a side whole, with NULLs. And joins can multiply rows.",
  "finish.2": "Next up: turning rows into numbers, with GROUP BY."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "join-condition": {
   "term": "Join condition",
   "def": "The test after ON that says which rows belong together, like c.id = o.customer_id."
  },
  "inner-join": {
   "term": "Inner join",
   "def": "Keeps only rows that have a match on both sides. Anything without a partner, on either side, is dropped. Plain JOIN means inner join."
  },
  "left-join": {
   "term": "Left join",
   "def": "Keeps every row of the left table. Where there's no match on the right, the right side's columns are NULL."
  },
  "anti-join": {
   "term": "Anti-join",
   "def": "Finds rows with no match in another table, for example with a left join and a test for NULL on the right side."
  },
  "right-join": {
   "term": "Right join",
   "def": "The mirror of a left join: keeps every row of the right table. Usually written as a left join with the tables swapped."
  },
  "full-outer-join": {
   "term": "Full outer join",
   "def": "Keeps every row from both tables, matched where possible, with NULLs where a side has no partner."
  },
  "fan-out": {
   "term": "Fan-out",
   "def": "A join that matches several rows per row, so the first table's rows repeat. Totals from that side get counted more than once."
  },
  "cross-join": {
   "term": "Cross join",
   "def": "Every row of one table paired with every row of the other: rows times rows. What you get when a join has no condition."
  }
 },
 "audio": {
  "fanout.1": {
   "hash": "4a57bff4221b",
   "ms": 3947
  },
  "fanout.2": {
   "hash": "9c579b05cfef",
   "ms": 7125
  },
  "fanout.3": {
   "hash": "ab7b3608629d",
   "ms": 4949
  },
  "fanout.4": {
   "hash": "3a55bd0caeaa",
   "ms": 8107
  },
  "fanout.5": {
   "hash": "1060b02c2b12",
   "ms": 3477
  },
  "fanout.6": {
   "hash": "bd99143d711a",
   "ms": 4736
  },
  "finish.1": {
   "hash": "ca9ba3472457",
   "ms": 8043
  },
  "finish.2": {
   "hash": "ca19a5931ae9",
   "ms": 3029
  },
  "full.1": {
   "hash": "e851524fb06a",
   "ms": 7360
  },
  "full.2": {
   "hash": "657de52ce85c",
   "ms": 5995
  },
  "full.3": {
   "hash": "fb6dab91f089",
   "ms": 5184
  },
  "hook.1": {
   "hash": "163897e19dc3",
   "ms": 6507
  },
  "hook.2": {
   "hash": "b6685043bdc5",
   "ms": 4907
  },
  "hook.3": {
   "hash": "ed636b6e56cc",
   "ms": 6208
  },
  "inner.1": {
   "hash": "3df708393ed2",
   "ms": 4843
  },
  "inner.2": {
   "hash": "32b5041f7db3",
   "ms": 8107
  },
  "inner.3": {
   "hash": "33d0ba618e59",
   "ms": 4672
  },
  "inner.4": {
   "hash": "68947d62629e",
   "ms": 6549
  },
  "inner.5": {
   "hash": "72d18c304ba3",
   "ms": 5632
  },
  "inner.6": {
   "hash": "6af232243c65",
   "ms": 2795
  },
  "inner.ask": {
   "hash": "299bbbd9034c",
   "ms": 2752
  },
  "inner.fourteen": {
   "hash": "1f7bb5e9d4c7",
   "ms": 2155
  },
  "inner.sixteen": {
   "hash": "77f24da1dbb8",
   "ms": 3456
  },
  "inner.ten": {
   "hash": "faad5f5296d4",
   "ms": 4544
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "left.1": {
   "hash": "066fbcba544c",
   "ms": 4053
  },
  "left.2": {
   "hash": "eef8a1ce6b5e",
   "ms": 4032
  },
  "left.3": {
   "hash": "4beb659ae376",
   "ms": 4715
  },
  "left.4": {
   "hash": "1260355267a5",
   "ms": 4672
  },
  "never.1": {
   "hash": "219d22340638",
   "ms": 4139
  },
  "never.2": {
   "hash": "4b474711f9f0",
   "ms": 5376
  },
  "never.ask": {
   "hash": "3d130ddd9e9e",
   "ms": 1749
  },
  "never.columns": {
   "hash": "9992708d9a68",
   "ms": 1813
  },
  "never.done": {
   "hash": "7cbbbd729876",
   "ms": 4373
  },
  "never.error": {
   "hash": "6a6131c294e4",
   "ms": 3840
  },
  "never.extra": {
   "hash": "c9a0cb5c0434",
   "ms": 3733
  },
  "never.hint": {
   "hash": "e1da582d9df0",
   "ms": 2411
  },
  "never.missing": {
   "hash": "324af81a438c",
   "ms": 4181
  },
  "quiz.intro": {
   "hash": "f0a37944ed86",
   "ms": 1365
  },
  "quiz.pass": {
   "hash": "fd15ec4d6ef7",
   "ms": 1579
  },
  "quiz.q1": {
   "hash": "7b6f0822b8cd",
   "ms": 9259
  },
  "quiz.q1-why": {
   "hash": "72fa505abc0a",
   "ms": 7851
  },
  "quiz.q2": {
   "hash": "338cfc69d601",
   "ms": 3371
  },
  "quiz.q2-why": {
   "hash": "0356ade4357c",
   "ms": 6101
  },
  "quiz.q3": {
   "hash": "2896a9bc90c8",
   "ms": 6891
  },
  "quiz.q3-why": {
   "hash": "dc44990a61cd",
   "ms": 5440
  },
  "quiz.q4": {
   "hash": "9733ea5e0e1d",
   "ms": 5803
  },
  "quiz.q4-why": {
   "hash": "baa4488c76a4",
   "ms": 6016
  },
  "quiz.retry": {
   "hash": "bae6100ef83b",
   "ms": 3349
  },
  "quiz.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "quiz.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "quiz.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "trap.1": {
   "hash": "c802d8a76508",
   "ms": 5611
  },
  "trap.2": {
   "hash": "b173a46fa7b6",
   "ms": 3712
  },
  "trap.3": {
   "hash": "d3651d2f5772",
   "ms": 6827
  },
  "trap.4": {
   "hash": "47ca0ffab8b3",
   "ms": 5355
  },
  "trap.5": {
   "hash": "0a5ece650057",
   "ms": 5504
  },
  "trap.6": {
   "hash": "c2c2eb5682dd",
   "ms": 4736
  },
  "trap.ask": {
   "hash": "4de5287b16c0",
   "ms": 1771
  },
  "trap.no": {
   "hash": "2db13c390b28",
   "ms": 1771
  },
  "trap.yes": {
   "hash": "390b46ee620a",
   "ms": 1728
  },
  "walk.1": {
   "hash": "dd4d4dfb274f",
   "ms": 5205
  },
  "walk.ask": {
   "hash": "373ee947750a",
   "ms": 2197
  },
  "walk.columns": {
   "hash": "d67dbcb45223",
   "ms": 2688
  },
  "walk.done": {
   "hash": "d9c038e418fa",
   "ms": 5696
  },
  "walk.error": {
   "hash": "321aab9fd8e5",
   "ms": 3520
  },
  "walk.extra": {
   "hash": "58fe95c47a0b",
   "ms": 2197
  },
  "walk.hint": {
   "hash": "378192044383",
   "ms": 2645
  },
  "walk.missing": {
   "hash": "eaeb6dabd7b6",
   "ms": 4480
  }
 }
});
