// Generated by tools/voice.py from latency.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("latency", {
 "lines": {
  "hook.1": "Some customers say the bakery's website feels slow. But the dashboard says the average page takes a hundred and seventy milliseconds.",
  "hook.2": "Both are true. This lesson is about measuring speed honestly, the way interviewers expect you to.",
  "terms.1": "Two different words first. Each dot is one request to the site.",
  "terms.2": "How long one request takes, start to finish, is its <k>latency</k>.",
  "terms.3": "How many requests finish each second is <k>throughput</k>.",
  "terms.4": "They're not the same. A busy site can finish lots of requests per second, while each one still waits a long time.",
  "dist.1": "Here are two hundred requests to the bakery's site, grouped by how long they took.",
  "dist.2": "Most are quick, under about a hundred and twenty milliseconds. But a few take seconds. That long stretch on the right is the tail.",
  "dist.3": {
   "caption": "The average is <b>170 ms</b>. Hardly any request actually takes that long.",
   "voice": "The average is a hundred and seventy milliseconds. Hardly any request actually takes that long."
  },
  "dist.ask": "Half the requests are faster than what?",
  "dist.mean": "That's the average. A handful of very slow requests drags it up. The middle value is lower.",
  "dist.median": "Right. The middle request: a hundred and one milliseconds.",
  "dist.fifty": "Lower than most. The middle request takes a hundred and one milliseconds.",
  "dist.4": "The middle value is the <k>median</k>, or p50. It's a <k>percentile</k>: half the requests are at or below it.",
  "tail.1": {
   "caption": "Now the slow end. The 95th percentile, <b>p95</b>, is <b>327 ms</b>.",
   "voice": "Now the slow end. The ninety-fifth percentile, p95, is three hundred and twenty-seven milliseconds."
  },
  "tail.2": {
   "caption": "And <b>p99</b> is over <b>2 seconds</b>. One request in a hundred waits more than two seconds.",
   "voice": "And p99 is over two seconds. One request in a hundred waits more than two seconds."
  },
  "tail.3": "That's <k id=\"tail-latency\">tail latency</k>. And the slow requests are often the valuable ones: the biggest baskets, the loyal customers with the most history.",
  "tail.4": "So report percentiles, not the average: p50 for the typical user, p95 and p99 for the unlucky ones.",
  "p99.1": {
   "caption": "Your turn. The table <b>requests</b> has one row per request, with its time in <b>ms</b>. Find the p99.",
   "voice": "Your turn. The table requests has one row per request, with its time in milliseconds. Find the p99."
  },
  "p99.ask": "There are two hundred rows, so p99 is the hundred and ninety-eighth fastest. Sort, skip, and take one.",
  "p99.hint": {
   "caption": "<b>ORDER BY ms LIMIT 1 OFFSET 197</b>: skip 197 rows, take the 198th.",
   "voice": "Order by the time, limit one, offset a hundred and ninety-seven. Skip a hundred and ninety-seven rows, and take the next."
  },
  "p99.error": "The database couldn't run that. Read the message under the editor.",
  "p99.extra": "Just one value, please: the p99.",
  "p99.missing": "Not quite. Sort ascending, skip a hundred and ninety-seven, and take one.",
  "p99.columns": "One column: the time.",
  "p99.done": "Two thousand and ninety-three milliseconds. That's the number the unlucky customers feel.",
  "amp.1": "It gets worse. To show the checkout page, the site calls several services: prices, stock, the basket, loyalty points.",
  "amp.2": "The page can't finish until the slowest call does. So if any one call hits its slow tail, the whole page is slow.",
  "amp.ask": "Each call is slow one time in a hundred. The page makes ten calls. How often is the page slow?",
  "amp.one": "It's worse than that. Ten chances to be unlucky: about one page in ten.",
  "amp.ten": "Right. About one in ten. Nearly ten percent.",
  "amp.half": "Not quite that bad yet. About one page in ten, for ten calls.",
  "amp.3": "With a hundred calls, nearly two pages in three are slow. That's <k id=\"tail-amplification\">tail amplification</k>. It's why big systems obsess over p99.",
  "queue.1": "One more source of slowness: waiting in line. A request can't start until the server is free.",
  "queue.2": "At half busy, requests barely wait. At eighty percent, waits start to build.",
  "queue.3": "At ninety-five percent busy, response time is four times what it was at eighty. The last bit of capacity is the most expensive.",
  "queue.4": "That wait before any work starts is <k id=\"queueing-delay\">queueing delay</k>. Throughput barely rises, while latency shoots up.",
  "checkout.1": "Your turn again. The team promises: ninety-five percent of checkouts in under one second. Check it.",
  "checkout.ask": "Find the p95 for the checkout endpoint. There are fifty checkout requests, so it's the forty-eighth fastest.",
  "checkout.hint": {
   "caption": "<b>WHERE endpoint = '/checkout' ORDER BY ms LIMIT 1 OFFSET 47</b>",
   "voice": "Where the endpoint is checkout, order by the time, limit one, offset forty-seven."
  },
  "checkout.error": "The database couldn't run that. Check the quotes around slash checkout.",
  "checkout.extra": "Just one value, please.",
  "checkout.missing": "Not quite. Only checkout requests, sorted, skip forty-seven, take one.",
  "checkout.columns": "One column: the time.",
  "checkout.done": "Nine hundred and eighty-four milliseconds: the promise holds, just. A promise stated as a percentile is an <k>SLO</k>.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "Average response time is 170 ms, but the median is 101 ms. What does that tell you?",
   "voice": "Average response time is a hundred and seventy milliseconds, but the median is a hundred and one. What does that tell you?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "A few very slow requests pull the average up. The distribution has a long tail, so report percentiles.",
  "quiz.q2": {
   "caption": "What does \"p99 is 2 seconds\" mean?",
   "voice": "What does p99 is two seconds mean?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "Ninety-nine in a hundred requests take two seconds or less. One in a hundred takes longer.",
  "quiz.q3": {
   "caption": "A page calls 10 services in parallel, each slow 1% of the time. Roughly how often is the page slow?",
   "voice": "A page calls ten services in parallel, each slow one percent of the time. Roughly how often is the page slow?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "It waits for the slowest call: one minus point nine nine to the tenth power, about ten percent.",
  "quiz.q4": {
   "caption": "A server goes from 80% to 95% busy. What happens to response time?",
   "voice": "A server goes from eighty percent to ninety-five percent busy. What happens to response time?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "Queues grow steeply near full capacity. In the simple queueing model it goes from five times the service time to twenty: four times worse.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson, and level one. Measure percentiles, not averages, watch the tail as calls fan out, and leave headroom before the queue explodes.",
  "finish.2": "Next up: how a database actually reads those rows from disk."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "latency": {
   "term": "Latency",
   "def": "How long one request takes, from start to finish, usually in milliseconds. Response time as the user sees it includes any waiting in queues."
  },
  "throughput": {
   "term": "Throughput",
   "def": "How much work gets done per unit of time, like requests per second. A system can have high throughput and still be slow for each request."
  },
  "percentile": {
   "term": "Percentile",
   "def": "The value below which that share of measurements falls. p95 is 327 milliseconds when 95 in 100 requests take 327 or less."
  },
  "median": {
   "term": "Median (p50)",
   "def": "The middle value: half the requests are faster, half slower. Unlike the mean, a few very slow requests can't drag it up."
  },
  "tail-latency": {
   "term": "Tail latency",
   "def": "The slowest requests, measured by high percentiles like p99 or p99.9. Often the users who matter most: the biggest baskets, the most data."
  },
  "tail-amplification": {
   "term": "Tail amplification",
   "def": "A request that waits for many backend calls is as slow as the slowest one, so rare slow calls become common slow pages."
  },
  "queueing-delay": {
   "term": "Queueing delay",
   "def": "Time a request waits before any work starts. It grows steeply as a server nears 100 percent busy."
  },
  "slo": {
   "term": "SLO",
   "def": "Service level objective: a target stated as a percentile, like 95 percent of checkouts in under one second."
  }
 },
 "audio": {
  "amp.1": {
   "hash": "8de9649aeaa6",
   "ms": 7424
  },
  "amp.2": {
   "hash": "31a3920daa92",
   "ms": 6827
  },
  "amp.3": {
   "hash": "6eeaf20b7e6c",
   "ms": 8640
  },
  "amp.ask": {
   "hash": "4da71f6408dc",
   "ms": 6123
  },
  "amp.half": {
   "hash": "ab884cd61322",
   "ms": 3861
  },
  "amp.one": {
   "hash": "205425b02988",
   "ms": 4565
  },
  "amp.ten": {
   "hash": "f3a006112c54",
   "ms": 2688
  },
  "checkout.1": {
   "hash": "d01ddac412ff",
   "ms": 5909
  },
  "checkout.ask": {
   "hash": "c896becbc130",
   "ms": 6699
  },
  "checkout.columns": {
   "hash": "7efefff8688d",
   "ms": 1515
  },
  "checkout.done": {
   "hash": "3fb1e481b470",
   "ms": 7296
  },
  "checkout.error": {
   "hash": "7ead29eb509a",
   "ms": 3712
  },
  "checkout.extra": {
   "hash": "01e16787f8d5",
   "ms": 1536
  },
  "checkout.hint": {
   "hash": "b5f6400e77eb",
   "ms": 4651
  },
  "checkout.missing": {
   "hash": "9ca06277f1ca",
   "ms": 4373
  },
  "dist.1": {
   "hash": "ea3a4e554f9c",
   "ms": 4331
  },
  "dist.2": {
   "hash": "4dd419c668d8",
   "ms": 7232
  },
  "dist.3": {
   "hash": "cbfbf5a24e22",
   "ms": 5781
  },
  "dist.4": {
   "hash": "800276c9599f",
   "ms": 6400
  },
  "dist.ask": {
   "hash": "5b1dc67cb1e8",
   "ms": 1941
  },
  "dist.fifty": {
   "hash": "0882bcb36841",
   "ms": 4160
  },
  "dist.mean": {
   "hash": "21c1d0410afa",
   "ms": 5589
  },
  "dist.median": {
   "hash": "28b197cb4605",
   "ms": 3136
  },
  "finish.1": {
   "hash": "55b102a51dd5",
   "ms": 8917
  },
  "finish.2": {
   "hash": "555b915c7e66",
   "ms": 3712
  },
  "hook.1": {
   "hash": "81186ad0e3ae",
   "ms": 7808
  },
  "hook.2": {
   "hash": "39c337ad4420",
   "ms": 5611
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "p99.1": {
   "hash": "4471bd53e7d4",
   "ms": 7232
  },
  "p99.ask": {
   "hash": "02181e358457",
   "ms": 6997
  },
  "p99.columns": {
   "hash": "7efefff8688d",
   "ms": 1515
  },
  "p99.done": {
   "hash": "287f9c827745",
   "ms": 5077
  },
  "p99.error": {
   "hash": "27af3e7cb704",
   "ms": 3456
  },
  "p99.extra": {
   "hash": "266f7e3b0e0c",
   "ms": 2731
  },
  "p99.hint": {
   "hash": "40f9df7708ae",
   "ms": 7360
  },
  "p99.missing": {
   "hash": "75835aed4421",
   "ms": 4139
  },
  "queue.1": {
   "hash": "23ba4fef8573",
   "ms": 5547
  },
  "queue.2": {
   "hash": "88bd9d244084",
   "ms": 4587
  },
  "queue.3": {
   "hash": "68918d996119",
   "ms": 7872
  },
  "queue.4": {
   "hash": "2ed1a053ca50",
   "ms": 5973
  },
  "quiz.intro": {
   "hash": "f0a37944ed86",
   "ms": 1365
  },
  "quiz.pass": {
   "hash": "fd15ec4d6ef7",
   "ms": 1579
  },
  "quiz.q1": {
   "hash": "307234c0fe64",
   "ms": 8064
  },
  "quiz.q1-why": {
   "hash": "523c697bbc8c",
   "ms": 6592
  },
  "quiz.q2": {
   "hash": "c05cb2ab983f",
   "ms": 3008
  },
  "quiz.q2-why": {
   "hash": "55564abb6583",
   "ms": 5312
  },
  "quiz.q3": {
   "hash": "3f268daadb02",
   "ms": 7765
  },
  "quiz.q3-why": {
   "hash": "118130565de4",
   "ms": 5781
  },
  "quiz.q4": {
   "hash": "5cad369c732f",
   "ms": 6229
  },
  "quiz.q4-why": {
   "hash": "e1fc9c6c4600",
   "ms": 8576
  },
  "quiz.retry": {
   "hash": "bae6100ef83b",
   "ms": 3349
  },
  "quiz.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "quiz.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "quiz.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "tail.1": {
   "hash": "8de27e227025",
   "ms": 6592
  },
  "tail.2": {
   "hash": "db6c27d22db7",
   "ms": 5845
  },
  "tail.3": {
   "hash": "0efd9603436e",
   "ms": 8320
  },
  "tail.4": {
   "hash": "b7ccc5ba653f",
   "ms": 7979
  },
  "terms.1": {
   "hash": "4ed58ea74b42",
   "ms": 3776
  },
  "terms.2": {
   "hash": "32548638f717",
   "ms": 3520
  },
  "terms.3": {
   "hash": "de365c1dd049",
   "ms": 2453
  },
  "terms.4": {
   "hash": "7ed4afcf49f6",
   "ms": 6528
  }
 }
});
