// Generated by tools/voice.py from models.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("models", {
 "lines": {
  "hook.1": "Maya's bakery lives in tables. Not every system does.",
  "hook.2": "Many apps store a whole order as one JSON document. Social apps store who knows whom as a graph.",
  "hook.3": "Same data, three shapes. Each makes some questions easy and others painful. Interviewers want to hear which is which.",
  "goals.intro": "Here's what you'll be able to do by the end of this lesson.",
  "goals.1": "One. Model an order as a document, explain embedding and data locality, and name the cost of copied data.",
  "goals.2": "Two. Contrast schema on write with schema on read, and say who pays for each.",
  "goals.3": "Three. Model connections as a graph, and traverse it to any depth with a recursive CTE.",
  "rel.1": "First, the shape you know. To show order one, the database joins four tables: the order, its customer, its items, and their products.",
  "rel.2": "Each fact lives once, and joins stitch them back together on every read. That's the relational model.",
  "doc.1": "Here's the same order as a document. The customer and the items are nested right inside it.",
  "doc.2": "Putting related data inside the document is called <k>embedding</k>. It's the heart of the <k id=\"document-model\">document model</k>.",
  "doc.3": "Showing the order is now one read, with no joins. Data that's read together is stored together: <k id=\"data-locality\">data locality</k>.",
  "doc.ask": "But Maya's details are copied into her orders. She changes her phone. How many documents must change?",
  "doc.one": "If only. Her number is in every one of her orders.",
  "doc.four": "Four. One per order she's placed.",
  "doc.sixteen": "Not all of them. Just hers: four.",
  "doc.4": "It's the update anomaly from the notebook, back again. Documents trade cheap reads for costly updates of copied data.",
  "names.1": "Your turn. The documents live in a table called order docs. Pull out each order's ID and the customer's name.",
  "names.ask": "Use json extract to reach inside the document.",
  "names.hint": {
   "caption": "<b>json_extract(doc, '$.customer.name')</b>",
   "voice": "Json extract, doc, dollar dot customer dot name."
  },
  "names.error": "The database couldn't run that. Check the path: dollar, dot customer, dot name.",
  "names.extra": "Too many rows. One per document.",
  "names.missing": "Some rows are off. Keep every document, even the walk-ins with no customer.",
  "names.columns": "Two columns: the order's ID, and the customer's name.",
  "names.done": "Sixteen documents, and the walk-ins come back NULL. The path simply finds nothing.",
  "schema.1": "Order eight has a note that no other order has. Nobody declared that field.",
  "schema.2": "A table would have refused it: the structure is checked as each row is written. That's <k id=\"schema-on-write\">schema on write</k>.",
  "schema.3": "A document accepts any shape. The code that reads it copes with whatever it finds: <k id=\"schema-on-read\">schema on read</k>.",
  "schema.4": "Flexible for fields that vary. But every reader now handles every old version, forever.",
  "graph.1": "Now the third shape. Some customers brought in friends. Maya brought Ana and Omar, and they brought others.",
  "graph.2": "People are nodes, and each referral is an edge between two of them. That's the <k id=\"graph-model\">graph model</k>.",
  "graph.3": "Who joined because of Maya, directly or not? Follow the edges one hop at a time until they run out.",
  "graph.4": "That's a <k>traversal</k>. Ana and Omar, then Ines and Yuki, then Priya: three hops deep.",
  "graph.5": "SQL can do it with a recursive CTE. Graph databases make it the main event, with queries like: follow referred, any depth.",
  "net.1": "Your turn. Find everyone Maya brought in, at any depth.",
  "net.ask": "Finish the recursive step: join referrals to the people found so far.",
  "net.hint": {
   "caption": "<b>SELECT r.referred_id FROM referrals r JOIN net ON r.referrer_id = net.id</b>",
   "voice": "Select the referred I D from referrals, joined to net, where the referrer is someone already in net."
  },
  "net.error": "The database couldn't run that. Check the join inside the CTE.",
  "net.extra": "Too many people. Start from Maya's referrals only.",
  "net.missing": "Some people are missing. Is the recursive step following the edges from people already found?",
  "net.columns": "Just the names, please.",
  "net.done": "Five people, three hops deep. That's a graph traversal in SQL.",
  "pick.1": "So which shape when? Here's how to say it in an interview.",
  "pick.2": "Documents when data is read as one tree, like an order or a profile, and rarely joined to much else.",
  "pick.3": "Graphs when everything connects to everything, and questions follow links to an unknown depth.",
  "pick.4": "Tables for everything in between, which is most things: many-to-many data, reports, and rules to enforce.",
  "pick.ask": "A social app shows friends of friends of friends. Which fits most naturally?",
  "pick.graph": "Graph. Following links to any depth is exactly what it's built for.",
  "pick.document": "A document can hold your own friends list, but friends of friends means following links. That's a graph.",
  "pick.relational": "Tables can do it with recursive queries, but it gets slow and awkward at depth. A graph fits more naturally.",
  "pick.5": "And the lines blur. PostgreSQL stores JSON columns, and many document databases now do joins. Pick by how the data is read.",
  "recap.intro": "Let's look back at what you can do now.",
  "recap.1": "A document embeds the customer and the items, so showing an order is one read with no joins. The cost: Maya's phone is copied four times.",
  "recap.2": "Tables check the shape as each row is written. Documents take any shape, and every reader copes. Only order eight has a note.",
  "recap.3": "In a graph, people are nodes and referrals are edges. A traversal follows them hop by hop: Maya's network is five people, three hops deep.",
  "check.intro": "Now three quick checks. Each asks you to use an idea, not just name it.",
  "check.q1": "Each order document embeds the price of every item. The bakery raises the croissant's price. What should happen to the old order documents?",
  "check.q1-why": "Leave them. An order should freeze the price it was sold at. Not every copy is a bug: copy what should freeze, point at what must stay current.",
  "check.q2": "A new app version stores the customer's phone as a list. Older documents hold a single number. With schema on read, who deals with the difference?",
  "check.q2-why": "Every piece of code that reads phones. Schema on read moves the check from the write to every reader.",
  "check.q3": "Why does a plain join struggle to find everyone Maya brought in, at any depth?",
  "check.q3-why": "Each join follows exactly one hop, and nobody knows how many hops there are. A recursive query repeats the hop until nothing new appears.",
  "check.right1": "Right.",
  "check.right2": "Exactly.",
  "check.right3": "Correct.",
  "check.pass": {
   "caption": "<b>{right} / 3</b>. The ideas are sticking.",
   "voice": "Nicely done. The ideas are sticking."
  },
  "check.retry": {
   "caption": "<b>{right} / 3</b>. The goals marked revisit are the ones to replay.",
   "voice": "A few to revisit. The goals marked revisit at the end are the ones to replay."
  },
  "interview.intro": "Now an interview round. Two quick questions, then one you answer in your own words.",
  "interview.w1": {
   "caption": "When would you choose a document database over a relational one?",
   "speaker": "interviewer"
  },
  "interview.w1-why": "When data is read as one self-contained tree, like an order or a profile, and rarely joined. That's locality.",
  "interview.w2": {
   "caption": "What's the difference between schema on write and schema on read?",
   "speaker": "interviewer"
  },
  "interview.w2-why": "Where the structure is enforced: by the database on every write, or by the code on every read.",
  "interview.right1": "Good answer.",
  "interview.right2": "That's the one they want.",
  "interview.open": {
   "caption": "The bakery wants customer reviews and a \"customers also bought\" feature. Would you use tables, documents or a graph? Walk me through the trade-offs.",
   "voice": "The bakery wants customer reviews, and a customers-also-bought feature. Would you use tables, documents or a graph? Walk me through the trade-offs.",
   "speaker": "interviewer"
  },
  "interview.think": "Take a minute. Say your answer out loud, as if you were in the room, or jot some notes. Then reveal the model answer.",
  "interview.hint": "Press Reveal when you're ready.",
  "interview.reveal": "Here's what an interviewer listens for. Tick the points you covered.",
  "interview.rate": "Be honest. How did you do?",
  "interview.got": "Nice. That's an answer that lands.",
  "interview.partly": "Good start. It's in your flashcards now, so it'll come back.",
  "interview.missed": "That's what practice is for. It's in your flashcards, and it'll come back.",
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. Tables store each fact once, documents store what's read together, and graphs store connections. Choose by how the data is read.",
  "finish.2": "Next up: measuring a system, with latency, throughput and percentiles."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "document-model": {
   "term": "Document model",
   "def": "Stores each record as one self-contained document, often JSON, with related data nested inside it. MongoDB is the classic example."
  },
  "embedding": {
   "term": "Embedding",
   "def": "Putting related data inside the document, like an order's items and a copy of its customer, instead of pointing to another table."
  },
  "data-locality": {
   "term": "Data locality",
   "def": "Data that's read together is stored together, so one read fetches it all. The main win of a document."
  },
  "schema-on-write": {
   "term": "Schema on write",
   "def": "The database checks every row against a declared structure when it's written. Tables work this way."
  },
  "schema-on-read": {
   "term": "Schema on read",
   "def": "Any shape is accepted when written; the code that reads it has to cope with each version. Documents work this way."
  },
  "graph-model": {
   "term": "Graph model",
   "def": "Stores things as nodes and the relationships between them as edges, for data where almost anything can connect to anything."
  },
  "traversal": {
   "term": "Traversal",
   "def": "Following edges from node to node, often to an unknown depth, like friends of friends. SQL does it with a recursive CTE."
  }
 },
 "audio": {
  "check.intro": {
   "hash": "e5b8ce767e4c",
   "ms": 4352
  },
  "check.pass": {
   "hash": "2042c6b1884a",
   "ms": 2219
  },
  "check.q1": {
   "hash": "348f8a74fc2f",
   "ms": 8533
  },
  "check.q1-why": {
   "hash": "e8a8cb88fba8",
   "ms": 8107
  },
  "check.q2": {
   "hash": "9e95f5f111e7",
   "ms": 8768
  },
  "check.q2-why": {
   "hash": "b16bf66aae9b",
   "ms": 5931
  },
  "check.q3": {
   "hash": "bc6b81840bfa",
   "ms": 4373
  },
  "check.q3-why": {
   "hash": "e5ecc25e43f3",
   "ms": 8533
  },
  "check.retry": {
   "hash": "3429b67ce974",
   "ms": 4800
  },
  "check.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "check.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "check.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "doc.1": {
   "hash": "60db077745a4",
   "ms": 5568
  },
  "doc.2": {
   "hash": "23b273329327",
   "ms": 6101
  },
  "doc.3": {
   "hash": "f61873094abf",
   "ms": 6891
  },
  "doc.4": {
   "hash": "de5585c5899a",
   "ms": 7040
  },
  "doc.ask": {
   "hash": "91de76bcbbf7",
   "ms": 6187
  },
  "doc.four": {
   "hash": "a7deb85969de",
   "ms": 1920
  },
  "doc.one": {
   "hash": "ddb349035331",
   "ms": 2901
  },
  "doc.sixteen": {
   "hash": "39e817dea162",
   "ms": 2133
  },
  "finish.1": {
   "hash": "aa9354b4b360",
   "ms": 9109
  },
  "finish.2": {
   "hash": "f064871db87a",
   "ms": 4352
  },
  "goals.1": {
   "hash": "7bd23fcd2f39",
   "ms": 6869
  },
  "goals.2": {
   "hash": "e82b062cb1f0",
   "ms": 4651
  },
  "goals.3": {
   "hash": "d90acfba12b8",
   "ms": 5696
  },
  "goals.intro": {
   "hash": "4f830014daa9",
   "ms": 2773
  },
  "graph.1": {
   "hash": "1a83621bec87",
   "ms": 6165
  },
  "graph.2": {
   "hash": "56390da8eb0c",
   "ms": 5163
  },
  "graph.3": {
   "hash": "72a7a6cb6afc",
   "ms": 6101
  },
  "graph.4": {
   "hash": "bd5f94cad459",
   "ms": 5419
  },
  "graph.5": {
   "hash": "632893e46a15",
   "ms": 8640
  },
  "hook.1": {
   "hash": "5182c5334b49",
   "ms": 3477
  },
  "hook.2": {
   "hash": "c8a0bf93932e",
   "ms": 6101
  },
  "hook.3": {
   "hash": "25aabc63035c",
   "ms": 6976
  },
  "interview.got": {
   "hash": "ff3a62868565",
   "ms": 1984
  },
  "interview.hint": {
   "hash": "71671f983567",
   "ms": 1557
  },
  "interview.intro": {
   "hash": "fd2b9f5f211e",
   "ms": 4629
  },
  "interview.missed": {
   "hash": "bdb95a72e8b4",
   "ms": 3797
  },
  "interview.open": {
   "hash": "6c7cd6979571",
   "ms": 9451
  },
  "interview.partly": {
   "hash": "68c0249489ef",
   "ms": 3243
  },
  "interview.rate": {
   "hash": "2a2b4a87bfe2",
   "ms": 1643
  },
  "interview.reveal": {
   "hash": "28474cd07ede",
   "ms": 3413
  },
  "interview.right1": {
   "hash": "ffc673b01d76",
   "ms": 896
  },
  "interview.right2": {
   "hash": "f6e03f942855",
   "ms": 1216
  },
  "interview.think": {
   "hash": "3078f157e206",
   "ms": 6912
  },
  "interview.w1": {
   "hash": "6b6440d92efe",
   "ms": 4075
  },
  "interview.w1-why": {
   "hash": "224d264197a4",
   "ms": 7168
  },
  "interview.w2": {
   "hash": "2076a93b3465",
   "ms": 4011
  },
  "interview.w2-why": {
   "hash": "fbeb21ddd572",
   "ms": 5568
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "names.1": {
   "hash": "4a09acac8421",
   "ms": 7061
  },
  "names.ask": {
   "hash": "c48a4314eccb",
   "ms": 3243
  },
  "names.columns": {
   "hash": "7ce320673427",
   "ms": 3243
  },
  "names.done": {
   "hash": "b10b9731a27e",
   "ms": 4885
  },
  "names.error": {
   "hash": "21d89572db4f",
   "ms": 4757
  },
  "names.extra": {
   "hash": "bef1f13ddfe4",
   "ms": 2133
  },
  "names.hint": {
   "hash": "27a0bb9400f6",
   "ms": 3605
  },
  "names.missing": {
   "hash": "e0f5c2ab79d7",
   "ms": 4885
  },
  "net.1": {
   "hash": "92d440577c2d",
   "ms": 3200
  },
  "net.ask": {
   "hash": "250aceeb1cab",
   "ms": 4139
  },
  "net.columns": {
   "hash": "55cbd986a0ca",
   "ms": 1365
  },
  "net.done": {
   "hash": "b91ca217e657",
   "ms": 4203
  },
  "net.error": {
   "hash": "7c270c277896",
   "ms": 3925
  },
  "net.extra": {
   "hash": "c2a42cf85bc4",
   "ms": 3008
  },
  "net.hint": {
   "hash": "1313d6ee9f62",
   "ms": 5867
  },
  "net.missing": {
   "hash": "2d2be3273b85",
   "ms": 5419
  },
  "pick.1": {
   "hash": "ce0e33ce0091",
   "ms": 2965
  },
  "pick.2": {
   "hash": "17f21cb7f78e",
   "ms": 6379
  },
  "pick.3": {
   "hash": "4a3057ac0501",
   "ms": 5056
  },
  "pick.4": {
   "hash": "c7b1d7c52360",
   "ms": 6720
  },
  "pick.5": {
   "hash": "f9e05c832501",
   "ms": 8448
  },
  "pick.ask": {
   "hash": "b34cc8706a0b",
   "ms": 4139
  },
  "pick.document": {
   "hash": "b8bb5df1c064",
   "ms": 5781
  },
  "pick.graph": {
   "hash": "2b525cd52c3f",
   "ms": 3904
  },
  "pick.relational": {
   "hash": "a149197f15b5",
   "ms": 6677
  },
  "recap.1": {
   "hash": "17087b5ce3c7",
   "ms": 9067
  },
  "recap.2": {
   "hash": "67092a011254",
   "ms": 7573
  },
  "recap.3": {
   "hash": "dac094a9efe2",
   "ms": 9045
  },
  "recap.intro": {
   "hash": "d0ec67520c20",
   "ms": 1963
  },
  "rel.1": {
   "hash": "19aaafb4c71b",
   "ms": 8021
  },
  "rel.2": {
   "hash": "3e5ff73fb839",
   "ms": 5973
  },
  "schema.1": {
   "hash": "184b6267f342",
   "ms": 4501
  },
  "schema.2": {
   "hash": "7ee75426717b",
   "ms": 5824
  },
  "schema.3": {
   "hash": "4ee383678b86",
   "ms": 5824
  },
  "schema.4": {
   "hash": "bbeb6e67a947",
   "ms": 5141
  }
 }
});
