// Generated by tools/voice.py from modeling.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("modeling", {
 "lines": {
  "teach-copies.1": "Maya runs a busy bakery. Every order goes into <b>one notebook</b>.",
  "teach-copies.2": "Maya ordered twice, so her phone number is written down <b>twice</b>.",
  "teach-copies.ask": "Now she gets a new number. What could go wrong?",
  "teach-copies.one": "Exactly. Watch.",
  "teach-copies.fine": "Let's see.",
  "teach-copies.3": "Someone updates <b>one</b> row, and moves on.",
  "teach-copies.4": "Now the notebook <b>disagrees with itself</b>. Which number is right? Nobody knows.",
  "teach-copies.5": "It gets worse. Cancel Ana's only order, and her phone number <b>vanishes</b> with it.",
  "teach-copies.6": "Two bugs, one cause: facts copied onto rows that don't own them.",
  "hunt.1": "Your turn to do the updating. Twenty-four orders. Ten seconds.",
  "hunt.ask": {
   "caption": "Press start, then tap every <b>555-0101</b> on Maya's tickets.",
   "voice": "Press start, then tap every copy of Maya's old number."
  },
  "hunt.hint": "Look for Maya's name on each ticket.",
  "hunt.wrong": "Not Maya. Keep looking.",
  "hunt.found": "All of them. This time. Nothing told you how many there were.",
  "hunt.missed": {
   "caption": "You missed <b>{missed}</b>. Maya now has two phone numbers.",
   "voice": "You missed some. Maya now has two phone numbers, and nobody would notice."
  },
  "hunt.outro": "With millions of rows, somebody misses a copy every time.",
  "cancel.1": {
   "caption": "Now the second bug. Ana placed exactly one order: <b>#104</b>.",
   "voice": "Now the second bug. Ana placed exactly one order. Number one oh four."
  },
  "cancel.ask": "Cancel it. Tap the bin on her row.",
  "cancel.hint": {
   "caption": "The \ud83d\uddd1 on order <b>#104</b>.",
   "voice": "The bin on order one oh four."
  },
  "cancel.gone": "Ana's gone. Her phone number only ever lived on that order.",
  "cancel.2": "Databases call these the <k>update anomaly</k> and the <k>deletion anomaly</k>.",
  "teach-lists.1": "The fix starts with one question: what is each fact <b>about</b>?",
  "teach-lists.2": "Some facts are about <b>people</b>, some about <b>cakes</b>, and some about the <b>order</b> itself.",
  "teach-lists.3": {
   "caption": "Give people their own list. Orders keep a <b>pointer</b> instead: <b>\u2192 C1</b> means Maya.",
   "voice": "Give people their own list. Orders keep a pointer instead. C one means Maya."
  },
  "teach-lists.4": "Cakes get their own list too. Now every order is just pointers.",
  "teach-lists.ask": "Maya changes her number again. How many places do you edit now?",
  "teach-lists.one": "One. Her number lives in exactly one place.",
  "teach-lists.two": "Just one, actually. The orders only point at her.",
  "teach-lists.5": "Every fact lives in <b>one place</b>. The IDs that link the lists are called <k id=\"key\">keys</k>.",
  "teach-lists.6": "This reshaping has a name: <k>normalization</k>.",
  "sort.1": "A new order just came in, written the old way.",
  "sort.ask": "Sort each fact onto the list of the thing it describes.",
  "sort.hint": "Ask yourself: is it about a person, a cake, or the order?",
  "sort.wrong": "Not quite. What is that fact about?",
  "sort.done": "Every fact on its own list. That's normalization, in six taps.",
  "edit.1": "Here's the reshaped bakery: a Customers list, and orders that point to it.",
  "edit.ask": "Maya has a new number. Change it, once.",
  "edit.hint": "Tap Maya's phone number on the Customers list.",
  "edit.edited": {
   "caption": "One edit, and both of Maya's orders see it. Now cancel order <b>#104</b>.",
   "voice": "One edit, and both of Maya's orders see it. Now cancel Ana's order again."
  },
  "edit.kept": "Ana stays. Deleting an order no longer deletes a person.",
  "teach-join.1": "Splitting has a cost. The screen still needs each order as <b>one line</b>.",
  "teach-join.2": {
   "caption": "Order <b>#103</b> points to <b>\u2192 C1</b>. Follow it to the Customers list.",
   "voice": "Order one oh three points to C one. Follow it to the Customers list."
  },
  "teach-join.3": {
   "caption": "Then follow <b>\u2192 I3</b> to the Items list.",
   "voice": "Then follow I three to the Items list."
  },
  "teach-join.4": "Stitching lists back together is called a <k>join</k>. A few lookups, and the data is always current.",
  "teach-join.ask": "Three lookups instead of one. Worth it?",
  "teach-join.yes": "That's the trade. And indexes make each lookup fast. You'll see how soon.",
  "teach-join.slow": "Each lookup is fast with an index. You'll see how soon.",
  "assemble.1": {
   "caption": "Your turn. Rebuild order <b>#102</b> for the screen.",
   "voice": "Your turn. Rebuild order one oh two for the screen."
  },
  "assemble.ask": "Tap the order, then follow each pointer.",
  "assemble.hint": {
   "caption": "Start with order <b>#102</b> on the Orders list.",
   "voice": "Start with order one oh two on the Orders list."
  },
  "assemble.l1": "Found it. Now follow its customer pointer.",
  "assemble.l2": "That's Omar. Now the cake.",
  "assemble.wrong": "Not that one. Look for the ID the pointer names.",
  "assemble.done": "Three lookups, one complete order. You just did a join by hand.",
  "teach-owner.1": {
   "caption": "The bakery grew. A nightly report now joins six lists, and takes <b>40 minutes</b>.",
   "voice": "The bakery grew. A nightly report now joins six lists, and takes forty minutes."
  },
  "teach-owner.2": "Tempting shortcut: copy everything into <b>one wide table</b>. Three minutes!",
  "teach-owner.3": "But customers keep changing, and nobody updates the copy. It <b>drifts</b>, and the report starts lying.",
  "teach-owner.4": "Give the copy an <b>owner</b>, like a nightly refresh, and it's stale for a day at most.",
  "teach-owner.5": "Or skip the copy, and make the joins fast with <b>indexes</b>.",
  "teach-owner.6": "Copies aren't the problem. Copies <b>nobody owns</b> are. On purpose, it's called <k>denormalization</k>.",
  "fix.1": "Your call. The report is slow. Pick a fix, then watch a month go by.",
  "fix.ask": "Try at least two fixes.",
  "fix.hint": "Tap one of the three cards.",
  "fix.repair": "Zero wrong facts all month, with one copy of everything.",
  "fix.refresh": "Stale for a day at most, then its owner fixes it.",
  "fix.wide": "Thirteen wrong facts, and climbing. Nobody owns that copy.",
  "fix.outro": "In an interview, lead with fast joins. Reach for an owned copy only when you must.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "Maya\u2019s phone number is copied onto every one of her order rows. What breaks first?",
   "voice": "Maya's phone number is copied onto every one of her order rows. What breaks first?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "Copies drift. Every edit becomes a search for every copy, and a missed one is silent.",
  "quiz.q2": {
   "caption": "A cell holds \u201cMaya \u00b7 555-0101\u201d. Splitting it into separate cells is the move databases call\u2026",
   "voice": "One cell holds Maya's name and her phone number. Splitting them into separate cells is called what?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "That's first normal form: one value per cell, so the database can filter and index it.",
  "quiz.q3": {
   "caption": "Cancelling a customer\u2019s only order also erases her phone number. The cheapest structural fix?",
   "voice": "Cancelling a customer's only order also erases her phone number. What's the cheapest structural fix?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "The phone is a fact about the person. Move it to a Customers list, and orders can come and go.",
  "quiz.q4": {
   "caption": "A nightly report joins six lists and takes 40 minutes. The safest first move?",
   "voice": "A nightly report joins six lists and takes forty minutes. What's the safest first move?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "Slow joins usually lack indexes. Fix those first, and add an owned copy only if it's still slow.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "finish.1": "That's the lesson. One fact, one place. Pointers instead of copies. And copies only when someone owns them.",
  "finish.2": "Next up: asking those tables questions, in SQL.",
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "update-anomaly": {
   "term": "Update anomaly",
   "def": "The same fact is copied onto several rows, so an update has to find every copy. Miss one and the data contradicts itself."
  },
  "deletion-anomaly": {
   "term": "Deletion anomaly",
   "def": "Deleting one row also erases a different fact that was only stored on that row."
  },
  "normalization": {
   "term": "Normalization",
   "def": "Reshaping tables so each fact lives in exactly one place: on the table of the thing it describes."
  },
  "key": {
   "term": "Key",
   "def": "A value that identifies one row (its primary key). Stored in another table to point at that row, it's a foreign key."
  },
  "join": {
   "term": "Join",
   "def": "Combining rows from several tables by matching their keys, to rebuild one complete record."
  },
  "denormalization": {
   "term": "Denormalization",
   "def": "Copying data on purpose to make reads faster, with something responsible for keeping the copies correct."
  }
 },
 "audio": {
  "assemble.1": {
   "hash": "df5c2b4df954",
   "ms": 3312
  },
  "assemble.ask": {
   "hash": "8b88a5c573d0",
   "ms": 2592
  },
  "assemble.done": {
   "hash": "39a7d4386ef9",
   "ms": 4176
  },
  "assemble.hint": {
   "hash": "97d3c548c337",
   "ms": 2772
  },
  "assemble.l1": {
   "hash": "91651c785ba8",
   "ms": 2988
  },
  "assemble.l2": {
   "hash": "6d5e0fb41bbc",
   "ms": 2340
  },
  "assemble.wrong": {
   "hash": "b3c3e89deeb0",
   "ms": 3600
  },
  "cancel.1": {
   "hash": "74543c749dc0",
   "ms": 6012
  },
  "cancel.2": {
   "hash": "ba3a06aaf4c5",
   "ms": 3888
  },
  "cancel.ask": {
   "hash": "db62aacb35c0",
   "ms": 2700
  },
  "cancel.gone": {
   "hash": "7157eca037d3",
   "ms": 4140
  },
  "cancel.hint": {
   "hash": "5b41551e8e31",
   "ms": 2304
  },
  "edit.1": {
   "hash": "2f6a197b0efa",
   "ms": 4392
  },
  "edit.ask": {
   "hash": "0fed306e4390",
   "ms": 3420
  },
  "edit.edited": {
   "hash": "d14f147a84f1",
   "ms": 4500
  },
  "edit.hint": {
   "hash": "0008713e7ab3",
   "ms": 2664
  },
  "edit.kept": {
   "hash": "3257f8ab60cf",
   "ms": 4320
  },
  "finish.1": {
   "hash": "c030c45abbf7",
   "ms": 8640
  },
  "finish.2": {
   "hash": "2ecc6548b5df",
   "ms": 4320
  },
  "fix.1": {
   "hash": "7fa1f6ee32a1",
   "ms": 5796
  },
  "fix.ask": {
   "hash": "ae577e74ae96",
   "ms": 1764
  },
  "fix.hint": {
   "hash": "708c3def22c9",
   "ms": 1656
  },
  "fix.outro": {
   "hash": "e931001cc9dd",
   "ms": 6372
  },
  "fix.refresh": {
   "hash": "777fe76b09ad",
   "ms": 3312
  },
  "fix.repair": {
   "hash": "b158970294a5",
   "ms": 4572
  },
  "fix.wide": {
   "hash": "82e2047ee924",
   "ms": 4680
  },
  "hunt.1": {
   "hash": "9374d2e985b6",
   "ms": 4572
  },
  "hunt.ask": {
   "hash": "131a1ba120ed",
   "ms": 4140
  },
  "hunt.found": {
   "hash": "800699d26e20",
   "ms": 4284
  },
  "hunt.hint": {
   "hash": "3f41d4d0daee",
   "ms": 2088
  },
  "hunt.missed": {
   "hash": "1dcad7362558",
   "ms": 5472
  },
  "hunt.outro": {
   "hash": "157dc0bb8e9f",
   "ms": 3708
  },
  "hunt.wrong": {
   "hash": "06448c22a018",
   "ms": 1980
  },
  "keywords.1": {
   "hash": "52c9899fd888",
   "ms": 2916
  },
  "keywords.ask": {
   "hash": "9e5d200f6173",
   "ms": 3708
  },
  "keywords.done": {
   "hash": "b410b19a541a",
   "ms": 4572
  },
  "keywords.hint": {
   "hash": "520960a4916d",
   "ms": 3276
  },
  "quiz.intro": {
   "hash": "08fdf9d19fee",
   "ms": 1476
  },
  "quiz.pass": {
   "hash": "1e2c41acf108",
   "ms": 2412
  },
  "quiz.q1": {
   "hash": "7558f680d6bd",
   "ms": 4824
  },
  "quiz.q1-why": {
   "hash": "d9904e76aaed",
   "ms": 6012
  },
  "quiz.q2": {
   "hash": "9557230d3e83",
   "ms": 6732
  },
  "quiz.q2-why": {
   "hash": "b8b9ad8fa954",
   "ms": 5832
  },
  "quiz.q3": {
   "hash": "30115a4efa0f",
   "ms": 6876
  },
  "quiz.q3-why": {
   "hash": "56cb67d29841",
   "ms": 5832
  },
  "quiz.q4": {
   "hash": "13ecc4bb0492",
   "ms": 5760
  },
  "quiz.q4-why": {
   "hash": "3a42cdd43df7",
   "ms": 7596
  },
  "quiz.retry": {
   "hash": "674b74cededc",
   "ms": 4067
  },
  "quiz.right1": {
   "hash": "5df4176b3959",
   "ms": 900
  },
  "quiz.right2": {
   "hash": "e99e52b00ddc",
   "ms": 1080
  },
  "quiz.right3": {
   "hash": "bbb1d6dfd81d",
   "ms": 900
  },
  "sort.1": {
   "hash": "2074b788f413",
   "ms": 2772
  },
  "sort.ask": {
   "hash": "bb4c20e85180",
   "ms": 3456
  },
  "sort.done": {
   "hash": "e5a58443a352",
   "ms": 4176
  },
  "sort.hint": {
   "hash": "b00a451857ac",
   "ms": 4428
  },
  "sort.wrong": {
   "hash": "306381bdbf14",
   "ms": 2664
  },
  "teach-copies.1": {
   "hash": "6d79c074ea66",
   "ms": 4176
  },
  "teach-copies.2": {
   "hash": "66ada7b90a70",
   "ms": 4428
  },
  "teach-copies.3": {
   "hash": "4b5203e85c39",
   "ms": 2808
  },
  "teach-copies.4": {
   "hash": "5e4c0550e060",
   "ms": 5076
  },
  "teach-copies.5": {
   "hash": "6654cd807dbf",
   "ms": 5832
  },
  "teach-copies.6": {
   "hash": "3c193be19c55",
   "ms": 4572
  },
  "teach-copies.ask": {
   "hash": "ca67ccf69cb4",
   "ms": 3276
  },
  "teach-copies.fine": {
   "hash": "933b6b302948",
   "ms": 900
  },
  "teach-copies.one": {
   "hash": "1f9a08946928",
   "ms": 1800
  },
  "teach-join.1": {
   "hash": "783112130ef2",
   "ms": 4752
  },
  "teach-join.2": {
   "hash": "47a30234f1b0",
   "ms": 4608
  },
  "teach-join.3": {
   "hash": "b864fd60905f",
   "ms": 2952
  },
  "teach-join.4": {
   "hash": "9d1753436290",
   "ms": 5760
  },
  "teach-join.ask": {
   "hash": "8c60b82ccc42",
   "ms": 2772
  },
  "teach-join.slow": {
   "hash": "79bc3fc10b34",
   "ms": 3672
  },
  "teach-join.yes": {
   "hash": "b9e2e1cf3623",
   "ms": 4860
  },
  "teach-lists.1": {
   "hash": "fa0c9e9966a6",
   "ms": 4067
  },
  "teach-lists.2": {
   "hash": "735f1aaf706c",
   "ms": 5328
  },
  "teach-lists.3": {
   "hash": "e7ee1acf2387",
   "ms": 5436
  },
  "teach-lists.4": {
   "hash": "d506016d3a04",
   "ms": 4176
  },
  "teach-lists.5": {
   "hash": "f4db434b6e7f",
   "ms": 5400
  },
  "teach-lists.6": {
   "hash": "342c394d49d4",
   "ms": 3492
  },
  "teach-lists.ask": {
   "hash": "c2034d06e7b4",
   "ms": 4176
  },
  "teach-lists.one": {
   "hash": "ae9fb76d6f91",
   "ms": 3852
  },
  "teach-lists.two": {
   "hash": "202a62faf283",
   "ms": 2916
  },
  "teach-owner.1": {
   "hash": "07dbbaa6ea77",
   "ms": 5976
  },
  "teach-owner.2": {
   "hash": "11d611bf96d2",
   "ms": 5220
  },
  "teach-owner.3": {
   "hash": "118d2daa5cc7",
   "ms": 6876
  },
  "teach-owner.4": {
   "hash": "e550000e2563",
   "ms": 4824
  },
  "teach-owner.5": {
   "hash": "7c6cadf86050",
   "ms": 4500
  },
  "teach-owner.6": {
   "hash": "3b19c3349a77",
   "ms": 7092
  }
 }
});
