// Generated by tools/voice.py from modeling.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("modeling", {
 "lines": {
  "teach-copies.1": "Maya runs a busy bakery. Every order goes into <b>one notebook</b>.",
  "teach-copies.2": "Maya ordered twice, so her phone number is written down <b>twice</b>.",
  "teach-copies.ask": "Now she gets a new number. What could go wrong?",
  "teach-copies.one": "Exactly. Watch.",
  "teach-copies.fine": "Let's see.",
  "teach-copies.3": "Someone updates <b>one</b> row, and moves on.",
  "teach-copies.4": "Now the notebook <b>disagrees with itself</b>. Which number is right? Nobody knows.",
  "teach-copies.5": "It gets worse. Cancel Ana's only order, and her phone number <b>vanishes</b> with it.",
  "teach-copies.6": "Two bugs, one cause: facts copied onto rows that don't own them.",
  "hunt.1": "Your turn to do the updating. Twenty-four orders. Ten seconds.",
  "hunt.ask": {
   "caption": "Press start, then tap every <b>555-0101</b> on Maya's tickets.",
   "voice": "Press start, then tap every copy of Maya's old number."
  },
  "hunt.hint": "Look for Maya's name on each ticket.",
  "hunt.wrong": "Not Maya. Keep looking.",
  "hunt.found": "All of them. This time. Nothing told you how many there were.",
  "hunt.missed": {
   "caption": "You missed <b>{missed}</b>. Maya now has two phone numbers.",
   "voice": "You missed some. Maya now has two phone numbers, and nobody would notice."
  },
  "hunt.outro": "With millions of rows, somebody misses a copy every time.",
  "cancel.1": {
   "caption": "Now the second bug. Ana placed exactly one order: <b>#104</b>.",
   "voice": "Now the second bug. Ana placed exactly one order. Number one oh four."
  },
  "cancel.ask": "Cancel it. Tap the bin on her row.",
  "cancel.hint": {
   "caption": "The \ud83d\uddd1 on order <b>#104</b>.",
   "voice": "The bin on order one oh four."
  },
  "cancel.gone": "Ana's gone. Her phone number only ever lived on that order.",
  "cancel.2": "Databases call these the <b>update anomaly</b> and the <b>deletion anomaly</b>.",
  "teach-lists.1": "The fix starts with one question: what is each fact <b>about</b>?",
  "teach-lists.2": "Some facts are about <b>people</b>, some about <b>cakes</b>, and some about the <b>order</b> itself.",
  "teach-lists.3": {
   "caption": "Give people their own list. Orders keep a <b>pointer</b> instead: <b>\u2192 C1</b> means Maya.",
   "voice": "Give people their own list. Orders keep a pointer instead. C one means Maya."
  },
  "teach-lists.4": "Cakes get their own list too. Now every order is just pointers.",
  "teach-lists.ask": "Maya changes her number again. How many places do you edit now?",
  "teach-lists.one": "One. Her number lives in exactly one place.",
  "teach-lists.two": "Just one, actually. The orders only point at her.",
  "teach-lists.5": "Every fact lives in <b>one place</b>. The IDs that link the lists are called <b>keys</b>.",
  "teach-lists.6": "This reshaping has a name: <b>normalization</b>.",
  "sort.1": "A new order just came in, written the old way.",
  "sort.ask": "Sort each fact onto the list of the thing it describes.",
  "sort.hint": "Ask yourself: is it about a person, a cake, or the order?",
  "sort.wrong": "Not quite. What is that fact about?",
  "sort.done": "Every fact on its own list. That's normalization, in six taps.",
  "edit.1": "Here's the reshaped bakery: a Customers list, and orders that point to it.",
  "edit.ask": "Maya has a new number. Change it, once.",
  "edit.hint": "Tap Maya's phone number on the Customers list.",
  "edit.edited": {
   "caption": "One edit, and both of Maya's orders see it. Now cancel order <b>#104</b>.",
   "voice": "One edit, and both of Maya's orders see it. Now cancel Ana's order again."
  },
  "edit.kept": "Ana stays. Deleting an order no longer deletes a person.",
  "teach-join.1": "Splitting has a cost. The screen still needs each order as <b>one line</b>.",
  "teach-join.2": {
   "caption": "Order <b>#103</b> points to <b>\u2192 C1</b>. Follow it to the Customers list.",
   "voice": "Order one oh three points to C one. Follow it to the Customers list."
  },
  "teach-join.3": {
   "caption": "Then follow <b>\u2192 I3</b> to the Items list.",
   "voice": "Then follow I three to the Items list."
  },
  "teach-join.4": "Stitching lists back together is called a <b>join</b>. A few lookups, and the data is always current.",
  "teach-join.ask": "Three lookups instead of one. Worth it?",
  "teach-join.yes": "That's the trade. And indexes make each lookup fast. You'll see how soon.",
  "teach-join.slow": "Each lookup is fast with an index. You'll see how soon.",
  "assemble.1": {
   "caption": "Your turn. Rebuild order <b>#102</b> for the screen.",
   "voice": "Your turn. Rebuild order one oh two for the screen."
  },
  "assemble.ask": "Tap the order, then follow each pointer.",
  "assemble.hint": {
   "caption": "Start with order <b>#102</b> on the Orders list.",
   "voice": "Start with order one oh two on the Orders list."
  },
  "assemble.l1": "Found it. Now follow its customer pointer.",
  "assemble.l2": "That's Omar. Now the cake.",
  "assemble.wrong": "Not that one. Look for the ID the pointer names.",
  "assemble.done": "Three lookups, one complete order. You just did a join by hand.",
  "teach-owner.1": {
   "caption": "The bakery grew. A nightly report now joins six lists, and takes <b>40 minutes</b>.",
   "voice": "The bakery grew. A nightly report now joins six lists, and takes forty minutes."
  },
  "teach-owner.2": "Tempting shortcut: copy everything into <b>one wide table</b>. Three minutes!",
  "teach-owner.3": "But customers keep changing, and nobody updates the copy. It <b>drifts</b>, and the report starts lying.",
  "teach-owner.4": "Give the copy an <b>owner</b>, like a nightly refresh, and it's stale for a day at most.",
  "teach-owner.5": "Or skip the copy, and make the joins fast with <b>indexes</b>.",
  "teach-owner.6": "Copies aren't the problem. Copies <b>nobody owns</b> are. On purpose, it's called <b>denormalization</b>.",
  "fix.1": "Your call. The report is slow. Pick a fix, then watch a month go by.",
  "fix.ask": "Try at least two fixes.",
  "fix.hint": "Tap one of the three cards.",
  "fix.repair": "Zero wrong facts all month, with one copy of everything.",
  "fix.refresh": "Stale for a day at most, then its owner fixes it.",
  "fix.wide": "Thirteen wrong facts, and climbing. Nobody owns that copy.",
  "fix.outro": "In an interview, lead with fast joins. Reach for an owned copy only when you must.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "Maya\u2019s phone number is copied onto every one of her order rows. What breaks first?",
   "voice": "Maya's phone number is copied onto every one of her order rows. What breaks first?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "Copies drift. Every edit becomes a search for every copy, and a missed one is silent.",
  "quiz.q2": {
   "caption": "A cell holds \u201cMaya \u00b7 555-0101\u201d. Splitting it into separate cells is the move databases call\u2026",
   "voice": "One cell holds Maya's name and her phone number. Splitting them into separate cells is called what?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "That's first normal form: one value per cell, so the database can filter and index it.",
  "quiz.q3": {
   "caption": "Cancelling a customer\u2019s only order also erases her phone number. The cheapest structural fix?",
   "voice": "Cancelling a customer's only order also erases her phone number. What's the cheapest structural fix?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "The phone is a fact about the person. Move it to a Customers list, and orders can come and go.",
  "quiz.q4": {
   "caption": "A nightly report joins six lists and takes 40 minutes. The safest first move?",
   "voice": "A nightly report joins six lists and takes forty minutes. What's the safest first move?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "Slow joins usually lack indexes. Fix those first, and add an owned copy only if it's still slow.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "finish.1": "That's the lesson. One fact, one place. Pointers instead of copies. And copies only when someone owns them.",
  "finish.2": "Next up: how a database actually reads those rows from disk."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "audio": {
  "assemble.1": {
   "hash": "11112a68ba44",
   "ms": 2859
  },
  "assemble.ask": {
   "hash": "3369234b22b5",
   "ms": 2325
  },
  "assemble.done": {
   "hash": "d79ed7844415",
   "ms": 3691
  },
  "assemble.hint": {
   "hash": "cb05c8d6eb0b",
   "ms": 2453
  },
  "assemble.l1": {
   "hash": "4f38cfc07f23",
   "ms": 2453
  },
  "assemble.l2": {
   "hash": "a0b2343a208e",
   "ms": 1600
  },
  "assemble.wrong": {
   "hash": "8ab8a7f8885a",
   "ms": 2901
  },
  "cancel.1": {
   "hash": "6e48e7b38638",
   "ms": 4544
  },
  "cancel.2": {
   "hash": "b2e2ec1593e9",
   "ms": 4096
  },
  "cancel.ask": {
   "hash": "4e9af7ce3ea0",
   "ms": 2048
  },
  "cancel.gone": {
   "hash": "7f4ba6705aea",
   "ms": 3371
  },
  "cancel.hint": {
   "hash": "80792dc58464",
   "ms": 1771
  },
  "edit.1": {
   "hash": "1ee047e92e3a",
   "ms": 4352
  },
  "edit.ask": {
   "hash": "273081cd3772",
   "ms": 2368
  },
  "edit.edited": {
   "hash": "51dc9ae10fce",
   "ms": 4587
  },
  "edit.hint": {
   "hash": "db19c91a1ab3",
   "ms": 2453
  },
  "edit.kept": {
   "hash": "cc3a27a564d5",
   "ms": 3456
  },
  "finish.1": {
   "hash": "a9e38f47405e",
   "ms": 6699
  },
  "finish.2": {
   "hash": "555b915c7e66",
   "ms": 3712
  },
  "fix.1": {
   "hash": "46d2ea04c6df",
   "ms": 3989
  },
  "fix.ask": {
   "hash": "b481b7ad9477",
   "ms": 1429
  },
  "fix.hint": {
   "hash": "4205f32f54e1",
   "ms": 1579
  },
  "fix.outro": {
   "hash": "416c152bb5ab",
   "ms": 4864
  },
  "fix.refresh": {
   "hash": "a160ba57bd41",
   "ms": 2688
  },
  "fix.repair": {
   "hash": "44b2938304e6",
   "ms": 3328
  },
  "fix.wide": {
   "hash": "86c5e217d568",
   "ms": 3669
  },
  "hunt.1": {
   "hash": "7eac90374bd7",
   "ms": 3776
  },
  "hunt.ask": {
   "hash": "a2323efe49f8",
   "ms": 3157
  },
  "hunt.found": {
   "hash": "d66879e5858f",
   "ms": 3200
  },
  "hunt.hint": {
   "hash": "415dea8bc81a",
   "ms": 1941
  },
  "hunt.missed": {
   "hash": "8d260f7f2fb1",
   "ms": 3947
  },
  "hunt.outro": {
   "hash": "71e3ef528dcf",
   "ms": 3371
  },
  "hunt.wrong": {
   "hash": "d16406dea988",
   "ms": 1515
  },
  "quiz.intro": {
   "hash": "f0a37944ed86",
   "ms": 1365
  },
  "quiz.pass": {
   "hash": "fd15ec4d6ef7",
   "ms": 1579
  },
  "quiz.q1": {
   "hash": "c10e7677779d",
   "ms": 5461
  },
  "quiz.q1-why": {
   "hash": "a801c87199bf",
   "ms": 5269
  },
  "quiz.q2": {
   "hash": "a8e351df7ebe",
   "ms": 6357
  },
  "quiz.q2-why": {
   "hash": "1c30386ae76f",
   "ms": 5291
  },
  "quiz.q3": {
   "hash": "f179e00f3ab0",
   "ms": 6933
  },
  "quiz.q3-why": {
   "hash": "1d5759f1d0d5",
   "ms": 5611
  },
  "quiz.q4": {
   "hash": "40fa5061e3c4",
   "ms": 5931
  },
  "quiz.q4-why": {
   "hash": "c88fdcd2ced8",
   "ms": 6379
  },
  "quiz.retry": {
   "hash": "bae6100ef83b",
   "ms": 3349
  },
  "quiz.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "quiz.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "quiz.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "sort.1": {
   "hash": "1eed94742b32",
   "ms": 2517
  },
  "sort.ask": {
   "hash": "831ba805af64",
   "ms": 2987
  },
  "sort.done": {
   "hash": "3886feb7f424",
   "ms": 3904
  },
  "sort.hint": {
   "hash": "ada8a5a399d9",
   "ms": 3477
  },
  "sort.wrong": {
   "hash": "3a1b84231d1e",
   "ms": 1984
  },
  "teach-copies.1": {
   "hash": "ba44d0a40e52",
   "ms": 3968
  },
  "teach-copies.2": {
   "hash": "f84ff6239780",
   "ms": 3520
  },
  "teach-copies.3": {
   "hash": "4fe16ebfe83d",
   "ms": 2240
  },
  "teach-copies.4": {
   "hash": "c647dcaf7d20",
   "ms": 4651
  },
  "teach-copies.5": {
   "hash": "0cfe4d0fe98f",
   "ms": 4608
  },
  "teach-copies.6": {
   "hash": "bd5d9c46a257",
   "ms": 3819
  },
  "teach-copies.ask": {
   "hash": "0b3eee18067a",
   "ms": 2517
  },
  "teach-copies.fine": {
   "hash": "d4e2dae96d94",
   "ms": 853
  },
  "teach-copies.one": {
   "hash": "546eb160f087",
   "ms": 1387
  },
  "teach-join.1": {
   "hash": "fe197ccdcdcd",
   "ms": 3989
  },
  "teach-join.2": {
   "hash": "87acfd5c327d",
   "ms": 4075
  },
  "teach-join.3": {
   "hash": "2dc04fa148fb",
   "ms": 2176
  },
  "teach-join.4": {
   "hash": "a47522c8f23a",
   "ms": 5589
  },
  "teach-join.ask": {
   "hash": "3c8d34afa983",
   "ms": 2304
  },
  "teach-join.slow": {
   "hash": "49b13e1820a6",
   "ms": 3157
  },
  "teach-join.yes": {
   "hash": "e7bff4b1a342",
   "ms": 4139
  },
  "teach-lists.1": {
   "hash": "886a614beded",
   "ms": 3243
  },
  "teach-lists.2": {
   "hash": "c09c036abbe9",
   "ms": 4139
  },
  "teach-lists.3": {
   "hash": "2eef5d6ab983",
   "ms": 4736
  },
  "teach-lists.4": {
   "hash": "5f178686b0c9",
   "ms": 3669
  },
  "teach-lists.5": {
   "hash": "2b496713a786",
   "ms": 4437
  },
  "teach-lists.6": {
   "hash": "5b05eaa747a1",
   "ms": 2688
  },
  "teach-lists.ask": {
   "hash": "40c28afecd25",
   "ms": 3563
  },
  "teach-lists.one": {
   "hash": "72e7dae7a440",
   "ms": 2517
  },
  "teach-lists.two": {
   "hash": "147ec6d5238b",
   "ms": 2901
  },
  "teach-owner.1": {
   "hash": "9b3f6d8f434d",
   "ms": 4885
  },
  "teach-owner.2": {
   "hash": "b55717d1d599",
   "ms": 4437
  },
  "teach-owner.3": {
   "hash": "0c96c636a609",
   "ms": 5973
  },
  "teach-owner.4": {
   "hash": "ffdfc7c042f6",
   "ms": 4416
  },
  "teach-owner.5": {
   "hash": "8f1ce63948fe",
   "ms": 3264
  },
  "teach-owner.6": {
   "hash": "51bd4e55466d",
   "ms": 5888
  }
 }
});
