// Generated by tools/voice.py from null.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("null", {
 "lines": {
  "hook.1": "Raj never gave his city. Three customers have no phone. Two orders have no customer.",
  "hook.2": "Each gap is a NULL, and NULL doesn't mean zero or empty. It means unknown.",
  "hook.3": "Unknown values break queries quietly: no error, just wrong answers. Here are the traps interviewers love.",
  "unknown.1": "Find the customers with no city. The obvious query says: city equals NULL.",
  "unknown.2": "Nothing comes back. Not even Raj.",
  "unknown.3": "Is Raj's unknown city equal to unknown? Nobody knows. So the answer isn't true or false. It's unknown.",
  "unknown.4": "That's <k id=\"three-valued-logic\">three-valued logic</k>: true, false, or unknown. And WHERE keeps only the rows where the test is true.",
  "unknown.5": "To find missing values, ask directly: city <k id=\"is-null\">IS NULL</k>. There's Raj.",
  "not.1": "Now the bakery wants every customer who isn't in Lisbon. Ten customers, three in Lisbon.",
  "not.ask": "City not equal to Lisbon. How many rows come back?",
  "not.seven": "That's the right answer to the question. But not what the query returns.",
  "not.six": "Six. You saw Raj coming.",
  "not.three": "Three is Lisbon. The rest should be seven, but watch.",
  "not.2": "Six rows. Raj is missing again. Is his unknown city different from Lisbon? Unknown, so WHERE drops him.",
  "not.3": {
   "caption": "Say what you mean: <b>city &lt;&gt; 'Lisbon' OR city IS NULL</b>. Now it's seven.",
   "voice": "Say what you mean: city is not Lisbon, or city is null. Now it's seven."
  },
  "not.4": "Or use <k id=\"is-distinct-from\">IS DISTINCT FROM</k>, which treats NULL as a value. SQLite spells it IS NOT.",
  "away.1": "Your turn. List every customer who isn't in Lisbon, including anyone whose city is unknown.",
  "away.ask": "Fix the WHERE clause so Raj is included.",
  "away.hint": {
   "caption": "<b>WHERE city &lt;&gt; 'Lisbon' OR city IS NULL</b>",
   "voice": "Where city is not Lisbon, or city is null."
  },
  "away.error": "The database couldn't run that. Read the message under the editor.",
  "away.extra": "Too many rows. Lisbon customers should stay out.",
  "away.missing": "Someone's missing. Is Raj there? His city is NULL.",
  "away.columns": "Just the customer's name.",
  "away.done": "Seven customers, Raj included.",
  "notin.1": "The worst trap. Customers who never ordered: id NOT IN the customer IDs on orders.",
  "notin.ask": "Lena and Theo have never ordered. How many rows does this return?",
  "notin.two": "It should be two. It's zero.",
  "notin.zero": "Zero. You know this one.",
  "notin.ten": "Fewer. In fact, zero.",
  "notin.2": "No rows at all. The walk-in orders put a NULL in the list.",
  "notin.3": "NOT IN means: not equal to one, and not equal to two, and not equal to NULL. That last part is unknown, for every customer.",
  "notin.4": "One NULL in the list, and NOT IN returns nothing. That's the <k id=\"not-in-null\">NOT IN trap</k>.",
  "notin.5": "The fix: NOT EXISTS, which has no such problem. Or filter the NULLs out of the list.",
  "never.1": "Your turn. Fix the query so it finds Lena and Theo.",
  "never.ask": "Rewrite it with NOT EXISTS, or filter the NULLs out of the list.",
  "never.hint": {
   "caption": "Add <b>WHERE customer_id IS NOT NULL</b> inside the subquery, or use <b>NOT EXISTS</b>.",
   "voice": "Add where customer ID is not null inside the subquery, or use not exists."
  },
  "never.error": "The database couldn't run that. Check the brackets around the subquery.",
  "never.extra": "Too many customers. Some of them have ordered.",
  "never.missing": "Still missing rows. Is there a NULL left in the list?",
  "never.columns": "Just the customer's name.",
  "never.done": "Lena and Theo. Same question, one NULL handled.",
  "expr.1": "NULL spreads through expressions too. Build a text message: Call, name, on, phone.",
  "expr.2": "Omar has no phone, so his whole message is NULL. Ten plus NULL is NULL too. That's <k id=\"null-propagation\">NULL propagation</k>.",
  "expr.3": {
   "caption": "<k>COALESCE</k> picks the first value that isn't NULL: <b>COALESCE(phone, 'no phone')</b>.",
   "voice": "COALESCE picks the first value that isn't null. Coalesce phone, no phone."
  },
  "avg.1": "And in aggregates. What's the average spend per customer?",
  "avg.2": "Lena and Theo never ordered, so their total is NULL, not zero. AVG skips them.",
  "avg.3": {
   "caption": "So the average comes out at <b>18.41</b>, over eight customers. Count them as zero, and it's <b>14.72</b>, over ten.",
   "voice": "So the average comes out at eighteen forty-one, over eight customers. Count them as zero, and it's fourteen seventy-two, over ten."
  },
  "avg.4": "Neither is wrong. Decide what the question means, then say it in SQL.",
  "phone.1": "Last one. Show every customer's name and phone, with the words no phone where it's missing.",
  "phone.ask": "Use COALESCE in the SELECT.",
  "phone.hint": {
   "caption": "<b>SELECT name, COALESCE(phone, 'no phone')</b>",
   "voice": "Select the name, and coalesce phone, no phone."
  },
  "phone.error": "The database couldn't run that. Check the quotes around no phone.",
  "phone.extra": "Too many rows. One per customer.",
  "phone.missing": "The rows don't match. Is the default exactly: no phone?",
  "phone.columns": "Two columns: the name, and the phone or the default.",
  "phone.done": "Ten customers, three with no phone. No NULLs left to trip over.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "What does <code>WHERE city = NULL</code> return?",
   "voice": "What does where city equals null return?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "Comparing with NULL is unknown, never true, so no row passes. Use IS NULL.",
  "quiz.q2": {
   "caption": "10 customers: 3 in Lisbon, 1 with a NULL city. How many rows does <code>WHERE city &lt;&gt; 'Lisbon'</code> return?",
   "voice": "Ten customers: three in Lisbon, one with a null city. How many rows does where city is not Lisbon return?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "The NULL city is unknown, not different, so it's dropped: six, not seven.",
  "quiz.q3": {
   "caption": "<code>WHERE id NOT IN (SELECT customer_id FROM orders)</code> returns nothing, though some customers never ordered. Why?",
   "voice": "Where the ID is not in the customer IDs from orders returns nothing, though some customers never ordered. Why?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "The list contains a NULL, so NOT IN is never true. Use NOT EXISTS, or filter out the NULLs.",
  "quiz.q4": {
   "caption": "What does <code>COALESCE(phone, 'no phone')</code> return when phone is NULL?",
   "voice": "What does coalesce phone, no phone return when phone is null?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "COALESCE returns its first argument that isn't NULL.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson, and the SQL module. NULL means unknown. Test it with IS NULL, never trust NOT IN near it, and give it a default when you mean one.",
  "finish.2": "Next up: keys the database enforces, and the shapes relationships take."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "three-valued-logic": {
   "term": "Three-valued logic",
   "def": "SQL tests can be true, false, or unknown. Anything compared with NULL is unknown, and WHERE keeps only rows where the test is true."
  },
  "is-null": {
   "term": "IS NULL",
   "def": "The only way to test for a missing value. = NULL is never true, not even for NULL."
  },
  "is-distinct-from": {
   "term": "IS DISTINCT FROM",
   "def": "A comparison that treats NULL as a value: NULL is distinct from 'Lisbon', and not distinct from NULL. SQLite spells it IS NOT."
  },
  "not-in-null": {
   "term": "NOT IN and NULL",
   "def": "If the list after NOT IN contains a NULL, no row can pass, so the query returns nothing. Use NOT EXISTS, or filter the NULLs out."
  },
  "null-propagation": {
   "term": "NULL propagation",
   "def": "Arithmetic or text built from a NULL is NULL: 10 + NULL, 'Call ' || NULL."
  },
  "coalesce": {
   "term": "COALESCE",
   "def": "Returns its first argument that isn't NULL. COALESCE(phone, 'no phone') gives a default for missing values."
  }
 },
 "audio": {
  "avg.1": {
   "hash": "78a47c01af3f",
   "ms": 3008
  },
  "avg.2": {
   "hash": "e52ad0e8a397",
   "ms": 5397
  },
  "avg.3": {
   "hash": "a4d0bc421c21",
   "ms": 8043
  },
  "avg.4": {
   "hash": "b4fbd03f6edb",
   "ms": 4523
  },
  "away.1": {
   "hash": "ecb601a38813",
   "ms": 5696
  },
  "away.ask": {
   "hash": "f093fc44a248",
   "ms": 2283
  },
  "away.columns": {
   "hash": "42b26453b27a",
   "ms": 1408
  },
  "away.done": {
   "hash": "9b338ddf3a8f",
   "ms": 2176
  },
  "away.error": {
   "hash": "27af3e7cb704",
   "ms": 3456
  },
  "away.extra": {
   "hash": "a447f6c698aa",
   "ms": 2773
  },
  "away.hint": {
   "hash": "728e27553371",
   "ms": 2539
  },
  "away.missing": {
   "hash": "4fd85b7e59a4",
   "ms": 3051
  },
  "expr.1": {
   "hash": "184d30d97f1d",
   "ms": 4907
  },
  "expr.2": {
   "hash": "30d65e1cbd5f",
   "ms": 6549
  },
  "expr.3": {
   "hash": "7f8246d5137d",
   "ms": 4267
  },
  "finish.1": {
   "hash": "060679577c43",
   "ms": 9259
  },
  "finish.2": {
   "hash": "14c565dc5ca3",
   "ms": 4651
  },
  "hook.1": {
   "hash": "2ff2ba31d690",
   "ms": 5568
  },
  "hook.2": {
   "hash": "0f26bb038d34",
   "ms": 4736
  },
  "hook.3": {
   "hash": "cf72e467580a",
   "ms": 6656
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "never.1": {
   "hash": "4f4e308ec56b",
   "ms": 3285
  },
  "never.ask": {
   "hash": "3f9f29bdcdda",
   "ms": 3563
  },
  "never.columns": {
   "hash": "42b26453b27a",
   "ms": 1408
  },
  "never.done": {
   "hash": "201a5a16bb6f",
   "ms": 3179
  },
  "never.error": {
   "hash": "4ffebfd50b27",
   "ms": 3712
  },
  "never.extra": {
   "hash": "baaae751051f",
   "ms": 2432
  },
  "never.hint": {
   "hash": "3d001f5bb9e2",
   "ms": 4843
  },
  "never.missing": {
   "hash": "f6430ea438c0",
   "ms": 2923
  },
  "not.1": {
   "hash": "1fc6f82b4891",
   "ms": 5547
  },
  "not.2": {
   "hash": "58656f27af76",
   "ms": 6549
  },
  "not.3": {
   "hash": "5dd7b7647288",
   "ms": 4373
  },
  "not.4": {
   "hash": "1caf199c3ae6",
   "ms": 5248
  },
  "not.ask": {
   "hash": "a75faf5096ca",
   "ms": 3093
  },
  "not.seven": {
   "hash": "30037f89a6e3",
   "ms": 3819
  },
  "not.six": {
   "hash": "c1558f6d3383",
   "ms": 1728
  },
  "not.three": {
   "hash": "4820d8b0c8fb",
   "ms": 3008
  },
  "notin.1": {
   "hash": "6530902aca10",
   "ms": 5269
  },
  "notin.2": {
   "hash": "53d34afe77d7",
   "ms": 3392
  },
  "notin.3": {
   "hash": "5420da9b60f4",
   "ms": 8085
  },
  "notin.4": {
   "hash": "bf5936cfb239",
   "ms": 4075
  },
  "notin.5": {
   "hash": "f6e8c7cdc54f",
   "ms": 4992
  },
  "notin.ask": {
   "hash": "a8db4bd7bf9f",
   "ms": 3968
  },
  "notin.ten": {
   "hash": "4a73f1ebe1b8",
   "ms": 1600
  },
  "notin.two": {
   "hash": "d10d072644d8",
   "ms": 1728
  },
  "notin.zero": {
   "hash": "c2c23c9fe3cf",
   "ms": 1515
  },
  "phone.1": {
   "hash": "04621734fffe",
   "ms": 5163
  },
  "phone.ask": {
   "hash": "591c4752ef28",
   "ms": 1536
  },
  "phone.columns": {
   "hash": "ee8ef8800dc2",
   "ms": 2944
  },
  "phone.done": {
   "hash": "abe8605f1c33",
   "ms": 3883
  },
  "phone.error": {
   "hash": "c38873eb7bb6",
   "ms": 3477
  },
  "phone.extra": {
   "hash": "7b7d23412632",
   "ms": 2091
  },
  "phone.hint": {
   "hash": "045402e0eb21",
   "ms": 2752
  },
  "phone.missing": {
   "hash": "4f4cdd820fca",
   "ms": 3520
  },
  "quiz.intro": {
   "hash": "f0a37944ed86",
   "ms": 1365
  },
  "quiz.pass": {
   "hash": "fd15ec4d6ef7",
   "ms": 1579
  },
  "quiz.q1": {
   "hash": "ccea71b27f30",
   "ms": 2816
  },
  "quiz.q1-why": {
   "hash": "13e1d0bb363e",
   "ms": 4907
  },
  "quiz.q2": {
   "hash": "cd7848be439a",
   "ms": 7232
  },
  "quiz.q2-why": {
   "hash": "6c2ba34e1c80",
   "ms": 4395
  },
  "quiz.q3": {
   "hash": "89aa9de29329",
   "ms": 7573
  },
  "quiz.q3-why": {
   "hash": "dc4a05d3ac97",
   "ms": 5675
  },
  "quiz.q4": {
   "hash": "9364077db598",
   "ms": 3883
  },
  "quiz.q4-why": {
   "hash": "23fa5e4d06d6",
   "ms": 2923
  },
  "quiz.retry": {
   "hash": "bae6100ef83b",
   "ms": 3349
  },
  "quiz.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "quiz.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "quiz.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "unknown.1": {
   "hash": "4d303ee3bd36",
   "ms": 4757
  },
  "unknown.2": {
   "hash": "b5c8c972be66",
   "ms": 2219
  },
  "unknown.3": {
   "hash": "4aa335a5e720",
   "ms": 6827
  },
  "unknown.4": {
   "hash": "b666af4e230b",
   "ms": 6357
  },
  "unknown.5": {
   "hash": "1af3f66c9311",
   "ms": 4139
  }
 }
});
