// Generated by tools/voice.py from pages.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("pages", {
 "lines": {
  "teach-page.1": "Here's a table of thirty-two customers. Each one is a <b>row</b>.",
  "teach-page.2": "On disk, rows aren't stored one by one. They're packed into <b>pages</b>.",
  "teach-page.3": {
   "caption": "Every page is the same size: <b>8 KB</b>.",
   "voice": "Every page is the same size. Eight kilobytes."
  },
  "teach-page.why-ask": "Now, you might be wondering about that number.",
  "teach-page.why": {
   "caption": "Disks move data in fixed-size blocks, so databases do too. Postgres uses <b>8 KB</b> pages; MySQL's InnoDB uses <b>16 KB</b>.",
   "voice": "Disks move data in fixed-size blocks, so databases do too. Postgres uses eight kilobyte pages. MySQL's InnoDB uses sixteen."
  },
  "teach-page.why-2": "Big enough to read efficiently. Small enough to keep thousands of them in memory.",
  "teach-page.skip": "Fair enough. Onward.",
  "teach-page.4": "A real page holds around a hundred rows. We'll draw four, so you can actually see them.",
  "teach-page.5": "Here's the catch. To read <b>one</b> row, the engine copies its <b>whole page</b> into memory.",
  "page.1": "Let's make that concrete. On the left, the table on disk. On the right, memory.",
  "page.predict": "You're about to fetch one customer. How much will the disk actually read?",
  "page.predict-row": "That's the intuitive answer. Let's find out.",
  "page.predict-page": "Good instinct. Let's check.",
  "page.predict-table": "Not quite that bad. Let's see.",
  "page.ask": "Go ahead. Tap any customer.",
  "page.hint": "Any numbered row on the shelf will do.",
  "page.got": {
   "caption": "You wanted <b>{asked} B</b>. The disk handed over <b>8,192 B</b>.",
   "voice": "You asked for one small row. The disk handed over the whole page. Eight kilobytes."
  },
  "page.called-it": "Exactly what you predicted.",
  "page.amp": "That ratio, bytes read over bytes wanted, is called <b>read amplification</b>. Keep an eye on it.",
  "neighbour.1": "But here's the upside. That page is sitting in memory now, with its neighbours on it.",
  "neighbour.ask": "Tap one of the other rows on that page.",
  "neighbour.hint": "The glowing rows share its page.",
  "neighbour.free": {
   "caption": "Free ride: <b>+0 B</b> read from disk.",
   "voice": "Free. Zero extra bytes from disk. The page was already here."
  },
  "neighbour.2": "Amplification drops with every neighbour you read.",
  "neighbour.3": "That's why databases work so hard to store rows that are read together, together.",
  "end.1": "That's all the narration for now. The rest of this lesson continues in guided mode."
 },
 "audio": {
  "end.1": {
   "hash": "890c35b5ed28",
   "ms": 4672
  },
  "neighbour.1": {
   "hash": "1f3b774a2582",
   "ms": 4587
  },
  "neighbour.2": {
   "hash": "a575d8988955",
   "ms": 2859
  },
  "neighbour.3": {
   "hash": "69d6e90550ca",
   "ms": 4864
  },
  "neighbour.ask": {
   "hash": "9863fc567586",
   "ms": 2155
  },
  "neighbour.free": {
   "hash": "c3ea94166f7e",
   "ms": 3861
  },
  "neighbour.hint": {
   "hash": "de1b12f24a60",
   "ms": 1749
  },
  "page.1": {
   "hash": "6c49e5c7d3b5",
   "ms": 4501
  },
  "page.amp": {
   "hash": "198c557fc8a0",
   "ms": 5696
  },
  "page.ask": {
   "hash": "56b15f7da2be",
   "ms": 1792
  },
  "page.called-it": {
   "hash": "35b8f0f24cd6",
   "ms": 1664
  },
  "page.got": {
   "hash": "e74f9c63a5ad",
   "ms": 4757
  },
  "page.hint": {
   "hash": "eec9281dbfbe",
   "ms": 1984
  },
  "page.predict": {
   "hash": "741d4d853fce",
   "ms": 3947
  },
  "page.predict-page": {
   "hash": "c81958794364",
   "ms": 1707
  },
  "page.predict-row": {
   "hash": "ba2a0f3830f9",
   "ms": 2475
  },
  "page.predict-table": {
   "hash": "581680154f2e",
   "ms": 1749
  },
  "teach-page.1": {
   "hash": "081ea4d1e7d1",
   "ms": 3499
  },
  "teach-page.2": {
   "hash": "617910e51b8e",
   "ms": 3925
  },
  "teach-page.3": {
   "hash": "816d065e7348",
   "ms": 2901
  },
  "teach-page.4": {
   "hash": "5dcf16019210",
   "ms": 5248
  },
  "teach-page.5": {
   "hash": "ea8987740083",
   "ms": 5013
  },
  "teach-page.skip": {
   "hash": "ac1166f9dc85",
   "ms": 1472
  },
  "teach-page.why": {
   "hash": "c614e364a33f",
   "ms": 10048
  },
  "teach-page.why-2": {
   "hash": "38b15e484316",
   "ms": 4395
  },
  "teach-page.why-ask": {
   "hash": "4c8f27f7c62e",
   "ms": 2219
  }
 }
});
