// Generated by tools/voice.py from select.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("select", {
 "lines": {
  "hook.1": "Remember Maya's notebook? It's four tables now: customers, products, orders, and the items in each order.",
  "hook.2": "Ten customers, eight products, sixteen orders. And the bakery has questions.",
  "hook.3": "Who lives in Lisbon? What costs the most? You could scroll. Instead, you'll ask the database.",
  "query.1": "Here's the customers table. Each row is a customer. Each column is one fact about them.",
  "query.2": {
   "caption": "A question in SQL looks like this: <b>SELECT</b> the columns you want, <b>FROM</b> a table.",
   "voice": "A question in S Q L looks like this. SELECT the columns you want, FROM a table."
  },
  "query.3": "SELECT picks columns. Every row still comes back, with only the facts you asked for.",
  "query.4": "And the answer is a table too. It's called the <k>result set</k>.",
  "query.5": "Notice what you didn't say: how to find the rows. You describe the result, and the database works out the steps.",
  "query.6": "That's what makes SQL <k>declarative</k>.",
  "pick.1": "The bakery wants to text every customer. Which columns does it need?",
  "pick.ask": "Fill in the blank to run the query.",
  "pick.hint": "A text needs a name to say hello to, and a number to send it to.",
  "pick.star": {
   "caption": "<b>*</b> means every column. Handy for a quick look, but it drags along data you don't need.",
   "voice": "Star means every column. Handy for a quick look, but it drags along data you don't need."
  },
  "pick.name": "Names alone won't reach anyone. Try again.",
  "pick.done": "Ten customers, two columns. A few phones say NULL. That means the bakery never got the number.",
  "pick.2": "In real code, list your columns rather than using star. Then a new column can't break or slow your query.",
  "shape.1": "You can compute new columns, too. The bakery is planning a ten percent price rise.",
  "shape.2": {
   "caption": "Multiply in the SELECT, and name the new column with <b>AS</b>. That name is an <k>alias</k>.",
   "voice": "Multiply in the SELECT, and name the new column with AS. That name is an alias."
  },
  "shape.3": "Next question: which cities do we deliver to? Asking for the city column repeats Lisbon three times.",
  "shape.ask": "Add DISTINCT, and repeats collapse. How many rows come back?",
  "shape.seven": "Seven. Six cities, plus one more you might not expect.",
  "shape.six": "Close. It's seven.",
  "shape.ten": "DISTINCT removes repeats, so it's fewer than ten. It's seven.",
  "shape.4": "<k id=\"distinct\">DISTINCT</k> keeps one copy of each row. Raj never gave his city, so NULL gets a row of its own.",
  "where.1": "Now a new pastry launches in Lisbon. Only Lisbon customers should get the text.",
  "where.2": "<b>WHERE</b> holds a test. The database checks it against every row, one by one.",
  "where.3": "Rows that pass stay. The rest are dropped before anything comes back.",
  "where.4": {
   "caption": "A test like <code>city = 'Lisbon'</code> is a <k>predicate</k>: true or false, for each row.",
   "voice": "A test like city equals Lisbon is called a predicate. It's true or false, for each row."
  },
  "where.5": "You can compare with equals, not equals, less than, greater than, and a few more. They're all on the card.",
  "where.6": "Text goes in single quotes. Numbers don't.",
  "filter.1": "Your turn. Get the name and phone of every customer in Lisbon.",
  "filter.ask": "Finish the query, then press Run.",
  "filter.hint": {
   "caption": "After WHERE, compare <b>city</b> with <b>'Lisbon'</b>, in single quotes.",
   "voice": "After WHERE, compare city with Lisbon, in single quotes."
  },
  "filter.error": "The database couldn't run that. Read the message under the editor, fix it, and run it again.",
  "filter.extra": "Too many rows. Is the WHERE test there?",
  "filter.missing": "Some Lisbon customers are missing. Check the spelling, with a capital L.",
  "filter.columns": "Check the columns. Just the name and the phone.",
  "filter.done": "Three customers. Ines has no phone, so she'll hear about the pastry at the counter.",
  "andor.1": "Maya calls. She paid for an order that never came. Find her orders that are pending or refunded.",
  "andor.2": "Here's a first try. Maya is customer one.",
  "andor.ask": "How many rows will it return?",
  "andor.one": "That's what we meant. But it's not what we wrote.",
  "andor.two": "Two. You spotted the trap.",
  "andor.3": "Two rows, and one of them is Raj's.",
  "andor.4": "AND binds tighter than OR. So SQL read it as: Maya's pending orders, or anybody's refunded order.",
  "andor.5": "Brackets say what you mean. Now it's only Maya's order.",
  "andor.6": {
   "caption": "Even clearer: <code>status IN ('pending', 'refunded')</code>. <b>IN</b> checks against a list.",
   "voice": "Even clearer: status IN pending, refunded. IN checks against a list."
  },
  "andor.7": "Whenever you mix AND with OR, add brackets. Interviewers look for it.",
  "order.1": "The menu board needs the three most expensive products.",
  "order.2": "Rows come back in no promised order. Today it looks like ID order. After some updates, it might not be.",
  "order.3": {
   "caption": "<k id=\"order-by\">ORDER BY</k> sorts the result. <b>DESC</b> puts the biggest first. Ascending is the default.",
   "voice": "ORDER BY sorts the result. DESC puts the biggest first. Ascending is the default."
  },
  "order.4": "<k id=\"limit\">LIMIT</k> keeps the first few rows and drops the rest. Top three, done.",
  "order.5": "Without ORDER BY, LIMIT three means any three rows. Always sort before you cut.",
  "recent.1": "The bakery wants its three most recent orders, newest first. Just the ID and the date.",
  "recent.ask": "Write the whole query this time.",
  "recent.hint": {
   "caption": "Sort by <b>ordered_at</b>, newest first, then keep three.",
   "voice": "Sort by the order date, newest first, then keep three."
  },
  "recent.error": "The database couldn't run that. The message under the editor says where it got stuck.",
  "recent.order": "Right orders, wrong order. Newest first means descending.",
  "recent.extra": "More than three rows. Add a LIMIT.",
  "recent.missing": "Not the right three. Are you sorting by the date?",
  "recent.columns": "Check the columns. The ID and the date.",
  "recent.done": "Orders sixteen, fifteen and fourteen. Sort, then cut. You'll use that pattern constantly.",
  "logic.1": "One more thing interviewers love. You write SELECT first, but the database doesn't run it first.",
  "logic.2": "It starts FROM the table, keeps the rows WHERE the test passes, then SELECTs columns, sorts, and cuts.",
  "logic.3": "That's the <k id=\"logical-order\">logical query order</k>. And it explains a classic mistake.",
  "logic.4": "An alias made in SELECT doesn't exist yet when WHERE runs. ORDER BY runs later, so it can use it.",
  "logic.5": {
   "caption": "Postgres and MySQL reject that WHERE. <b>SQLite</b>, the engine in this course, lets it slide. Don't count on it.",
   "voice": "Postgres and My S Q L reject that WHERE. S Q Lite, the engine in this course, lets it slide. Don't count on it."
  },
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "Which query returns each city exactly once?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "DISTINCT collapses repeated rows. LIMIT would just cut the list short.",
  "quiz.q2": {
   "caption": "How does SQL read <code>WHERE a = 1 AND b = 2 OR c = 3</code>?",
   "voice": "Where a equals one, and b equals two, or c equals three. How does SQL read that?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "AND binds tighter than OR, so it's grouped first. Add brackets to say what you mean.",
  "quiz.q3": {
   "caption": "A query ends in LIMIT 10, with no ORDER BY. Which ten rows come back?",
   "voice": "A query ends in limit ten, with no order by. Which ten rows come back?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "With no ORDER BY, there's no promised order. Sort first, then cut.",
  "quiz.q4": {
   "caption": "<code>SELECT price * 2 AS doubled FROM products WHERE doubled &gt; 10</code> fails in Postgres. Why?",
   "voice": "Select price times two as doubled, from products, where doubled is over ten. Postgres rejects it. Why?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "WHERE runs before SELECT, so the alias doesn't exist yet. Repeat the expression in WHERE instead.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. SELECT shapes the answer, WHERE keeps the rows you want, and ORDER BY with LIMIT picks the top.",
  "finish.2": "Next up: joining tables, and the rows each kind of join quietly drops."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "declarative": {
   "term": "Declarative",
   "def": "You describe the result you want, and the database works out how to get it. SQL is declarative."
  },
  "result-set": {
   "term": "Result set",
   "def": "The table a query returns. It has its own columns and rows, like any other table."
  },
  "alias": {
   "term": "Alias",
   "def": "A name given with AS to a column or table inside a query, like price * 1.1 AS new_price."
  },
  "distinct": {
   "term": "DISTINCT",
   "def": "Removes duplicate rows from a result, keeping one copy of each."
  },
  "predicate": {
   "term": "Predicate",
   "def": "A test that is true or false for each row, like city = 'Lisbon'. WHERE keeps the rows where it's true."
  },
  "order-by": {
   "term": "ORDER BY",
   "def": "Sorts the result, ascending unless you add DESC. Without it, the row order isn't guaranteed."
  },
  "limit": {
   "term": "LIMIT",
   "def": "Keeps only the first N rows of the result. Sort first, or you get any N rows."
  },
  "logical-order": {
   "term": "Logical query order",
   "def": "The order the clauses are evaluated: FROM, WHERE, SELECT, ORDER BY, then LIMIT. It's why an alias works in ORDER BY but not in WHERE."
  }
 },
 "audio": {
  "andor.1": {
   "hash": "d2ff1809c6e5",
   "ms": 6480
  },
  "andor.2": {
   "hash": "814e94b8e571",
   "ms": 3420
  },
  "andor.3": {
   "hash": "81fd11bda847",
   "ms": 2664
  },
  "andor.4": {
   "hash": "2a977b68e7ca",
   "ms": 8892
  },
  "andor.5": {
   "hash": "e670d3e84a25",
   "ms": 3816
  },
  "andor.6": {
   "hash": "e2bb99699cc7",
   "ms": 5940
  },
  "andor.7": {
   "hash": "52a32c9490a4",
   "ms": 4392
  },
  "andor.ask": {
   "hash": "ec6dab35afa4",
   "ms": 1872
  },
  "andor.one": {
   "hash": "104822dfc37f",
   "ms": 2988
  },
  "andor.two": {
   "hash": "0bc10e016906",
   "ms": 2268
  },
  "filter.1": {
   "hash": "ad3a788b476d",
   "ms": 4572
  },
  "filter.ask": {
   "hash": "6e9c2b0ed835",
   "ms": 2448
  },
  "filter.columns": {
   "hash": "1ded8ee88999",
   "ms": 2916
  },
  "filter.done": {
   "hash": "3dfe3108a7be",
   "ms": 5508
  },
  "filter.error": {
   "hash": "736a77e94443",
   "ms": 5508
  },
  "filter.extra": {
   "hash": "758dd34e3901",
   "ms": 2592
  },
  "filter.hint": {
   "hash": "e0785f6e37bb",
   "ms": 4320
  },
  "filter.missing": {
   "hash": "b1364b045a11",
   "ms": 4680
  },
  "finish.1": {
   "hash": "afa9d00392c7",
   "ms": 7164
  },
  "finish.2": {
   "hash": "ddcab87e85d6",
   "ms": 5940
  },
  "hook.1": {
   "hash": "59e4c583273d",
   "ms": 7056
  },
  "hook.2": {
   "hash": "018394d27289",
   "ms": 5832
  },
  "hook.3": {
   "hash": "238770faf8ee",
   "ms": 6588
  },
  "keywords.1": {
   "hash": "52c9899fd888",
   "ms": 2952
  },
  "keywords.ask": {
   "hash": "9e5d200f6173",
   "ms": 3996
  },
  "keywords.done": {
   "hash": "b410b19a541a",
   "ms": 4680
  },
  "keywords.hint": {
   "hash": "520960a4916d",
   "ms": 3168
  },
  "logic.1": {
   "hash": "83360badbb50",
   "ms": 6444
  },
  "logic.2": {
   "hash": "241bc0b136f9",
   "ms": 7020
  },
  "logic.3": {
   "hash": "93d7f3eaa7c1",
   "ms": 4067
  },
  "logic.4": {
   "hash": "52a12639b632",
   "ms": 7272
  },
  "logic.5": {
   "hash": "d16eea53f963",
   "ms": 8784
  },
  "order.1": {
   "hash": "4a631d372882",
   "ms": 3060
  },
  "order.2": {
   "hash": "b4eaaffdc5b3",
   "ms": 7524
  },
  "order.3": {
   "hash": "665231d602f0",
   "ms": 5832
  },
  "order.4": {
   "hash": "352b20758052",
   "ms": 5040
  },
  "order.5": {
   "hash": "f1eabb8b7aa0",
   "ms": 5544
  },
  "pick.1": {
   "hash": "a137671895ab",
   "ms": 4284
  },
  "pick.2": {
   "hash": "62535ff5c673",
   "ms": 6732
  },
  "pick.ask": {
   "hash": "d9664e2d82c5",
   "ms": 2232
  },
  "pick.done": {
   "hash": "eea3daf1f622",
   "ms": 6876
  },
  "pick.hint": {
   "hash": "f01424a745e4",
   "ms": 4104
  },
  "pick.name": {
   "hash": "7e11cdd00c45",
   "ms": 2448
  },
  "pick.star": {
   "hash": "0de46c38cf8a",
   "ms": 6228
  },
  "query.1": {
   "hash": "631e8658a892",
   "ms": 5508
  },
  "query.2": {
   "hash": "de693a739c18",
   "ms": 5796
  },
  "query.3": {
   "hash": "81618abe3e5d",
   "ms": 5400
  },
  "query.4": {
   "hash": "4e1fdbaaca16",
   "ms": 5076
  },
  "query.5": {
   "hash": "11722ac89328",
   "ms": 7020
  },
  "query.6": {
   "hash": "6a5905c5aac2",
   "ms": 2700
  },
  "quiz.intro": {
   "hash": "08fdf9d19fee",
   "ms": 1584
  },
  "quiz.pass": {
   "hash": "1e2c41acf108",
   "ms": 2412
  },
  "quiz.q1": {
   "hash": "b0bae7e4f2d8",
   "ms": 3204
  },
  "quiz.q1-why": {
   "hash": "981347b7cebc",
   "ms": 4428
  },
  "quiz.q2": {
   "hash": "1eb0d44cf195",
   "ms": 6660
  },
  "quiz.q2-why": {
   "hash": "fc59055c28be",
   "ms": 5760
  },
  "quiz.q3": {
   "hash": "65b9c64806bc",
   "ms": 5112
  },
  "quiz.q3-why": {
   "hash": "338bc2ed3746",
   "ms": 5256
  },
  "quiz.q4": {
   "hash": "cc36f1f5884f",
   "ms": 7740
  },
  "quiz.q4-why": {
   "hash": "6936cb2fce83",
   "ms": 6696
  },
  "quiz.retry": {
   "hash": "674b74cededc",
   "ms": 3852
  },
  "quiz.right1": {
   "hash": "5df4176b3959",
   "ms": 900
  },
  "quiz.right2": {
   "hash": "e99e52b00ddc",
   "ms": 1152
  },
  "quiz.right3": {
   "hash": "bbb1d6dfd81d",
   "ms": 972
  },
  "recent.1": {
   "hash": "6e4d02107a35",
   "ms": 5976
  },
  "recent.ask": {
   "hash": "1167a26bba38",
   "ms": 1980
  },
  "recent.columns": {
   "hash": "7cc444b3001d",
   "ms": 2700
  },
  "recent.done": {
   "hash": "dc3fa88f67b1",
   "ms": 6912
  },
  "recent.error": {
   "hash": "00a8985f7513",
   "ms": 4824
  },
  "recent.extra": {
   "hash": "647f78a975a9",
   "ms": 2664
  },
  "recent.hint": {
   "hash": "d0e1dae2768c",
   "ms": 3996
  },
  "recent.missing": {
   "hash": "4a84320e1238",
   "ms": 2988
  },
  "recent.order": {
   "hash": "7f37735ae46f",
   "ms": 4824
  },
  "shape.1": {
   "hash": "be18080d1607",
   "ms": 4788
  },
  "shape.2": {
   "hash": "e4560c043f8b",
   "ms": 5940
  },
  "shape.3": {
   "hash": "69c522f5f0fd",
   "ms": 7596
  },
  "shape.4": {
   "hash": "306cd82ac212",
   "ms": 6228
  },
  "shape.ask": {
   "hash": "f808ffb60905",
   "ms": 4284
  },
  "shape.seven": {
   "hash": "2b41f8b93148",
   "ms": 4572
  },
  "shape.six": {
   "hash": "2b6d45c09567",
   "ms": 1620
  },
  "shape.ten": {
   "hash": "f27c3e271559",
   "ms": 4284
  },
  "where.1": {
   "hash": "bd92b1332e18",
   "ms": 4824
  },
  "where.2": {
   "hash": "3f99537963b6",
   "ms": 5292
  },
  "where.3": {
   "hash": "8a9517732386",
   "ms": 4392
  },
  "where.4": {
   "hash": "5c396f0e2905",
   "ms": 5652
  },
  "where.5": {
   "hash": "1047f5bc7229",
   "ms": 7416
  },
  "where.6": {
   "hash": "0ebad4c7a60d",
   "ms": 3168
  }
 }
});
