// Generated by tools/voice.py from select.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("select", {
 "lines": {
  "hook.1": "Remember Maya's notebook? It's four tables now: customers, products, orders, and the items in each order.",
  "hook.2": "Ten customers, eight products, sixteen orders. And the bakery has questions.",
  "hook.3": "Who lives in Lisbon? What costs the most? You could scroll. Instead, you'll ask the database.",
  "query.1": "Here's the customers table. Each row is a customer. Each column is one fact about them.",
  "query.2": {
   "caption": "A question in SQL looks like this: <b>SELECT</b> the columns you want, <b>FROM</b> a table.",
   "voice": "A question in S Q L looks like this. SELECT the columns you want, FROM a table."
  },
  "query.3": "SELECT picks columns. Every row still comes back, with only the facts you asked for.",
  "query.4": "And the answer is a table too. It's called the <k>result set</k>.",
  "query.5": "Notice what you didn't say: how to find the rows. You describe the result, and the database works out the steps.",
  "query.6": "That's what makes SQL <k>declarative</k>.",
  "pick.1": "The bakery wants to text every customer. Which columns does it need?",
  "pick.ask": "Fill in the blank to run the query.",
  "pick.hint": "A text needs a name to say hello to, and a number to send it to.",
  "pick.star": {
   "caption": "<b>*</b> means every column. Handy for a quick look, but it drags along data you don't need.",
   "voice": "Star means every column. Handy for a quick look, but it drags along data you don't need."
  },
  "pick.name": "Names alone won't reach anyone. Try again.",
  "pick.done": "Ten customers, two columns. A few phones say NULL. That means the bakery never got the number.",
  "pick.2": "In real code, list your columns rather than using star. Then a new column can't break or slow your query.",
  "shape.1": "You can compute new columns, too. The bakery is planning a ten percent price rise.",
  "shape.2": {
   "caption": "Multiply in the SELECT, and name the new column with <b>AS</b>. That name is an <k>alias</k>.",
   "voice": "Multiply in the SELECT, and name the new column with AS. That name is an alias."
  },
  "shape.3": "Next question: which cities do we deliver to? Asking for the city column repeats Lisbon three times.",
  "shape.ask": "Add DISTINCT, and repeats collapse. How many rows come back?",
  "shape.seven": "Seven. Six cities, plus one more you might not expect.",
  "shape.six": "Close. It's seven.",
  "shape.ten": "DISTINCT removes repeats, so it's fewer than ten. It's seven.",
  "shape.4": "<k id=\"distinct\">DISTINCT</k> keeps one copy of each row. Raj never gave his city, so NULL gets a row of its own.",
  "where.1": "Now a new pastry launches in Lisbon. Only Lisbon customers should get the text.",
  "where.2": "<b>WHERE</b> holds a test. The database checks it against every row, one by one.",
  "where.3": "Rows that pass stay. The rest are dropped before anything comes back.",
  "where.4": {
   "caption": "A test like <code>city = 'Lisbon'</code> is a <k>predicate</k>: true or false, for each row.",
   "voice": "A test like city equals Lisbon is called a predicate. It's true or false, for each row."
  },
  "where.5": "You can compare with equals, not equals, less than, greater than, and a few more. They're all on the card.",
  "where.6": "Text goes in single quotes. Numbers don't.",
  "filter.1": "Your turn. Get the name and phone of every customer in Lisbon.",
  "filter.ask": "Finish the query, then press Run.",
  "filter.hint": {
   "caption": "After WHERE, compare <b>city</b> with <b>'Lisbon'</b>, in single quotes.",
   "voice": "After WHERE, compare city with Lisbon, in single quotes."
  },
  "filter.error": "The database couldn't run that. Read the message under the editor, fix it, and run it again.",
  "filter.extra": "Too many rows. Is the WHERE test there?",
  "filter.missing": "Some Lisbon customers are missing. Check the spelling, with a capital L.",
  "filter.columns": "Check the columns. Just the name and the phone.",
  "filter.done": "Three customers. Ines has no phone, so she'll hear about the pastry at the counter.",
  "andor.1": "Maya calls. She paid for an order that never came. Find her orders that are pending or refunded.",
  "andor.2": "Here's a first try. Maya is customer one.",
  "andor.ask": "How many rows will it return?",
  "andor.one": "That's what we meant. But it's not what we wrote.",
  "andor.two": "Two. You spotted the trap.",
  "andor.3": "Two rows, and one of them is Raj's.",
  "andor.4": "AND binds tighter than OR. So SQL read it as: Maya's pending orders, or anybody's refunded order.",
  "andor.5": "Brackets say what you mean. Now it's only Maya's order.",
  "andor.6": {
   "caption": "Even clearer: <code>status IN ('pending', 'refunded')</code>. <b>IN</b> checks against a list.",
   "voice": "Even clearer: status IN pending, refunded. IN checks against a list."
  },
  "andor.7": "Whenever you mix AND with OR, add brackets. Interviewers look for it.",
  "order.1": "The menu board needs the three most expensive products.",
  "order.2": "Rows come back in no promised order. Today it looks like ID order. After some updates, it might not be.",
  "order.3": {
   "caption": "<k id=\"order-by\">ORDER BY</k> sorts the result. <b>DESC</b> puts the biggest first. Ascending is the default.",
   "voice": "ORDER BY sorts the result. DESC puts the biggest first. Ascending is the default."
  },
  "order.4": "<k id=\"limit\">LIMIT</k> keeps the first few rows and drops the rest. Top three, done.",
  "order.5": "Without ORDER BY, LIMIT three means any three rows. Always sort before you cut.",
  "recent.1": "The bakery wants its three most recent orders, newest first. Just the ID and the date.",
  "recent.ask": "Write the whole query this time.",
  "recent.hint": {
   "caption": "Sort by <b>ordered_at</b>, newest first, then keep three.",
   "voice": "Sort by the order date, newest first, then keep three."
  },
  "recent.error": "The database couldn't run that. The message under the editor says where it got stuck.",
  "recent.order": "Right orders, wrong order. Newest first means descending.",
  "recent.extra": "More than three rows. Add a LIMIT.",
  "recent.missing": "Not the right three. Are you sorting by the date?",
  "recent.columns": "Check the columns. The ID and the date.",
  "recent.done": "Orders sixteen, fifteen and fourteen. Sort, then cut. You'll use that pattern constantly.",
  "logic.1": "One more thing interviewers love. You write SELECT first, but the database doesn't run it first.",
  "logic.2": "It starts FROM the table, keeps the rows WHERE the test passes, then SELECTs columns, sorts, and cuts.",
  "logic.3": "That's the <k id=\"logical-order\">logical query order</k>. And it explains a classic mistake.",
  "logic.4": "An alias made in SELECT doesn't exist yet when WHERE runs. ORDER BY runs later, so it can use it.",
  "logic.5": {
   "caption": "Postgres and MySQL reject that WHERE. <b>SQLite</b>, the engine in this course, lets it slide. Don't count on it.",
   "voice": "Postgres and My S Q L reject that WHERE. S Q Lite, the engine in this course, lets it slide. Don't count on it."
  },
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "Which query returns each city exactly once?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "DISTINCT collapses repeated rows. LIMIT would just cut the list short.",
  "quiz.q2": {
   "caption": "How does SQL read <code>WHERE a = 1 AND b = 2 OR c = 3</code>?",
   "voice": "Where a equals one, and b equals two, or c equals three. How does SQL read that?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "AND binds tighter than OR, so it's grouped first. Add brackets to say what you mean.",
  "quiz.q3": {
   "caption": "A query ends in LIMIT 10, with no ORDER BY. Which ten rows come back?",
   "voice": "A query ends in limit ten, with no order by. Which ten rows come back?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "With no ORDER BY, there's no promised order. Sort first, then cut.",
  "quiz.q4": {
   "caption": "<code>SELECT price * 2 AS doubled FROM products WHERE doubled &gt; 10</code> fails in Postgres. Why?",
   "voice": "Select price times two as doubled, from products, where doubled is over ten. Postgres rejects it. Why?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "WHERE runs before SELECT, so the alias doesn't exist yet. Repeat the expression in WHERE instead.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. SELECT shapes the answer, WHERE keeps the rows you want, and ORDER BY with LIMIT picks the top.",
  "finish.2": "Next up: joining tables, and the rows each kind of join quietly drops."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "declarative": {
   "term": "Declarative",
   "def": "You describe the result you want, and the database works out how to get it. SQL is declarative."
  },
  "result-set": {
   "term": "Result set",
   "def": "The table a query returns. It has its own columns and rows, like any other table."
  },
  "alias": {
   "term": "Alias",
   "def": "A name given with AS to a column or table inside a query, like price * 1.1 AS new_price."
  },
  "distinct": {
   "term": "DISTINCT",
   "def": "Removes duplicate rows from a result, keeping one copy of each."
  },
  "predicate": {
   "term": "Predicate",
   "def": "A test that is true or false for each row, like city = 'Lisbon'. WHERE keeps the rows where it's true."
  },
  "order-by": {
   "term": "ORDER BY",
   "def": "Sorts the result, ascending unless you add DESC. Without it, the row order isn't guaranteed."
  },
  "limit": {
   "term": "LIMIT",
   "def": "Keeps only the first N rows of the result. Sort first, or you get any N rows."
  },
  "logical-order": {
   "term": "Logical query order",
   "def": "The order the clauses are evaluated: FROM, WHERE, SELECT, ORDER BY, then LIMIT. It's why an alias works in ORDER BY but not in WHERE."
  }
 },
 "audio": {
  "andor.1": {
   "hash": "0606e68ffe45",
   "ms": 5973
  },
  "andor.2": {
   "hash": "75079b6a6c70",
   "ms": 2645
  },
  "andor.3": {
   "hash": "98cb8dee03a9",
   "ms": 2112
  },
  "andor.4": {
   "hash": "b97e61566337",
   "ms": 6699
  },
  "andor.5": {
   "hash": "7a91e2416933",
   "ms": 3093
  },
  "andor.6": {
   "hash": "c0f4885a96bf",
   "ms": 4288
  },
  "andor.7": {
   "hash": "3a1512ede46b",
   "ms": 3819
  },
  "andor.ask": {
   "hash": "d03d4ad5defd",
   "ms": 1621
  },
  "andor.one": {
   "hash": "bd08def788e4",
   "ms": 2347
  },
  "andor.two": {
   "hash": "871f8f53bac2",
   "ms": 1515
  },
  "filter.1": {
   "hash": "b79c6fc89a44",
   "ms": 3733
  },
  "filter.ask": {
   "hash": "4a825ac561af",
   "ms": 1963
  },
  "filter.columns": {
   "hash": "d3b9a0e05832",
   "ms": 2560
  },
  "filter.done": {
   "hash": "fd783a8cfc1b",
   "ms": 4992
  },
  "filter.error": {
   "hash": "a186282e2a85",
   "ms": 5120
  },
  "filter.extra": {
   "hash": "3b4330e24c35",
   "ms": 2112
  },
  "filter.hint": {
   "hash": "ef4b0942c055",
   "ms": 3136
  },
  "filter.missing": {
   "hash": "e5083d0b7495",
   "ms": 4139
  },
  "finish.1": {
   "hash": "e3bd7615a582",
   "ms": 6379
  },
  "finish.2": {
   "hash": "36241408a441",
   "ms": 4821
  },
  "hook.1": {
   "hash": "19118fd24cf6",
   "ms": 6507
  },
  "hook.2": {
   "hash": "937818aa6fc8",
   "ms": 4651
  },
  "hook.3": {
   "hash": "fee87ad91613",
   "ms": 5312
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "logic.1": {
   "hash": "61f975755e68",
   "ms": 5461
  },
  "logic.2": {
   "hash": "b0a70ab9a2e5",
   "ms": 5909
  },
  "logic.3": {
   "hash": "20c038ac43bd",
   "ms": 3904
  },
  "logic.4": {
   "hash": "0099bbccb1aa",
   "ms": 5909
  },
  "logic.5": {
   "hash": "d19b0d25a52c",
   "ms": 7275
  },
  "order.1": {
   "hash": "184c35327ff6",
   "ms": 3371
  },
  "order.2": {
   "hash": "4c23db369f89",
   "ms": 6549
  },
  "order.3": {
   "hash": "33d23ddf5a13",
   "ms": 5120
  },
  "order.4": {
   "hash": "e3bf12591f8c",
   "ms": 4032
  },
  "order.5": {
   "hash": "b78a3fb110d8",
   "ms": 4779
  },
  "pick.1": {
   "hash": "6cb9c65b425b",
   "ms": 3989
  },
  "pick.2": {
   "hash": "f6923bdc3fe1",
   "ms": 6528
  },
  "pick.ask": {
   "hash": "f350f2f9f6fb",
   "ms": 1792
  },
  "pick.done": {
   "hash": "dbea6a99ba91",
   "ms": 5931
  },
  "pick.hint": {
   "hash": "e1200bceb1f2",
   "ms": 3840
  },
  "pick.name": {
   "hash": "af9f1c3e4dc4",
   "ms": 2603
  },
  "pick.star": {
   "hash": "eb16636c1042",
   "ms": 5291
  },
  "query.1": {
   "hash": "97986013ba4f",
   "ms": 5547
  },
  "query.2": {
   "hash": "019076b66377",
   "ms": 4949
  },
  "query.3": {
   "hash": "6e5662e76364",
   "ms": 4971
  },
  "query.4": {
   "hash": "c68cc6154378",
   "ms": 3179
  },
  "query.5": {
   "hash": "56446d48addc",
   "ms": 6443
  },
  "query.6": {
   "hash": "bf8ad37be54e",
   "ms": 2155
  },
  "quiz.intro": {
   "hash": "f0a37944ed86",
   "ms": 1365
  },
  "quiz.pass": {
   "hash": "fd15ec4d6ef7",
   "ms": 1579
  },
  "quiz.q1": {
   "hash": "6ff00381931f",
   "ms": 3136
  },
  "quiz.q1-why": {
   "hash": "a38e402fb7c0",
   "ms": 3989
  },
  "quiz.q2": {
   "hash": "01a9f8c202ea",
   "ms": 5696
  },
  "quiz.q2-why": {
   "hash": "c2e5a7e38493",
   "ms": 4715
  },
  "quiz.q3": {
   "hash": "2aafaa21d9b0",
   "ms": 5141
  },
  "quiz.q3-why": {
   "hash": "6a7e6c53beed",
   "ms": 3904
  },
  "quiz.q4": {
   "hash": "ee57b6a8dc66",
   "ms": 6912
  },
  "quiz.q4-why": {
   "hash": "250747415b6d",
   "ms": 5760
  },
  "quiz.retry": {
   "hash": "bae6100ef83b",
   "ms": 3349
  },
  "quiz.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "quiz.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "quiz.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "recent.1": {
   "hash": "2c6c73ef895d",
   "ms": 5333
  },
  "recent.ask": {
   "hash": "63596885c66e",
   "ms": 1664
  },
  "recent.columns": {
   "hash": "85e91b02f936",
   "ms": 2453
  },
  "recent.done": {
   "hash": "9e74014db3f9",
   "ms": 5376
  },
  "recent.error": {
   "hash": "34e54d83cc55",
   "ms": 4437
  },
  "recent.extra": {
   "hash": "1e92c76f3b85",
   "ms": 2048
  },
  "recent.hint": {
   "hash": "0d71d1407a38",
   "ms": 2816
  },
  "recent.missing": {
   "hash": "f97991041073",
   "ms": 2581
  },
  "recent.order": {
   "hash": "0eb114c662cd",
   "ms": 3243
  },
  "shape.1": {
   "hash": "bb132632cc67",
   "ms": 4821
  },
  "shape.2": {
   "hash": "009f11292c73",
   "ms": 4715
  },
  "shape.3": {
   "hash": "62ba9aefcdf4",
   "ms": 6293
  },
  "shape.4": {
   "hash": "37fda8329f7b",
   "ms": 6016
  },
  "shape.ask": {
   "hash": "e4630ba48733",
   "ms": 3413
  },
  "shape.seven": {
   "hash": "e81094886ffe",
   "ms": 3136
  },
  "shape.six": {
   "hash": "cde261f54211",
   "ms": 1280
  },
  "shape.ten": {
   "hash": "fbc6321637a8",
   "ms": 3648
  },
  "where.1": {
   "hash": "8afb0635c8ce",
   "ms": 4928
  },
  "where.2": {
   "hash": "b4f81a06e4c3",
   "ms": 4501
  },
  "where.3": {
   "hash": "209830ccda94",
   "ms": 3861
  },
  "where.4": {
   "hash": "c76f86db4a57",
   "ms": 5504
  },
  "where.5": {
   "hash": "5c03ee9bebe3",
   "ms": 5547
  },
  "where.6": {
   "hash": "6e6fdd857dc2",
   "ms": 2496
  }
 }
});
