// Generated by tools/voice.py from welcome.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("welcome", {
 "lines": {
  "welcome.1": "Ana and Omar tap Buy on the bakery's last croissant at the same moment. Both get a receipt.",
  "welcome.2": "One croissant, two sales, and a database that said yes to both. By the end of this course, you'll know exactly why, and how to stop it.",
  "welcome.3": "That's what this course is: how databases really work, from the inside, all the way up to what interviewers ask.",
  "welcome.4": "No slides and no setup. You'll predict, write real SQL, and break things on purpose.",
  "welcome.ask": "So, what brings you here?",
  "welcome.interview": "Then you're in the right place. Interviewers want the why, and you'll practise saying it out loud.",
  "welcome.design": "Good. Replication, sharding and caching are all coming, and they stand on everything you build here first.",
  "welcome.curious": "The best reason there is. You'll see what the machine actually does when you press Enter.",
  "welcome.5": "Either way, we start small: a paper notebook and a pencil.",
  "story.1": "The whole course follows one place, Maya's bakery, as it grows up.",
  "story.2": "Level one: a paper <b>notebook</b>. You'll shape data so it stays correct, and ask it questions in SQL.",
  "story.3": "Level two: the bakery goes online, on <b>one server</b>. You'll see how a database stores, finds and protects every order. That's where the croissant gets sold once.",
  "story.4": "Level three: it becomes a <b>chain</b>, with many servers and a network that fails in creative ways. You'll scale out without losing data.",
  "story.5": "Level four: a whole <b>system</b> grows around the database. Caches, event streams, analytics. You'll keep them all telling the same story.",
  "story.6": "Level five is the deep end: electives on how specific database engines work.",
  "story.7": "And every new idea arrives the way it does at work: as the bakery's next real problem.",
  "how.1": "Every lesson plays like this one. I explain, and the pictures move with me.",
  "how.2": "Then it's your turn. When the film stops, the next move is yours.",
  "how.3": "At the end, an interviewer checks what stuck. It sounds like this.",
  "how.interviewer": {
   "caption": "Why can a query that returns twelve rows still read ten pages from disk?",
   "speaker": "interviewer"
  },
  "how.4": "You'll be able to answer that very soon.",
  "how.speed-ask": "Before we go on, find your pace. Tap the speed button below.",
  "how.speed-hint": "It's the button showing the playback speed, at the bottom.",
  "how.speed-ok": "Nice. You can change it, pause, or mute me whenever you like.",
  "how.5": "Prefer to read at your own pace? Switch to Guided at the top. For free play, there's Explore.",
  "path.1": "Here's your path, from the first notebook to a whole chain of stores.",
  "path.2": "Each stop is a module. Finish a lesson's labs, and it's checked off.",
  "path.3": "Your progress stays in this browser, so you can come back anytime.",
  "path.ask": "Ready? Tap the first stop to begin.",
  "path.hint": "The first stop is the glowing one.",
  "path.go": "Let's start with Maya's notebook. Bring a pencil."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {},
 "audio": {
  "how.1": {
   "hash": "15ac8b299775",
   "ms": 5580
  },
  "how.2": {
   "hash": "5531a4145461",
   "ms": 4356
  },
  "how.3": {
   "hash": "c20e279c6473",
   "ms": 4320
  },
  "how.4": {
   "hash": "a358dfe10f8c",
   "ms": 2052
  },
  "how.5": {
   "hash": "8b534b414f8c",
   "ms": 5724
  },
  "how.interviewer": {
   "hash": "283a94434279",
   "ms": 4824
  },
  "how.speed-ask": {
   "hash": "459f3cee2011",
   "ms": 3420
  },
  "how.speed-hint": {
   "hash": "3a91b707f6ce",
   "ms": 3420
  },
  "how.speed-ok": {
   "hash": "b09bd245a555",
   "ms": 4140
  },
  "path.1": {
   "hash": "e67a95db6cf4",
   "ms": 4320
  },
  "path.2": {
   "hash": "110e3a1fe82f",
   "ms": 4428
  },
  "path.3": {
   "hash": "984b6add0e2a",
   "ms": 4320
  },
  "path.ask": {
   "hash": "87d2e9dfc7bb",
   "ms": 2988
  },
  "path.go": {
   "hash": "3d654a020169",
   "ms": 3204
  },
  "path.hint": {
   "hash": "832920c0b40b",
   "ms": 2196
  },
  "story.1": {
   "hash": "ac901a2e82b3",
   "ms": 4356
  },
  "story.2": {
   "hash": "214ac749dead",
   "ms": 7164
  },
  "story.3": {
   "hash": "99a5618ff4f2",
   "ms": 11484
  },
  "story.4": {
   "hash": "f2d5483199a6",
   "ms": 8064
  },
  "story.5": {
   "hash": "0eef7df3de13",
   "ms": 8712
  },
  "story.6": {
   "hash": "ee09335a2c9b",
   "ms": 5472
  },
  "story.7": {
   "hash": "3b9123c7bdf9",
   "ms": 6156
  },
  "welcome.1": {
   "hash": "5ddfbc24203e",
   "ms": 4968
  },
  "welcome.2": {
   "hash": "dc20cce89475",
   "ms": 8172
  },
  "welcome.3": {
   "hash": "b20ff6a8dd32",
   "ms": 7524
  },
  "welcome.4": {
   "hash": "fc88e665e097",
   "ms": 6660
  },
  "welcome.5": {
   "hash": "5f7897db2192",
   "ms": 4572
  },
  "welcome.ask": {
   "hash": "3522be97da1a",
   "ms": 2088
  },
  "welcome.curious": {
   "hash": "488910a6f360",
   "ms": 4572
  },
  "welcome.design": {
   "hash": "03732cf53dad",
   "ms": 6912
  },
  "welcome.interview": {
   "hash": "a397f576a7fc",
   "ms": 5904
  }
 }
});
