// Generated by tools/voice.py from welcome.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("welcome", {
 "lines": {
  "welcome.1": "Hi. This course shows you how databases really work, from the basics to what interviewers ask.",
  "welcome.2": "No setup and no slides. You'll learn by doing: tapping, predicting, and fixing things.",
  "welcome.ask": "First, what are you getting ready for?",
  "welcome.interview": "Good. Interviewers love the why behind databases, and that's exactly what you'll practise.",
  "welcome.design": "Then the later levels are for you. Replication, sharding and caching all build on the basics here.",
  "welcome.curious": "Perfect. Curiosity is the best reason. You'll see how the machine works on the inside.",
  "welcome.3": "Either way, we start small and build up.",
  "story.1": "Everything happens in one place: Maya's bakery.",
  "story.2": "It starts with a paper <b>notebook</b>. You'll learn to shape data so it stays correct.",
  "story.3": "Then the bakery goes online, on <b>one server</b>. You'll see how a database stores, finds and protects every order.",
  "story.4": "Then it becomes a <b>chain</b>, with many stores and lots of traffic. You'll learn to scale without losing data.",
  "story.5": "For roles that go deeper, an elective level looks at specific database engines.",
  "story.6": "Every new idea arrives as the bakery's next real problem.",
  "how.1": "Every lesson plays like this one. I explain, and the pictures move with me.",
  "how.2": "Then it's your turn. When the film stops, the next move is yours.",
  "how.3": "At the end, an interviewer checks what stuck. It sounds like this.",
  "how.interviewer": {
   "caption": "Why can a query that returns twelve rows still read ten pages from disk?",
   "speaker": "interviewer"
  },
  "how.4": "You'll be able to answer that very soon.",
  "how.speed-ask": "Before we go on, find your pace. Tap the speed button below.",
  "how.speed-hint": "It's the button showing the playback speed, at the bottom.",
  "how.speed-ok": "Nice. You can change it, pause, or mute me whenever you like.",
  "how.5": "Prefer to read at your own pace? Switch to Guided at the top. For free play, there's Explore.",
  "path.1": "Here's your path, from the first notebook to a whole chain of stores.",
  "path.2": "Each stop is a module. Finish a lesson's labs, and it's checked off.",
  "path.3": "Your progress stays in this browser, so you can come back anytime.",
  "path.ask": "Ready? Tap the first stop to begin.",
  "path.hint": "The first stop is the glowing one.",
  "path.go": "Let's start with Maya's notebook. See you there."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {},
 "audio": {
  "how.1": {
   "hash": "15ac8b299775",
   "ms": 5580
  },
  "how.2": {
   "hash": "5531a4145461",
   "ms": 4356
  },
  "how.3": {
   "hash": "c20e279c6473",
   "ms": 4320
  },
  "how.4": {
   "hash": "a358dfe10f8c",
   "ms": 2052
  },
  "how.5": {
   "hash": "8b534b414f8c",
   "ms": 5724
  },
  "how.interviewer": {
   "hash": "283a94434279",
   "ms": 4824
  },
  "how.speed-ask": {
   "hash": "459f3cee2011",
   "ms": 3420
  },
  "how.speed-hint": {
   "hash": "3a91b707f6ce",
   "ms": 3420
  },
  "how.speed-ok": {
   "hash": "b09bd245a555",
   "ms": 4140
  },
  "path.1": {
   "hash": "e67a95db6cf4",
   "ms": 4320
  },
  "path.2": {
   "hash": "110e3a1fe82f",
   "ms": 4428
  },
  "path.3": {
   "hash": "984b6add0e2a",
   "ms": 4320
  },
  "path.ask": {
   "hash": "87d2e9dfc7bb",
   "ms": 2988
  },
  "path.go": {
   "hash": "64bd28b48097",
   "ms": 2664
  },
  "path.hint": {
   "hash": "832920c0b40b",
   "ms": 2196
  },
  "story.1": {
   "hash": "2942e96d1b93",
   "ms": 3564
  },
  "story.2": {
   "hash": "df091de8adbf",
   "ms": 5040
  },
  "story.3": {
   "hash": "e761b08da627",
   "ms": 6660
  },
  "story.4": {
   "hash": "1bc9a8b4fa2e",
   "ms": 6588
  },
  "story.5": {
   "hash": "d07f0cfec2e8",
   "ms": 4752
  },
  "story.6": {
   "hash": "c6c2c8b6e14c",
   "ms": 4067
  },
  "welcome.1": {
   "hash": "87e0d1f3cd8e",
   "ms": 6120
  },
  "welcome.2": {
   "hash": "e8b6179caac2",
   "ms": 7380
  },
  "welcome.3": {
   "hash": "2e3eec441ecf",
   "ms": 3024
  },
  "welcome.ask": {
   "hash": "8a5011e5e68c",
   "ms": 2484
  },
  "welcome.curious": {
   "hash": "83715bf78f2b",
   "ms": 6012
  },
  "welcome.design": {
   "hash": "e2df940654e7",
   "ms": 5940
  },
  "welcome.interview": {
   "hash": "7b463994a405",
   "ms": 6264
  }
 }
});
