// Generated by tools/voice.py from welcome.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("welcome", {
 "lines": {
  "welcome.1": "Hi. This course shows you how databases really work, from the basics to what interviewers ask.",
  "welcome.2": "No setup and no slides. You'll learn by doing: tapping, predicting, and fixing things.",
  "welcome.ask": "First, what are you getting ready for?",
  "welcome.interview": "Good. Interviewers love the why behind databases, and that's exactly what you'll practise.",
  "welcome.design": "Then the later levels are for you. Replication, sharding and caching all build on the basics here.",
  "welcome.curious": "Perfect. Curiosity is the best reason. You'll see how the machine works on the inside.",
  "welcome.3": "Either way, we start small and build up.",
  "story.1": "Everything happens in one place: Maya's bakery.",
  "story.2": "It starts with a paper <b>notebook</b>. You'll learn to shape data so it stays correct.",
  "story.3": "Then the bakery goes online, on <b>one server</b>. You'll see how a database stores, finds and protects every order.",
  "story.4": "Then it becomes a <b>chain</b>, with many stores and lots of traffic. You'll learn to scale without losing data.",
  "story.5": "For roles that go deeper, an elective level looks at specific database engines.",
  "story.6": "Every new idea arrives as the bakery's next real problem.",
  "how.1": "Every lesson plays like this one. I explain, and the pictures move with me.",
  "how.2": "Then it's your turn. When the film stops, the next move is yours.",
  "how.3": "At the end, an interviewer checks what stuck. It sounds like this.",
  "how.interviewer": {
   "caption": "Why can a query that returns twelve rows still read ten pages from disk?",
   "speaker": "interviewer"
  },
  "how.4": "You'll be able to answer that very soon.",
  "how.speed-ask": "Before we go on, find your pace. Tap the speed button below.",
  "how.speed-hint": "It's the button showing the playback speed, at the bottom.",
  "how.speed-ok": "Nice. You can change it, pause, or mute me whenever you like.",
  "how.5": "Prefer to read at your own pace? Switch to Guided at the top. For free play, there's Explore.",
  "path.1": "Here's your path, from the first notebook to a whole chain of stores.",
  "path.2": "Each stop is a module. Finish a lesson's labs, and it's checked off.",
  "path.3": "Your progress stays in this browser, so you can come back anytime.",
  "path.ask": "Ready? Tap the first stop to begin.",
  "path.hint": "The first stop is the glowing one.",
  "path.go": "Let's start with Maya's notebook. See you there."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "audio": {
  "how.1": {
   "hash": "f9001a8bc59b",
   "ms": 4352
  },
  "how.2": {
   "hash": "47c40dea4853",
   "ms": 3563
  },
  "how.3": {
   "hash": "73746a59693d",
   "ms": 3605
  },
  "how.4": {
   "hash": "b23f455a9a3c",
   "ms": 2027
  },
  "how.5": {
   "hash": "01d33a5b2ef9",
   "ms": 5035
  },
  "how.interviewer": {
   "hash": "246edd0e7859",
   "ms": 5163
  },
  "how.speed-ask": {
   "hash": "0e1d07daf1ae",
   "ms": 3691
  },
  "how.speed-hint": {
   "hash": "a763f2daf615",
   "ms": 2837
  },
  "how.speed-ok": {
   "hash": "72ce8234f2d0",
   "ms": 3563
  },
  "path.1": {
   "hash": "236cb3ab112b",
   "ms": 3563
  },
  "path.2": {
   "hash": "746b94824aaa",
   "ms": 3904
  },
  "path.3": {
   "hash": "ebe6ded223e2",
   "ms": 3584
  },
  "path.ask": {
   "hash": "6cd08bc60b65",
   "ms": 2091
  },
  "path.go": {
   "hash": "66a5fb7d1791",
   "ms": 2475
  },
  "path.hint": {
   "hash": "f5aa84648db5",
   "ms": 1877
  },
  "story.1": {
   "hash": "6cf8787118ed",
   "ms": 2944
  },
  "story.2": {
   "hash": "70160467d289",
   "ms": 4160
  },
  "story.3": {
   "hash": "0b52764bfcf4",
   "ms": 6635
  },
  "story.4": {
   "hash": "77d3b4391fe9",
   "ms": 6037
  },
  "story.5": {
   "hash": "b6ca3aefb8c6",
   "ms": 4523
  },
  "story.6": {
   "hash": "91075fab3bf2",
   "ms": 3883
  },
  "welcome.1": {
   "hash": "8687fde582ce",
   "ms": 5611
  },
  "welcome.2": {
   "hash": "342de45f37fa",
   "ms": 5376
  },
  "welcome.3": {
   "hash": "c7720184ba18",
   "ms": 2261
  },
  "welcome.ask": {
   "hash": "c748db2efa35",
   "ms": 1813
  },
  "welcome.curious": {
   "hash": "e25de6ba3331",
   "ms": 5120
  },
  "welcome.design": {
   "hash": "40cf764c9caf",
   "ms": 5845
  },
  "welcome.interview": {
   "hash": "d447c37ba961",
   "ms": 5248
  }
 }
});
