// Generated by tools/voice.py from window.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("window", {
 "lines": {
  "hook.1": "GROUP BY squeezes each group into one row. Sometimes you want to keep every row, with the group's number beside it.",
  "hook.2": "Each product next to its category's average. Each order ranked. A running total, day by day.",
  "hook.3": "That's what window functions do. Every row stays.",
  "goals.intro": "Here's what you'll be able to do by the end of this lesson.",
  "goals.1": "One. Put a group's number beside every row with OVER and PARTITION BY, and tell a window from a GROUP BY.",
  "goals.2": "Two. Rank rows with ROW_NUMBER, RANK and DENSE_RANK, and return the top N per group.",
  "goals.3": "Three. Build running totals, and compare a row with the one before it, using ORDER BY inside the window and LAG.",
  "over.1": "Here are the eight products, with their categories.",
  "over.2": "GROUP BY category gives three rows, one per category. The products are gone.",
  "over.3": "AVG of price, OVER, partition by category, keeps all eight rows, and writes each category's average beside every product.",
  "over.4": "A function with OVER is a <k id=\"window-function\">window function</k>. <k id=\"partition-by\">PARTITION BY</k> splits the rows into groups, without collapsing them.",
  "avg.1": "Your turn. Show each product's name, category and price, with its category's average price beside it.",
  "avg.ask": "Add the window function to the SELECT.",
  "avg.hint": {
   "caption": "<b>AVG(price) OVER (PARTITION BY category)</b>",
   "voice": "Average of price, over, partition by category."
  },
  "avg.error": "The database couldn't run that. Check the brackets after OVER.",
  "avg.extra": "Too many rows. There should be one per product.",
  "avg.missing": "Rows or averages are off. Partition by category, and don't add a GROUP BY.",
  "avg.columns": "Four columns: name, category, price, and the average.",
  "avg.done": "Eight rows, every product kept. Compare with the correlated subquery from last time: same numbers, one pass.",
  "rank.1": "Now ranking. Here are the products by units sold. Carrot cake and cinnamon roll are tied, at four each.",
  "rank.2": "<k id=\"row-number\">ROW_NUMBER</k> numbers the rows one, two, three. The tie gets two different numbers, in no promised order.",
  "rank.3": "RANK gives the tie the same number, five and five, then skips to seven.",
  "rank.ask": "Lemon tart comes after the tie. What does DENSE_RANK give it?",
  "rank.six": "Six. DENSE_RANK doesn't skip.",
  "rank.seven": "That's RANK. DENSE_RANK doesn't skip, so it's six.",
  "rank.five": "Five is the tie. Lemon tart comes next: six.",
  "rank.4": "<k id=\"dense-rank\">RANK and DENSE_RANK</k>: the same number for a tie, with or without a gap after it. Interviewers ask this one a lot.",
  "top.1": "A classic: the most expensive product in each category.",
  "top.2": "ROW_NUMBER, partitioned by category and ordered by price, descending. Each category counts from one again.",
  "top.3": "Now keep row number one. But WHERE can't see it: window functions are computed after WHERE.",
  "top.4": "So number the rows in a CTE, and filter in the outer query. That's <k id=\"top-n-per-group\">top N per group</k>.",
  "top2.1": "Your turn. The two most expensive products in each category.",
  "top2.ask": "Finish the window function, then filter the numbered rows.",
  "top2.hint": {
   "caption": "<b>ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) AS rn</b>, then <b>WHERE rn &lt;= 2</b>.",
   "voice": "Row number, over, partition by category, order by price descending, as r n. Then keep r n up to two."
  },
  "top2.error": "The database couldn't run that. Is the window function inside the CTE?",
  "top2.extra": "Too many rows. Keep row numbers one and two.",
  "top2.missing": "Some products are missing. Partition by category, and order by price, descending.",
  "top2.columns": "Three columns: name, category, price.",
  "top2.done": "Six products, two per category. Top N per group, done.",
  "run.1": "Window functions can also look back along the rows. Here's the bakery's revenue, day by day.",
  "run.2": "SUM of revenue, over, order by day. Each row adds itself to everything before it.",
  "run.3": {
   "caption": "That's a <k id=\"running-total\">running total</k>. By the 25th it reaches <b>161.25</b>.",
   "voice": "That's a running total. By the twenty-fifth, it reaches a hundred and sixty-one twenty-five."
  },
  "lag.1": "And LAG reads the previous row. Here are Maya's four orders.",
  "lag.2": "LAG of ordered at puts her previous order's date beside each one. Her first order has none, so it's NULL.",
  "lag.3": "Subtract, and you get the gaps: three days, seven, then thirteen. Maya's slowing down.",
  "lag.4": "<k id=\"lag\">LAG and LEAD</k> read the row before or after. Handy for gaps, changes and streaks.",
  "gap.1": "Last one. For each of Maya's orders, show the date of her previous order.",
  "gap.ask": "Use LAG, ordered by date.",
  "gap.hint": {
   "caption": "<b>LAG(ordered_at) OVER (ORDER BY ordered_at)</b>",
   "voice": "Lag of ordered at, over, order by ordered at."
  },
  "gap.error": "The database couldn't run that. Check the brackets after OVER.",
  "gap.extra": "Too many rows. Only Maya's orders: customer one.",
  "gap.missing": "Some rows or dates are off. Order the window by the order date.",
  "gap.columns": "Three columns: the order's ID, its date, and the previous date.",
  "gap.done": "Four orders, and the first has no previous one. That's LAG.",
  "recap.intro": "Let's look back at what you can do now.",
  "recap.1": "A window function works over a group but keeps every row. Eight products in, eight rows out, each with its category's average.",
  "recap.2": "Ties share a rank. RANK leaves a gap after them, DENSE_RANK doesn't. For top N per group, number the rows in a CTE, then filter outside.",
  "recap.3": "With ORDER BY inside the window, SUM becomes a running total, and LAG reads the row before. Maya's first order has no previous one.",
  "check.intro": "Now three quick checks. Each asks you to use an idea, not just name it.",
  "check.q1": {
   "caption": "<code>COUNT(*) OVER (PARTITION BY category)</code> on 8 products in 3 categories. How many rows come back?",
   "voice": "Count star, over, partition by category, on eight products in three categories. How many rows come back?"
  },
  "check.q1-why": "Eight. A window function never removes rows. Each product gets its category's count beside it.",
  "check.q2": "Four prices, from high to low: six fifty, five ninety, five ninety, two eighty. What does each function give the two eighty?",
  "check.q2-why": "ROW_NUMBER just counts, so four. RANK gives the tie two and two, then skips to four. DENSE_RANK doesn't skip, so three.",
  "check.q3": {
   "caption": "A running total of daily revenue: <code>SUM(revenue) OVER ( ? )</code>. What goes in the brackets?",
   "voice": "A running total of daily revenue: the sum of revenue, over what?"
  },
  "check.q3-why": "ORDER BY day. It lines the days up, so each row adds itself to everything before it. PARTITION BY day would restart every day.",
  "check.right1": "Right.",
  "check.right2": "Exactly.",
  "check.right3": "Correct.",
  "check.pass": {
   "caption": "<b>{right} / 3</b>. The ideas are sticking.",
   "voice": "Nicely done. The ideas are sticking."
  },
  "check.retry": {
   "caption": "<b>{right} / 3</b>. The goals marked revisit are the ones to replay.",
   "voice": "A few to revisit. The goals marked revisit at the end are the ones to replay."
  },
  "interview.intro": "Now an interview round. Two quick questions, then one you answer in your own words.",
  "interview.w1": {
   "caption": "What's the difference between ROW_NUMBER, RANK and DENSE_RANK?",
   "speaker": "interviewer"
  },
  "interview.w1-why": "They only differ on ties. ROW_NUMBER breaks them arbitrarily, RANK leaves a gap after them, and DENSE_RANK doesn't.",
  "interview.w2": {
   "caption": "When would you use a window function instead of GROUP BY?",
   "speaker": "interviewer"
  },
  "interview.w2-why": "When you need the group's value beside each row. GROUP BY collapses the group; a window keeps every row.",
  "interview.right1": "Good answer.",
  "interview.right2": "That's the one they want.",
  "interview.open": {
   "caption": "Find the top three customers by total spend in each city. Walk me through the query, and tell me what happens with ties.",
   "speaker": "interviewer"
  },
  "interview.think": "Take a minute. Say your answer out loud, as if you were in the room, or jot some notes. Then reveal the model answer.",
  "interview.hint": "Press Reveal when you're ready.",
  "interview.reveal": "Here's what an interviewer listens for. Tick the points you covered.",
  "interview.rate": "Be honest. How did you do?",
  "interview.got": "Nice. That's an answer that lands.",
  "interview.partly": "Good start. It's in your flashcards now, so it'll come back.",
  "interview.missed": "That's what practice is for. It's in your flashcards, and it'll come back.",
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. Window functions keep every row. PARTITION BY groups them, ORDER BY lines them up, and ranks, totals and LAG read along the line.",
  "finish.2": "Next up: NULL, and the quiet ways it breaks queries."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "window-function": {
   "term": "Window function",
   "def": "A function computed over a set of rows related to the current row, written with OVER. Unlike GROUP BY, every row stays."
  },
  "partition-by": {
   "term": "PARTITION BY",
   "def": "Splits the rows into groups inside OVER. The window function restarts for each partition, and no rows are collapsed."
  },
  "row-number": {
   "term": "ROW_NUMBER",
   "def": "Numbers rows 1, 2, 3 in the window's order, with no ties. Tied rows get different numbers, in no promised order."
  },
  "dense-rank": {
   "term": "RANK and DENSE_RANK",
   "def": "Both give tied rows the same number. RANK then skips numbers, like 5, 5, 7; DENSE_RANK doesn't, like 5, 5, 6."
  },
  "top-n-per-group": {
   "term": "Top N per group",
   "def": "Number rows within each group with ROW_NUMBER, then keep numbers 1 to N in an outer query, since WHERE runs before window functions."
  },
  "running-total": {
   "term": "Running total",
   "def": "SUM over the rows so far, in order: SUM(x) OVER (ORDER BY day). Each row shows the total up to and including it."
  },
  "lag": {
   "term": "LAG and LEAD",
   "def": "Read a value from the previous row, or the next one, in the window's order. The first row's LAG is NULL."
  }
 },
 "audio": {
  "avg.1": {
   "hash": "014fb7b1de67",
   "ms": 6187
  },
  "avg.ask": {
   "hash": "a5379a82dd76",
   "ms": 1899
  },
  "avg.columns": {
   "hash": "8db9ae95855d",
   "ms": 3413
  },
  "avg.done": {
   "hash": "c604b0e09e50",
   "ms": 6827
  },
  "avg.error": {
   "hash": "40d61d32c675",
   "ms": 3413
  },
  "avg.extra": {
   "hash": "eb3502a57ac4",
   "ms": 2411
  },
  "avg.hint": {
   "hash": "cc2724e29c8e",
   "ms": 2965
  },
  "avg.missing": {
   "hash": "6ff6e08d56f1",
   "ms": 4907
  },
  "check.intro": {
   "hash": "e5b8ce767e4c",
   "ms": 4352
  },
  "check.pass": {
   "hash": "2042c6b1884a",
   "ms": 2219
  },
  "check.q1": {
   "hash": "0c967980efaf",
   "ms": 6464
  },
  "check.q1-why": {
   "hash": "410ccd688683",
   "ms": 5760
  },
  "check.q2": {
   "hash": "89fd5748172a",
   "ms": 7744
  },
  "check.q2-why": {
   "hash": "5b68510f4676",
   "ms": 7147
  },
  "check.q3": {
   "hash": "7770feb26e3a",
   "ms": 3733
  },
  "check.q3-why": {
   "hash": "a9f3b7a2706c",
   "ms": 8000
  },
  "check.retry": {
   "hash": "3429b67ce974",
   "ms": 4800
  },
  "check.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "check.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "check.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "finish.1": {
   "hash": "4b14afa0154f",
   "ms": 9707
  },
  "finish.2": {
   "hash": "4c0540843f21",
   "ms": 3136
  },
  "gap.1": {
   "hash": "814a1bb85c60",
   "ms": 4075
  },
  "gap.ask": {
   "hash": "c4b9279d1c83",
   "ms": 1685
  },
  "gap.columns": {
   "hash": "b6a0efc4329d",
   "ms": 3861
  },
  "gap.done": {
   "hash": "b2177e644d05",
   "ms": 3819
  },
  "gap.error": {
   "hash": "40d61d32c675",
   "ms": 3413
  },
  "gap.extra": {
   "hash": "842868005d93",
   "ms": 3264
  },
  "gap.hint": {
   "hash": "ecc9d9242498",
   "ms": 2709
  },
  "gap.missing": {
   "hash": "27ab97f57a70",
   "ms": 3648
  },
  "goals.1": {
   "hash": "70ecd0f907f3",
   "ms": 6080
  },
  "goals.2": {
   "hash": "92f6713fbff3",
   "ms": 5227
  },
  "goals.3": {
   "hash": "01daf5fe09a1",
   "ms": 7360
  },
  "goals.intro": {
   "hash": "4f830014daa9",
   "ms": 2773
  },
  "hook.1": {
   "hash": "e41cbfc9a78b",
   "ms": 6720
  },
  "hook.2": {
   "hash": "6dfd0aff7363",
   "ms": 5717
  },
  "hook.3": {
   "hash": "50171055a967",
   "ms": 2901
  },
  "interview.got": {
   "hash": "ff3a62868565",
   "ms": 1984
  },
  "interview.hint": {
   "hash": "71671f983567",
   "ms": 1557
  },
  "interview.intro": {
   "hash": "fd2b9f5f211e",
   "ms": 4629
  },
  "interview.missed": {
   "hash": "bdb95a72e8b4",
   "ms": 3797
  },
  "interview.open": {
   "hash": "5fbabfcff23b",
   "ms": 7616
  },
  "interview.partly": {
   "hash": "68c0249489ef",
   "ms": 3243
  },
  "interview.rate": {
   "hash": "2a2b4a87bfe2",
   "ms": 1643
  },
  "interview.reveal": {
   "hash": "28474cd07ede",
   "ms": 3413
  },
  "interview.right1": {
   "hash": "ffc673b01d76",
   "ms": 896
  },
  "interview.right2": {
   "hash": "f6e03f942855",
   "ms": 1216
  },
  "interview.think": {
   "hash": "3078f157e206",
   "ms": 6912
  },
  "interview.w1": {
   "hash": "c1a6845c6e49",
   "ms": 3883
  },
  "interview.w1-why": {
   "hash": "0346ac5745d9",
   "ms": 7061
  },
  "interview.w2": {
   "hash": "aac917dc4f10",
   "ms": 3563
  },
  "interview.w2-why": {
   "hash": "8e9271b87d63",
   "ms": 6037
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "lag.1": {
   "hash": "4474ec8391c4",
   "ms": 3797
  },
  "lag.2": {
   "hash": "b98997cf432f",
   "ms": 6528
  },
  "lag.3": {
   "hash": "189bc87446b4",
   "ms": 5120
  },
  "lag.4": {
   "hash": "e8e2fffe48ed",
   "ms": 5440
  },
  "over.1": {
   "hash": "dc3df1d5434e",
   "ms": 2475
  },
  "over.2": {
   "hash": "4ba47b3cae73",
   "ms": 4480
  },
  "over.3": {
   "hash": "3c4ceac47d88",
   "ms": 8299
  },
  "over.4": {
   "hash": "c832e353a78d",
   "ms": 6379
  },
  "rank.1": {
   "hash": "7f1e070b1deb",
   "ms": 6400
  },
  "rank.2": {
   "hash": "7275084443d6",
   "ms": 6165
  },
  "rank.3": {
   "hash": "1d181acdb203",
   "ms": 4160
  },
  "rank.4": {
   "hash": "281b2c9713b0",
   "ms": 6720
  },
  "rank.ask": {
   "hash": "ff398c87db21",
   "ms": 3541
  },
  "rank.five": {
   "hash": "9e8d98bee1d9",
   "ms": 3307
  },
  "rank.seven": {
   "hash": "cd2541f361b0",
   "ms": 2667
  },
  "rank.six": {
   "hash": "8acec41fa643",
   "ms": 1749
  },
  "recap.1": {
   "hash": "23b6339cbdce",
   "ms": 7616
  },
  "recap.2": {
   "hash": "aa937a228b6d",
   "ms": 9045
  },
  "recap.3": {
   "hash": "5431b92bb990",
   "ms": 9365
  },
  "recap.intro": {
   "hash": "d0ec67520c20",
   "ms": 1963
  },
  "run.1": {
   "hash": "ce57925dbf43",
   "ms": 5675
  },
  "run.2": {
   "hash": "203262aff875",
   "ms": 5632
  },
  "run.3": {
   "hash": "bfeadc7bd466",
   "ms": 5227
  },
  "top.1": {
   "hash": "bcc2f4168a75",
   "ms": 3349
  },
  "top.2": {
   "hash": "b030873995b2",
   "ms": 6464
  },
  "top.3": {
   "hash": "e49b678a00cc",
   "ms": 5269
  },
  "top.4": {
   "hash": "81eaf5e80ffa",
   "ms": 5611
  },
  "top2.1": {
   "hash": "0de9f39b2db9",
   "ms": 3627
  },
  "top2.ask": {
   "hash": "f3f430e19113",
   "ms": 3029
  },
  "top2.columns": {
   "hash": "d1202d7e21bd",
   "ms": 2603
  },
  "top2.done": {
   "hash": "d0ce464cf2c6",
   "ms": 3413
  },
  "top2.error": {
   "hash": "2e38ab1c1447",
   "ms": 4331
  },
  "top2.extra": {
   "hash": "0d967ffce69b",
   "ms": 2624
  },
  "top2.hint": {
   "hash": "29d4f7c7c138",
   "ms": 7125
  },
  "top2.missing": {
   "hash": "d1233d05e661",
   "ms": 4949
  }
 }
});
