// Generated by tools/voice.py from window.json. Edit that file, then rebuild.
window.DataSystemsLab.Narrator.register("window", {
 "lines": {
  "hook.1": "GROUP BY squeezes each group into one row. Sometimes you want to keep every row, with the group's number beside it.",
  "hook.2": "Each product next to its category's average. Each order ranked. A running total, day by day.",
  "hook.3": "That's what window functions do. Every row stays.",
  "over.1": "Here are the eight products, with their categories.",
  "over.2": "GROUP BY category gives three rows, one per category. The products are gone.",
  "over.3": "AVG of price, OVER, partition by category, keeps all eight rows, and writes each category's average beside every product.",
  "over.4": "A function with OVER is a <k id=\"window-function\">window function</k>. <k id=\"partition-by\">PARTITION BY</k> splits the rows into groups, without collapsing them.",
  "avg.1": "Your turn. Show each product's name, category and price, with its category's average price beside it.",
  "avg.ask": "Add the window function to the SELECT.",
  "avg.hint": {
   "caption": "<b>AVG(price) OVER (PARTITION BY category)</b>",
   "voice": "Average of price, over, partition by category."
  },
  "avg.error": "The database couldn't run that. Check the brackets after OVER.",
  "avg.extra": "Too many rows. There should be one per product.",
  "avg.missing": "Rows or averages are off. Partition by category, and don't add a GROUP BY.",
  "avg.columns": "Four columns: name, category, price, and the average.",
  "avg.done": "Eight rows, every product kept. Compare with the correlated subquery from last time: same numbers, one pass.",
  "rank.1": "Now ranking. Here are the products by units sold. Carrot cake and cinnamon roll are tied, at four each.",
  "rank.2": "<k id=\"row-number\">ROW_NUMBER</k> numbers the rows one, two, three. The tie gets two different numbers, in no promised order.",
  "rank.3": "RANK gives the tie the same number, five and five, then skips to seven.",
  "rank.ask": "Lemon tart comes after the tie. What does DENSE_RANK give it?",
  "rank.six": "Six. DENSE_RANK doesn't skip.",
  "rank.seven": "That's RANK. DENSE_RANK doesn't skip, so it's six.",
  "rank.five": "Five is the tie. Lemon tart comes next: six.",
  "rank.4": "<k id=\"dense-rank\">RANK and DENSE_RANK</k>: the same number for a tie, with or without a gap after it. Interviewers ask this one a lot.",
  "top.1": "A classic: the most expensive product in each category.",
  "top.2": "ROW_NUMBER, partitioned by category and ordered by price, descending. Each category counts from one again.",
  "top.3": "Now keep row number one. But WHERE can't see it: window functions are computed after WHERE.",
  "top.4": "So number the rows in a CTE, and filter in the outer query. That's <k id=\"top-n-per-group\">top N per group</k>.",
  "top2.1": "Your turn. The two most expensive products in each category.",
  "top2.ask": "Finish the window function, then filter the numbered rows.",
  "top2.hint": {
   "caption": "<b>ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) AS rn</b>, then <b>WHERE rn &lt;= 2</b>.",
   "voice": "Row number, over, partition by category, order by price descending, as r n. Then keep r n up to two."
  },
  "top2.error": "The database couldn't run that. Is the window function inside the CTE?",
  "top2.extra": "Too many rows. Keep row numbers one and two.",
  "top2.missing": "Some products are missing. Partition by category, and order by price, descending.",
  "top2.columns": "Three columns: name, category, price.",
  "top2.done": "Six products, two per category. Top N per group, done.",
  "run.1": "Window functions can also look back along the rows. Here's the bakery's revenue, day by day.",
  "run.2": "SUM of revenue, over, order by day. Each row adds itself to everything before it.",
  "run.3": {
   "caption": "That's a <k id=\"running-total\">running total</k>. By the 25th it reaches <b>161.25</b>.",
   "voice": "That's a running total. By the twenty-fifth, it reaches a hundred and sixty-one twenty-five."
  },
  "lag.1": "And LAG reads the previous row. Here are Maya's four orders.",
  "lag.2": "LAG of ordered at puts her previous order's date beside each one. Her first order has none, so it's NULL.",
  "lag.3": "Subtract, and you get the gaps: three days, seven, then thirteen. Maya's slowing down.",
  "lag.4": "<k id=\"lag\">LAG and LEAD</k> read the row before or after. Handy for gaps, changes and streaks.",
  "gap.1": "Last one. For each of Maya's orders, show the date of her previous order.",
  "gap.ask": "Use LAG, ordered by date.",
  "gap.hint": {
   "caption": "<b>LAG(ordered_at) OVER (ORDER BY ordered_at)</b>",
   "voice": "Lag of ordered at, over, order by ordered at."
  },
  "gap.error": "The database couldn't run that. Check the brackets after OVER.",
  "gap.extra": "Too many rows. Only Maya's orders: customer one.",
  "gap.missing": "Some rows or dates are off. Order the window by the order date.",
  "gap.columns": "Three columns: the order's ID, its date, and the previous date.",
  "gap.done": "Four orders, and the first has no previous one. That's LAG.",
  "quiz.intro": "Four quick questions.",
  "quiz.q1": {
   "caption": "<code>GROUP BY category</code> returns 3 rows. How many does <code>AVG(price) OVER (PARTITION BY category)</code> return, on 8 products?",
   "voice": "Group by category returns three rows. How many does average price over partition by category return, on eight products?",
   "speaker": "interviewer"
  },
  "quiz.q1-why": "A window function keeps every row. Eight products in, eight rows out.",
  "quiz.q2": {
   "caption": "Scores 90, 80, 80, 70. What does DENSE_RANK give the 70?",
   "voice": "Scores ninety, eighty, eighty, seventy. What does dense rank give the seventy?",
   "speaker": "interviewer"
  },
  "quiz.q2-why": "The eighties share rank two, and DENSE_RANK doesn't skip, so seventy is three. RANK would say four.",
  "quiz.q3": {
   "caption": "Why can't you write <code>WHERE ROW_NUMBER() OVER (\u2026) = 1</code>?",
   "voice": "Why can't you filter on row number over something in the WHERE clause?",
   "speaker": "interviewer"
  },
  "quiz.q3-why": "Window functions are computed after WHERE. Number the rows in a CTE or subquery, then filter outside.",
  "quiz.q4": {
   "caption": "What does <code>LAG(ordered_at)</code> return on a customer's first order?",
   "voice": "What does lag of ordered at return on a customer's first order?",
   "speaker": "interviewer"
  },
  "quiz.q4-why": "There's no previous row, so it's NULL, unless you give LAG a default.",
  "quiz.right1": "Right.",
  "quiz.right2": "Exactly.",
  "quiz.right3": "Correct.",
  "quiz.pass": {
   "caption": "<b>{right} / 4</b>. Passed.",
   "voice": "Nicely done. You passed."
  },
  "quiz.retry": {
   "caption": "<b>{right} / 4</b>. Worth another pass.",
   "voice": "Not quite there. Replay a chapter or two, then try again."
  },
  "keywords.1": "Before we wrap up, here are the words worth keeping.",
  "keywords.ask": "Flip each card. Star the ones you want to practise later.",
  "keywords.hint": "Tap a card to flip it. Press Done when you're ready.",
  "keywords.done": "Starred words go to your flashcards. A few minutes a day keeps them fresh.",
  "finish.1": "That's the lesson. Window functions keep every row. PARTITION BY groups them, ORDER BY lines them up, and ranks, totals and LAG read along the line.",
  "finish.2": "Next up: how a database actually reads those rows from disk."
 },
 "speakers": {
  "interviewer": {
   "label": "Interviewer"
  }
 },
 "keywords": {
  "window-function": {
   "term": "Window function",
   "def": "A function computed over a set of rows related to the current row, written with OVER. Unlike GROUP BY, every row stays."
  },
  "partition-by": {
   "term": "PARTITION BY",
   "def": "Splits the rows into groups inside OVER. The window function restarts for each partition, and no rows are collapsed."
  },
  "row-number": {
   "term": "ROW_NUMBER",
   "def": "Numbers rows 1, 2, 3 in the window's order, with no ties. Tied rows get different numbers, in no promised order."
  },
  "dense-rank": {
   "term": "RANK and DENSE_RANK",
   "def": "Both give tied rows the same number. RANK then skips numbers, like 5, 5, 7; DENSE_RANK doesn't, like 5, 5, 6."
  },
  "top-n-per-group": {
   "term": "Top N per group",
   "def": "Number rows within each group with ROW_NUMBER, then keep numbers 1 to N in an outer query, since WHERE runs before window functions."
  },
  "running-total": {
   "term": "Running total",
   "def": "SUM over the rows so far, in order: SUM(x) OVER (ORDER BY day). Each row shows the total up to and including it."
  },
  "lag": {
   "term": "LAG and LEAD",
   "def": "Read a value from the previous row, or the next one, in the window's order. The first row's LAG is NULL."
  }
 },
 "audio": {
  "avg.1": {
   "hash": "014fb7b1de67",
   "ms": 6187
  },
  "avg.ask": {
   "hash": "a5379a82dd76",
   "ms": 1899
  },
  "avg.columns": {
   "hash": "8db9ae95855d",
   "ms": 3413
  },
  "avg.done": {
   "hash": "c604b0e09e50",
   "ms": 6827
  },
  "avg.error": {
   "hash": "40d61d32c675",
   "ms": 3413
  },
  "avg.extra": {
   "hash": "eb3502a57ac4",
   "ms": 2411
  },
  "avg.hint": {
   "hash": "cc2724e29c8e",
   "ms": 2965
  },
  "avg.missing": {
   "hash": "6ff6e08d56f1",
   "ms": 4907
  },
  "finish.1": {
   "hash": "4b14afa0154f",
   "ms": 9707
  },
  "finish.2": {
   "hash": "555b915c7e66",
   "ms": 3712
  },
  "gap.1": {
   "hash": "814a1bb85c60",
   "ms": 4075
  },
  "gap.ask": {
   "hash": "c4b9279d1c83",
   "ms": 1685
  },
  "gap.columns": {
   "hash": "b6a0efc4329d",
   "ms": 3861
  },
  "gap.done": {
   "hash": "b2177e644d05",
   "ms": 3819
  },
  "gap.error": {
   "hash": "40d61d32c675",
   "ms": 3413
  },
  "gap.extra": {
   "hash": "842868005d93",
   "ms": 3264
  },
  "gap.hint": {
   "hash": "ecc9d9242498",
   "ms": 2709
  },
  "gap.missing": {
   "hash": "27ab97f57a70",
   "ms": 3648
  },
  "hook.1": {
   "hash": "e41cbfc9a78b",
   "ms": 6720
  },
  "hook.2": {
   "hash": "6dfd0aff7363",
   "ms": 5717
  },
  "hook.3": {
   "hash": "50171055a967",
   "ms": 2901
  },
  "keywords.1": {
   "hash": "6e8f6ec7dc0f",
   "ms": 2603
  },
  "keywords.ask": {
   "hash": "b9f053603353",
   "ms": 3115
  },
  "keywords.done": {
   "hash": "050256c0adfd",
   "ms": 4096
  },
  "keywords.hint": {
   "hash": "bb3638fa922e",
   "ms": 2688
  },
  "lag.1": {
   "hash": "4474ec8391c4",
   "ms": 3797
  },
  "lag.2": {
   "hash": "b98997cf432f",
   "ms": 6528
  },
  "lag.3": {
   "hash": "189bc87446b4",
   "ms": 5120
  },
  "lag.4": {
   "hash": "e8e2fffe48ed",
   "ms": 5440
  },
  "over.1": {
   "hash": "dc3df1d5434e",
   "ms": 2475
  },
  "over.2": {
   "hash": "4ba47b3cae73",
   "ms": 4480
  },
  "over.3": {
   "hash": "3c4ceac47d88",
   "ms": 8299
  },
  "over.4": {
   "hash": "c832e353a78d",
   "ms": 6379
  },
  "quiz.intro": {
   "hash": "f0a37944ed86",
   "ms": 1365
  },
  "quiz.pass": {
   "hash": "fd15ec4d6ef7",
   "ms": 1579
  },
  "quiz.q1": {
   "hash": "cc29eb5806fe",
   "ms": 8363
  },
  "quiz.q1-why": {
   "hash": "560c19f5041f",
   "ms": 4181
  },
  "quiz.q2": {
   "hash": "8b1d7809aba9",
   "ms": 5184
  },
  "quiz.q2-why": {
   "hash": "7f5cea731d48",
   "ms": 5739
  },
  "quiz.q3": {
   "hash": "84959b39c424",
   "ms": 4267
  },
  "quiz.q3-why": {
   "hash": "7b47e66e006a",
   "ms": 7104
  },
  "quiz.q4": {
   "hash": "41a307fd1b96",
   "ms": 3947
  },
  "quiz.q4-why": {
   "hash": "c6d13350c3f3",
   "ms": 4309
  },
  "quiz.retry": {
   "hash": "bae6100ef83b",
   "ms": 3349
  },
  "quiz.right1": {
   "hash": "7fbe46dd22ea",
   "ms": 725
  },
  "quiz.right2": {
   "hash": "5217151b2ec3",
   "ms": 917
  },
  "quiz.right3": {
   "hash": "8d6cd3cbe687",
   "ms": 789
  },
  "rank.1": {
   "hash": "7f1e070b1deb",
   "ms": 6400
  },
  "rank.2": {
   "hash": "7275084443d6",
   "ms": 6165
  },
  "rank.3": {
   "hash": "1d181acdb203",
   "ms": 4160
  },
  "rank.4": {
   "hash": "281b2c9713b0",
   "ms": 6720
  },
  "rank.ask": {
   "hash": "ff398c87db21",
   "ms": 3541
  },
  "rank.five": {
   "hash": "9e8d98bee1d9",
   "ms": 3307
  },
  "rank.seven": {
   "hash": "cd2541f361b0",
   "ms": 2667
  },
  "rank.six": {
   "hash": "8acec41fa643",
   "ms": 1749
  },
  "run.1": {
   "hash": "ce57925dbf43",
   "ms": 5675
  },
  "run.2": {
   "hash": "203262aff875",
   "ms": 5632
  },
  "run.3": {
   "hash": "bfeadc7bd466",
   "ms": 5227
  },
  "top.1": {
   "hash": "bcc2f4168a75",
   "ms": 3349
  },
  "top.2": {
   "hash": "b030873995b2",
   "ms": 6464
  },
  "top.3": {
   "hash": "e49b678a00cc",
   "ms": 5269
  },
  "top.4": {
   "hash": "81eaf5e80ffa",
   "ms": 5611
  },
  "top2.1": {
   "hash": "0de9f39b2db9",
   "ms": 3627
  },
  "top2.ask": {
   "hash": "f3f430e19113",
   "ms": 3029
  },
  "top2.columns": {
   "hash": "d1202d7e21bd",
   "ms": 2603
  },
  "top2.done": {
   "hash": "d0ce464cf2c6",
   "ms": 3413
  },
  "top2.error": {
   "hash": "2e38ab1c1447",
   "ms": 4331
  },
  "top2.extra": {
   "hash": "0d967ffce69b",
   "ms": 2624
  },
  "top2.hint": {
   "hash": "29d4f7c7c138",
   "ms": 7125
  },
  "top2.missing": {
   "hash": "d1233d05e661",
   "ms": 4949
  }
 }
});
