(function registerNarrator(DSL) {
  "use strict";

  // Narrated mode: a lesson plays like a short film. A voice reads each line (pre-rendered mp3s
  // from tools/voice.py, or the browser's own speech for lines not rendered yet), the visuals
  // animate along, and the film stops whenever the learner has to act or pick a response.
  //
  // chapter = { id, title, continues?, script(n, scene) → Promise }
  // n       = { say, react, show, mount, ask, choose, wait, after, alive, lab, state }
  //
  // Lines are written in narration/<lesson>.json as { id: caption } or { id: { caption, voice } }.
  // Captions may hold markup and {placeholders}; the voice text never does.

  const { reducedMotion, retrigger } = DSL.LabKit;
  const PREFS_KEY = "dsl-narrator";
  const SPEEDS = [1, 1.25, 1.5];
  const LINE_GAP = 280;
  const IDLE_HINT = 9000;
  const SILENT_WAV = "data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=";
  let active = null;

  function readJson(key, fallback) {
    try {
      return { ...fallback, ...JSON.parse(localStorage.getItem(key) || "{}") };
    } catch (error) {
      return { ...fallback };
    }
  }

  function writeJson(key, value) {
    try {
      localStorage.setItem(key, JSON.stringify(value));
    } catch (error) {
      // Preferences and resume are conveniences.
    }
  }

  // Captions and audio durations, registered by narration/<lesson>.js (generated by tools/voice.py).
  const narrations = Object.create(null);

  function register(lessonId, bundle) {
    narrations[lessonId] = bundle;
  }

  const stripTags = (html) => html.replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ");
  const never = () => new Promise(() => {});

  // One pause switch for the whole film: timers, audio and running animations all obey it.
  function createClock() {
    let paused = false;
    let frozen = [];
    const listeners = new Set();
    return {
      get paused() { return paused; },
      set(value) {
        if (value === paused) return;
        paused = value;
        if (paused) {
          frozen = document.getAnimations().filter((animation) => animation.playState === "running");
          frozen.forEach((animation) => animation.pause());
        } else {
          frozen.forEach((animation) => animation.play());
          frozen = [];
        }
        [...listeners].forEach((listener) => listener(paused));
      },
      listen(listener) {
        listeners.add(listener);
        return () => listeners.delete(listener);
      },
      // Resolves after `ms` of unpaused time.
      sleep(ms) {
        return new Promise((resolve) => {
          let left = ms;
          let started = 0;
          let timer = null;
          const run = () => { started = performance.now(); timer = window.setTimeout(finish, left); };
          const stop = this.listen((isPaused) => {
            if (isPaused) {
              window.clearTimeout(timer);
              left -= performance.now() - started;
            } else run();
          });
          function finish() { stop(); resolve(); }
          if (!paused) run();
        });
      },
      ready() {
        if (!paused) return Promise.resolve();
        return new Promise((resolve) => {
          const stop = this.listen((isPaused) => { if (!isPaused) { stop(); resolve(); } });
        });
      },
    };
  }

  // Speaks one line at a time. play(id) resolves when the line is over (or skipped).
  function createVoice({ lessonId, lines, manifest, prefs, clock }) {
    const audio = new Audio();
    audio.preload = "auto";
    let finishCurrent = null;
    let englishVoice = null;

    function spoken(id) {
      const line = lines[id];
      if (!line) return id;
      return typeof line === "string" ? stripTags(line) : line.voice || stripTags(line.caption);
    }

    function readingTime(id) {
      const entry = manifest[id];
      if (entry) return entry.ms / prefs.speed;
      return Math.max(1400, spoken(id).split(/\s+/).length * 330) / prefs.speed;
    }

    // Voices load late (and some browsers, like Brave, may report none), so keep asking until one shows up.
    function pickVoice() {
      if (englishVoice) return englishVoice;
      const voices = window.speechSynthesis ? speechSynthesis.getVoices().filter((voice) => /^en[-_]/i.test(voice.lang)) : [];
      englishVoice = voices.find((voice) => /natural|premium|enhanced|google/i.test(voice.name)) || voices[0] || null;
      return englishVoice;
    }

    function stop() {
      if (finishCurrent) finishCurrent();
    }

    function play(id) {
      stop();
      return new Promise((resolve) => {
        const cleanups = [];
        let settled = false;
        const finish = () => {
          if (settled) return;
          settled = true;
          finishCurrent = null;
          cleanups.forEach((cleanup) => cleanup());
          resolve();
        };
        finishCurrent = finish;
        const onPause = (handler) => cleanups.push(clock.listen(handler));

        // Muted, or nothing can speak: hold the caption for its reading time.
        const silent = () => clock.sleep(readingTime(id)).then(finish);

        if (prefs.muted) return silent();

        const entry = manifest[id];
        if (entry) {
          audio.src = `audio/${lessonId}/${encodeURIComponent(id)}.mp3?v=${entry.hash}`;
          audio.playbackRate = prefs.speed;
          const ended = () => finish();
          const failed = () => { if (!settled) silent(); };
          audio.addEventListener("ended", ended);
          audio.addEventListener("error", failed);
          cleanups.push(() => {
            audio.removeEventListener("ended", ended);
            audio.removeEventListener("error", failed);
            audio.pause();
          });
          onPause((paused) => (paused ? audio.pause() : audio.play().catch(failed)));
          if (!clock.paused) audio.play().catch(failed);
          return undefined;
        }

        if (window.speechSynthesis && pickVoice()) {
          const speak = () => {
            const utterance = new SpeechSynthesisUtterance(spoken(id));
            utterance.voice = pickVoice();
            utterance.rate = prefs.speed;
            utterance.onend = () => { if (!clock.paused) finish(); };
            utterance.onerror = () => { if (!clock.paused) finish(); };
            speechSynthesis.speak(utterance);
          };
          // Browser speech can't pause reliably, so a paused line restarts from its beginning.
          onPause((paused) => { speechSynthesis.cancel(); if (!paused) speak(); });
          cleanups.push(() => speechSynthesis.cancel());
          if (!clock.paused) speak();
          return undefined;
        }

        return silent();
      });
    }

    function setSpeed() {
      audio.playbackRate = prefs.speed;
    }

    // Must run inside a click: browsers only allow audio after a user gesture.
    function unlock() {
      audio.src = SILENT_WAV;
      audio.play().catch(() => {});
      if (window.speechSynthesis) speechSynthesis.getVoices();
    }

    return { play, stop, unlock, setSpeed };
  }

  function run({ lessonId, title, chapters, onLab }) {
    const root = DSL.elements.root;
    const { lines = {}, audio: manifest = {} } = narrations[lessonId] || {};

    const saveKey = `dsl-narrated-${lessonId}`;
    const saved = readJson(saveKey, { index: 0, done: [] });
    const prefs = readJson(PREFS_KEY, { speed: 1, muted: false });
    const clock = createClock();
    const voice = createVoice({ lessonId, lines, manifest, prefs, clock });
    const done = new Set((saved.done || []).filter((id) => chapters.some((chapter) => chapter.id === id)));
    const state = {};
    let index = Math.min(Math.max(Number(saved.index) || 0, 0), chapters.length - 1);
    let token = 0;
    let started = false;
    let choiceKeys = null;

    root.innerHTML = `<div class="gd nr">
      <header class="gd-bar">
        <button type="button" class="gd-icon" data-nav-toggle aria-label="Course menu">☰</button>
        <span class="gd-title">${title}</span>
        <ol class="gd-dots" aria-label="Chapters">${chapters.map((chapter, i) => `<li><button type="button" data-chapter="${i}" aria-label="Chapter ${i + 1}: ${chapter.title}" title="${chapter.title}"></button></li>`).join("")}</ol>
        ${DSL.modeSwitch(lessonId)}
      </header>
      <section class="gd-stage nr-stage" tabindex="-1"></section>
      <div class="nr-dock">
        <div class="nr-voice" aria-hidden="true"><i></i><i></i><i></i><i></i></div>
        <p class="nr-cap" aria-live="polite"></p>
        <span class="nr-turn" hidden></span>
        <div class="nr-choices" hidden></div>
      </div>
      <footer class="nr-transport">
        <button type="button" class="nr-btn nr-prev" aria-label="Previous chapter">⏮</button>
        <button type="button" class="nr-btn nr-play" aria-label="Pause">❚❚</button>
        <button type="button" class="nr-btn nr-replay" aria-label="Replay chapter">↺</button>
        <span class="nr-chapter"></span>
        <button type="button" class="nr-btn nr-speed" aria-label="Playback speed"></button>
        <button type="button" class="nr-btn nr-mute" aria-pressed="false"></button>
        <button type="button" class="nr-btn nr-next" aria-label="Next chapter">⏭</button>
      </footer>
      <div class="nr-start">
        <div class="nr-start-card">
          <span class="nr-start-eyebrow">🎧 Narrated lesson</span>
          <h1>${title.replace(/^\d+\s·\s/, "")}</h1>
          <p>Sound on. The narrator walks you through, and stops whenever it's your turn.</p>
          <button type="button" class="button primary gd-big nr-go">▶ ${index > 0 ? `Resume · ${chapters[index].title}` : "Start"}</button>
          ${index > 0 ? `<button type="button" class="button ghost nr-over">Start over</button>` : ""}
        </div>
      </div>
    </div>`;

    const el = (selector) => root.querySelector(selector);
    const stage = el(".nr-stage");
    const dock = el(".nr-dock");
    const cap = el(".nr-cap");
    const turn = el(".nr-turn");
    const choices = el(".nr-choices");
    const playButton = el(".nr-play");
    const speedButton = el(".nr-speed");
    const muteButton = el(".nr-mute");

    function persist() {
      writeJson(saveKey, { index, done: [...done] });
    }

    function paintChrome() {
      root.querySelectorAll(".gd-dots button").forEach((dot, i) => {
        dot.className = `${done.has(chapters[i].id) ? "done" : ""}${i === index ? " current" : ""}`;
      });
      el(".nr-chapter").textContent = `${index + 1} / ${chapters.length} · ${chapters[index].title}`;
      el(".nr-prev").disabled = index === 0;
      el(".nr-next").disabled = index === chapters.length - 1;
      speedButton.textContent = `${prefs.speed}×`;
      muteButton.textContent = prefs.muted ? "🔇" : "🔊";
      muteButton.setAttribute("aria-pressed", String(prefs.muted));
      muteButton.setAttribute("aria-label", prefs.muted ? "Unmute narrator" : "Mute narrator");
    }

    function paintPlay() {
      playButton.textContent = clock.paused ? "▶" : "❚❚";
      playButton.setAttribute("aria-label", clock.paused ? "Play" : "Pause");
      dock.classList.toggle("paused", clock.paused);
    }
    clock.listen(paintPlay);

    function caption(id, vars = {}) {
      const line = lines[id];
      const text = line ? (typeof line === "string" ? line : line.caption) : `[missing line: ${id}]`;
      cap.innerHTML = text.replace(/\{(\w+)\}/g, (match, key) => (key in vars ? vars[key] : match));
      retrigger(cap, "nr-cap-in");
    }

    function setTurn(label) {
      turn.hidden = !label;
      turn.textContent = label || "";
      dock.classList.toggle("waiting", Boolean(label));
      if (label) retrigger(turn, "nr-turn-in");
    }

    function makeNarration(t, scene) {
      const alive = () => t === token && root.contains(scene);
      const after = (promise) => Promise.resolve(promise).then((value) => (alive() ? value : never()));

      let reacting = Promise.resolve();

      async function say(id, vars) {
        if (!alive()) return never();
        await after(reacting);
        await after(clock.ready());
        caption(id, vars);
        dock.classList.add("speaking");
        await after(voice.play(id));
        dock.classList.remove("speaking");
        await after(clock.sleep(LINE_GAP));
      }

      // A line spoken over the action without stopping it (a reaction mid-game). The next say waits for it.
      function react(id, vars) {
        if (!alive()) return never();
        caption(id, vars);
        dock.classList.add("speaking");
        reacting = voice.play(id).then(() => dock.classList.remove("speaking"));
        return after(reacting);
      }

      // Stop the film until the learner acts: setup(finish) wires listeners and calls finish(value),
      // or pass a promise (like the one mount returns) to wait for it.
      function ask(setup, { hint, highlight, label = "Your turn" } = {}) {
        if (!alive()) return never();
        if (typeof setup.then === "function") {
          const pending = setup;
          setup = (finish) => pending.then(finish);
        }
        setTurn(label);
        return after(new Promise((resolve) => {
          let settled = false;
          let hinting = false;
          const targets = () => (highlight ? [...scene.querySelectorAll(highlight)] : []);
          const finish = (value) => {
            if (settled || !alive()) return;
            settled = true;
            setTurn("");
            targets().forEach((target) => target.classList.remove("nr-nudge"));
            if (hinting) voice.stop();
            resolve(value);
          };
          clock.sleep(IDLE_HINT).then(() => {
            if (settled || !alive()) return;
            targets().forEach((target) => target.classList.add("nr-nudge"));
            if (hint) {
              hinting = true;
              react(hint).then(() => { hinting = false; });
            }
          });
          setup(finish);
        }));
      }

      // Put a Guided beat on stage now; the returned promise resolves when it calls done().
      // Its say() text shows as a silent caption; event(name, data) calls reach onEvent.
      function mount(beat, { onEvent } = {}) {
        return new Promise((finish) => beat.mount(scene, {
          state,
          alive,
          after,
          wait,
          prompt() {},
          say(html) {
            if (!alive() || !html) return;
            cap.innerHTML = html;
            retrigger(cap, "nr-cap-in");
          },
          done: () => finish(),
          lab,
          restart,
          event(name, data) {
            if (alive() && onEvent) onEvent(name, data);
          },
        }));
      }

      function wait(ms) {
        return after(clock.sleep(reducedMotion() ? Math.min(ms, 80) : ms));
      }

      function lab(labId) {
        if (onLab) onLab(labId);
      }

      // Stop the film for a response. options = [[key, label], …] → resolves with the chosen key.
      function choose(options, { label = "Your call" } = {}) {
        if (!alive()) return never();
        setTurn(label);
        choices.innerHTML = options.map(([key, text], i) => `<button type="button" class="nr-choice" data-key="${key}" style="--i:${i}"><kbd>${i + 1}</kbd>${text}</button>`).join("");
        choices.hidden = false;
        return after(new Promise((resolve) => {
          const pick = (button) => {
            if (!button || !alive()) return;
            choiceKeys = null;
            button.classList.add("picked");
            choices.querySelectorAll(".nr-choice").forEach((other) => { other.disabled = true; });
            clock.sleep(reducedMotion() ? 0 : 420).then(() => {
              choices.hidden = true;
              choices.innerHTML = "";
              setTurn("");
              resolve(button.dataset.key);
            });
          };
          choices.onclick = (event) => pick(event.target.closest(".nr-choice"));
          choiceKeys = (digit) => pick(choices.querySelectorAll(".nr-choice")[digit - 1]);
        }));
      }

      return {
        state,
        alive,
        after,
        say,
        react,
        ask,
        mount,
        choose,
        wait,
        show: (fn) => after(fn()),
        lab,
      };
    }

    async function play(i, direction = 1) {
      token += 1;
      const t = token;
      voice.stop();
      clock.set(false);
      choiceKeys = null;
      choices.hidden = true;
      choices.innerHTML = "";
      setTurn("");
      dock.classList.remove("speaking");
      cap.innerHTML = "";
      index = i;
      persist();
      paintChrome();

      const chapter = chapters[i];
      const old = stage.firstElementChild;
      const scene = document.createElement("div");
      scene.className = "gd-scene";
      stage.appendChild(scene);
      if (old) {
        if (!reducedMotion() && !(direction > 0 && chapter.continues)) {
          old.style.position = "absolute";
          old.style.inset = "0";
          old.animate([{ opacity: 1 }, { opacity: 0, transform: `translateX(${direction > 0 ? -48 : 48}px)` }], { duration: 220, easing: "ease-in" }).onfinish = () => old.remove();
          scene.animate([{ opacity: 0, transform: `translateX(${direction > 0 ? 48 : -48}px)` }, { opacity: 1, transform: "none" }], { duration: 320, easing: "cubic-bezier(.2,.8,.3,1)" });
        } else {
          old.remove();
        }
      }

      const n = makeNarration(t, scene);
      await chapter.script(n, scene);
      if (t !== token) return;
      done.add(chapter.id);
      persist();
      paintChrome();
      if (i < chapters.length - 1) {
        await n.wait(600);
        play(i + 1, 1);
      }
    }

    function restart() {
      done.clear();
      Object.keys(state).forEach((key) => delete state[key]);
      play(0, -1);
    }

    function start(from) {
      started = true;
      voice.unlock();
      const overlay = el(".nr-start");
      overlay.classList.add("gone");
      DSL.setTimer(() => overlay.remove(), 400);
      play(from, 1);
    }

    el(".nr-go").addEventListener("click", () => start(index));
    const over = el(".nr-over");
    if (over) over.addEventListener("click", () => {
      done.clear();
      Object.keys(state).forEach((key) => delete state[key]);
      start(0);
    });
    playButton.addEventListener("click", () => clock.set(!clock.paused));
    el(".nr-prev").addEventListener("click", () => play(index - 1, -1));
    el(".nr-next").addEventListener("click", () => play(index + 1, 1));
    el(".nr-replay").addEventListener("click", () => play(index, -1));
    speedButton.addEventListener("click", () => {
      prefs.speed = SPEEDS[(SPEEDS.indexOf(prefs.speed) + 1) % SPEEDS.length];
      writeJson(PREFS_KEY, prefs);
      voice.setSpeed();
      paintChrome();
    });
    muteButton.addEventListener("click", () => {
      prefs.muted = !prefs.muted;
      writeJson(PREFS_KEY, prefs);
      paintChrome();
    });
    cap.addEventListener("click", () => voice.stop());
    root.querySelector(".gd-dots").addEventListener("click", (event) => {
      const dot = event.target.closest("[data-chapter]");
      if (!dot || !started) return;
      const target = Number(dot.dataset.chapter);
      play(target, target >= index ? 1 : -1);
    });

    const onVisibility = () => { if (document.hidden && started) clock.set(true); };
    document.addEventListener("visibilitychange", onVisibility);

    active = {
      root,
      key(event) {
        if (!started || event.target.closest("input, textarea, select")) return;
        if (/^[1-9]$/.test(event.key) && choiceKeys) {
          event.preventDefault();
          choiceKeys(Number(event.key));
        } else if ((event.key === " " || event.key === "k") && !event.target.closest("button")) {
          event.preventDefault();
          clock.set(!clock.paused);
        }
      },
    };

    DSL.onLeave(() => {
      token += 1;
      voice.stop();
      clock.set(false);
      document.removeEventListener("visibilitychange", onVisibility);
      active = null;
    });
    paintChrome();
    paintPlay();
  }

  document.addEventListener("keydown", (event) => {
    if (active && active.root.querySelector(".nr")) active.key(event);
  });

  DSL.Narrator = Object.freeze({ run, register });
})(window.DataSystemsLab);
